({
    // Notifications
    SAFE_GRAPHICS_MODE: "Mode graphique sans échec",
    AUTH_FOR_AUTO_START: "Vous possédez des machines virtuelles qui requièrent authentification avant de pouvoir démarrer automatiquement. Appuyez sur CTRL + ALT + RET. ARR. pour activer l'authentification sécurisée.",
    AUTH_START: "Appuyez sur CTRL + ALT + RETOUR ARRIÈRE pour activer l'authentification sécurisée.",
    CTRL_SWITCH: "Pour revenir sur cet écran, utilisez :<div class='ctrlText'><span class='ctrlButton'>CTRL</span> + <span class='ctrlButton'>0</span></div>",
    SEVERAL_VMS: "L'exécution de plusieurs machines virtuelles alors que les outils OpenXT ne sont pas installés peut dégrader les performances système. Si possible, les outils OpenXT doivent être installés.",
    // Alerts
    LOW_SPACE_WARNING: "L'espace disque est insuffisant. Il reste {0}% d'espace disponible.",
    LOW_SPACE_TOOLTIP: "<strong>L'espace disque est insuffisant</strong><br/><br/>L'espace disponible est de {0}%.",
    // Errors
    AJAX_FAILED: "Échec de la requête AJAX\r\nid : {0}; méthode : {1}",
    UNEXPECTED_RESULT: "Résultat inattendu de signalRegister pour l'interface ",
    SIGNAL_ERROR: "Erreur lors de la réception de signaux ; file d'attente : {0}",
    UNEXPECTED_RCV_RESULT: "Résultats inattendus de receiveSignals",
    SERVICE_NOT_RUNNING: "Le service {0} n'est pas en cours d'exécution.",
    XT_BED_NOT_RUNNING_ACTION: "Cette action ne peut pas être réalisée car le démon Synchronizer n'est pas exécuté.",
    XT_VERSION_MISMATCH_INFO: "Impossible de se connecter au Synchronizer.  Le serveur '{0}' n'est pas compatible avec un client ''{1}'.",
    // XenConstants.ToolstackCodes
    NOT_ENOUGH_FREE_MEMORY: "Mémoire indisponible insuffisante pour satisfaire votre requête",
    VM_BAD_STATE: "La machine virtuelle se trouve dans un état inattendu",
    VM_UNEXPECTED_SHUTDOWN_REASON: "La raison évoquée pour l'arrêt ne correspond pas à la raison attendue",
    VM_NOT_SHUTDOWN: "La machine virtuelle ne s'est pas arrêtée",
    VM_ALREADY_CREATED: "La machine virtuelle est déjà créée",
    VT_MISSING: "La virtualisation matérielle doit être activée avant qu'une machine virtuelle puisse être utilisée. Vérifiez vos réglages BIOS.",
    VM_TAP_MOUNT_FAILURE: "La machine virtuelle n'a pas démarrée car elle n'est pas prête.<br/>Il est possible qu'elle soit mise à jour par un autre processus, réessayez ultérieurement.",
    HDX_AUTOSTART_MULTIPLE: "HDX et Autostart ne peuvent pas être activés simultanément sur plus d'une MV.",
    VM_HIBERNATE_FAILED: "La machine virtuelle n'a pas pu se mettre en veille prolongée",
    VM_EDIT_DISABLED: "La modification des propriétés est désactivée par la stratégie active de cette MV",
    NO_SUCH_DEVICE: "Aucun périphérique",
    VM_CANNOT_DELETE_RUNNING: "Impossible de supprimer la MV tant qu'elle est en cours d'exécution",
    VM_COUNT_HIGH: "Nombre de machines virtuelles trop important",
    DISK_NOT_EXIST: "Aucun disque",
    INCORRECT_DISK_TYPE: "Type de disque incorrect",
    INCORRECT_DEVICE_TYPE: "Type de périphérique incorrect",
    HDX_CHANGE_WHILE_RUNNING: "Impossible d'activer ou de désactiver HDX tant que la MV est en cours d'exécution",
    HDX_ENABLE_NO_TOOLS: "Impossible d'activer HDX si les outils OpenXT ne sont pas installés",
    HDX_NO_VTD: "Impossible de démarrer la MV avec HDX car VT-d n'est pas activé",
    DISK_DEVICE_EXISTS: "Impossible d'ajouter le disque spécifié, le périphérique existe déjà",
    TOOLS_REQUIRED: "Les outils OpenXT doivent être installés sur la MV pour que vous puissiez réaliser cette action",
    PROPERTY_READ_ONLY: "Propriété en lecture seule",
    PROPERTY_WRITE_ONLY: "Propriété en écriture seule",
    NO_DIAGNOSTICS: "Aucune information de diagnostic n'est actuellement recueillie",
    INCORRECT_DISK_HASH: "Le hachage sur disque ne correspond pas",
    TOO_MANY_HDX: "Impossible de démarrer la MV, un nombre trop important de MV avec HDX sont déjà en cours d'exécution",
    VM_PASSTHRU_RUNNING: "Impossible de démarrer la MV, une autre MV avec AMT pass-through est déjà en cours d'exécution",
    POLICY_SUPPRESSED_ACTION: "Cette action a été annulée par les paramètres de la stratégie active",
    VM_HIBERNATE_CHANGE: "Impossible de modifier la propriété de la MV alors qu'elle est en veille prolongée",
    NIC_NOT_FOUND: "Aucune interface réseau",
    IO_ERROR: "Erreur d'E/S",
    VM_RESUME_FAILED: "Impossible de sortir la MV du mode veille prolongée",
    OPERATION_SUPPRESSED_ACTION: "Impossible d'effectuer l'action requise car une autre opération d'arrière-plan est en cours",
    VM_NO_RPC_AGENT: "La MV n'est pas configurée pour utiliser l'agent rpc",
    VM_SLEEP_TIMEOUT: "Expiration du délai d'attente de mise en veille de la MV",
    VM_HIBERNATE_TIMEOUT: "Expiration du délai d'attente de mise en veille prolongée de la MV",
    VM_SHUTDOWN_TIMEOUT: "Expiration du délai d'attente d'arrêt de la MV",
    DEVICE_ATTACHED_ELSEWHERE: "Le périphérique est actuellement transféré vers une autre MV",
    ADAPTER_NOT_SECONDARY: "La carte graphique ne peut pas être transférée en tant que carte secondaire",
    NETWORK_NOT_RUNNNING: "Le domaine principal de réseau n'est pas exécuté",
    OEM_ACPI_RUNNING: "Impossible de démarrer la MV, une autre MV dotée de fonctionnalités oem-acpi est déjà en cours d'exécution",
    UNKNOWN_GPU: "GPU indéterminé",
    VM_TXT_SLEEP_DISABLED: "La mise en veille de l'hôte est désactivée lorsque le mode TXT Measured Launch est sélectionné",
    UNSUPPORTED_LANGUAGE: "Langue non prise en charge",
    RULE_PARSE_ERROR: "Erreur d'analyse de règle",
    // XenConstants.UpdateCodes
    UPDATE_INTERNAL_ERROR: "Une erreur interne s'est produite",
    UPDATE_DOWNLOAD_FAILED: "Échec du téléchargement",
    UPDATE_DOWNLOAD_CANCELLED: "Téléchargement annulé",
    UPDATE_MISSING_METADATA: "Métadonnées absentes",
    UPDATE_MALFORMED_METADATA: "Métadonnées incorrectes",
    UPDATE_UPDATE_NOT_APPLICABLE: "Mise à jour non applicable",
    UPDATE_ALREADY_RUNNING: "Mise à jour en cours d'exécution",
    UPDATE_VM_RUNNING: "La mise à jour ne peut pas être appliquée tant que des MV invitées sont exécutées.\nArrêtez les MV en cours d'exécution et réessayez.",
    UPDATE_CORRUPT_FILE: "Fichier endommagé rencontré",
    UPDATE_UP_TO_DATE: "Déjà mis à jour",
    UPDATE_FILE_NOT_FOUND: "Référentiel de mise à jour introuvable, vérifiez l'adresse URL",
    UPDATE_CANNOT_RESOLVE_HOST: "Impossible de résoudre l'hôte, vérifiez l'adresse URL",
    UPDATE_CANNOT_CONNECT_HOST: "Impossible de se connecter à l'hôte, vérifiez l'adresse URL",
    UPDATE_SIGNATURE_FAILED: "La signature de la mise à jour n'a pas passé la vérification",
    UPDATE_POLICY_DISABLED: "Les mises à jour sont désactivées par une stratégie",
    // XenClient.Resource.RegisterStatus
    NETWORK_DISCONNECTED_2: "Aucune connectivité réseau",
    SERVER_UNREACHABLE: "Impossible de se connecter au serveur, vérifiez l'adresse URL",
    CERT_CA_MISSING: "OpenXT n'a pas pu enregistrer ce périphérique. Vérifiez la configuration du Synchronizer et que OpenXT est correctement installé : ",
    CERT_VERIFY_FAILED: "Impossible d'authentifier le serveur :",
    CERT_GENERIC: "Une erreur générique s'est produite",
    CERT_TRUST_ROOT_CERT_FAILED: "Échec d'approbation du certificat racine",
    CERT_AUTH_CODE_MISMATCH: "Le code d'autorisation ne correspond pas à celui généré par le certificat",
    CERT_GET_CHAIN_FAILED: "Impossible d'obtenir la chaîne de certificat du serveur",
    HOSTNAME_INVALID: "Nom d'hôte non valide utilisé dans l'enregistrement",
    CERT_NO_CN: "Pas de nom commun dans le certificat de serveur",
    CERT_HOSTNAME_CN_MISMATCH: "Le nom commun du certificat ne correspond pas au nom d'hôte transmis lors de l'enregistrement, le nom commun dans le certificat est : {0}"
})
