({
    // Layout
    CREATE_FROM_MEDIA: "Créer à partir du disque d'installation",
    CREATE_VM_WIZARD_NAME_HEADER: "Nom et  type",
    TYPE_LABEL: "Type :",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 bits",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 bits",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 bits",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 bits",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 bits (expérimental)",
    TYPE_UNKNOWN: "Indéterminé",
    VM_NAME_LABEL: "Nom de la MV : ",
    DESCRIPTION_LABEL: "Description :",
    CREATE_VM_WIZARD_ICON_HEADER: "Icône",
    CREATE_VM_WIZARD_MEMORY_HEADER: "Mémoire et UC",
    CREATE_VM_WIZARD_MEMORY_ALT_HEADER: "Mémoire",
    MEMORY_LABEL: "Mémoire :",
    MB_INDICATOR_TEXT: "(Mo)",
    GB_INDICATOR_TEXT: "(Go)",
    TOTAL_MEM_MASK: "Mémoire totale : {0:n}",
    FREE_MEM_MASK: "Mémoire disponible : {0:n}",
    VCPUS_LABEL: "vCPU :",
    CREATE_VM_WIZARD_STORAGE_HEADER: "Stockage et réseau",
    STORAGE_LABEL: "Taille du disque virtuel :",
    WIRELESS_LABEL: "Réseau sans fil :",
    NETWORK_WIRELESS_OPTION: "Sans fil partagé",
    NETWORK_3G_OPTION: "3G partagé (expérimental)",
    WIRED_LABEL: "Réseau filaire :",
    NETWORK_BRIDGED_OPTION: "Relié par un pont",
    NETWORK_SHARED_OPTION: "Partagé",
    NETWORK_INTERNAL_OPTION: "Interne",
    NETWORK_BRIDGED_MASK: "Relié par un pont sur {0}",
    NETWORK_SHARED_MASK: "Partagé sur {0}",
    NETWORK_INTERNAL_MASK: "Interne {0}",
    WIRED_NETWORK_INFORMATION: "Un réseau <strong>relié par un pont</strong> connecte une MV directement au réseau externe.<br/>Un réseau <strong>partagé</strong> réutilise la même adresse IP de réseau pour toutes les MV.<br/>Le réseau <strong>interne</strong> n'est connecté à aucun réseau externe.",
    CREATE_VM_WIZARD_FINISH_HEADER: "Terminer",
    CREATE_VM_WIZARD_FINISH_PARA1: "Vous êtes prêt à créer une MV à partir du disque d'installation du SE.",
    AUTOSTART_LABEL: "Démarrer la MV et installer le SE",
    AUTOSTART_OFF_LABEL: "Créer la MV et installer le SE ultérieurement",
    CREATE_VM_WIZARD_FINISH_PARA2: "Une fois l'installation du SE terminée, double-cliquez sur le <strong>CD virtuel des outils OpenXT</strong> pour installer les outils OpenXT.",
    // Errors
    NAME_VALERROR: "Un nom est requis. Il ne peut pas dépasser 60 caractères et peut contenir des lettres, des chiffres, des espaces et certains signes de ponctuation (notamment trait de soulignement, tiret, parenthèses, point, apostrophe et virgule).",
    DESCRIPTION_VALERROR: "La description ne doit pas dépasser 200 caractères et peut contenir des lettres, des chiffres, des espaces et certains signes de ponctuation (notamment trait de soulignement, tiret, parenthèses, point, apostrophe et virgule).",
    VM_ERRORS: "La machine virtuelle a été créée, mais des erreurs se sont produites. Vérifiez les paramètres de votre nouvelle machine virtuelle."
})
