({
    // Layout
    CREATE_STATUS_REPORT: "Créer un rapport d'état",
    REPORT_WELCOME: "Bienvenue",
    REPORT_DESCRIPTION: "Cet assistant recueille des informations de diagnostic sur ce système.<br/><ul><li>Il recueille la sortie de dmesg Xen, des informations sur la configuration matérielle de votre machine, des informations sur la build de Xen que vous utilisez ainsi que divers journaux.<br/><br/></li><li>Les informations recueillies seront téléchargeables au format .tar.bz2 à des fins d'archivage ou d'envoi à un conseiller du support technique.</li></ul>",
    REPORT_VM_DESCRIPTION: "Cet outil peut éventuellement recueillir des informations de diagnostic auprès de MV, y compris des journaux et copies d'écran des MV actuellement exécutées. Cela peut s'avérer très utile pour diagnostiquer des problèmes techniques.",
    REPORT_INCLUDE_VMSCREENS: "Inclure des copies d'écran des MV dans ce rapport",
    REPORT_INCLUDE_VMS: "Inclure d'autres informations de diagnostic des MV dans ce rapport",
    REPORT_INFO: "Les journaux peuvent contenir des informations confidentielles et si cela soulève des inquiétudes, excluez explicitement les journaux MV de l'archive. L'exclusion de certaines informations relatives à une MV du rapport peut empêcher le diagnostic de votre problème.",
    REPORT_SUMMARY: "Description",
    REPORT_DETAILS: "Entrez un récapitulatif du problème et une description détaillée",
    SUMMARY_LABEL: "Récapitulatif :",
    SUMMARY_VALERROR: "Un récapitulatif est requis. Il ne peut pas dépasser 60 caractères et peut contenir des lettres, des chiffres, des espaces et certains signes de ponctuation (notamment des traits de soulignement, tirets, parenthèses, points, apostrophes et virgules).",
    DESCRIPTION_LABEL: "Description :",
    REPORT_SUMMARY_INFO: "Essayez de limiter votre récapitulatif à huit mots.",
    REPORT_STEPS: "Reproduction",
    REPORT_REPRO: "Si possible, décrivez les étapes à suivre pour reproduire ce problème.",
    REPORT_REPRO_LABEL: "Étapes à reproduire :",
    REPORT_TICKET: "Si vous disposez d'un numéro d'incident ou d'un numéro de ticket, entrez-le ici.",
    REPORT_TICKET_LABEL: "Numéro d'incident :",
    REPORT_GENERATION: "Génération",
    REPORT_SERVER_DESCRIPTION: "Une fois généré, cet assistant rendra le rapport disponible en téléchargement en exécutant un serveur Web dédié temporaire sur cette machine. Vous pouvez ensuite entrer l'adresse URL correspondante dans votre navigateur Web.<br/><br/>Si vous n'avez pas l'intention de le télécharger immédiatement, décochez la case à cocher suivante.",
    REPORT_SERVER: "Activer le téléchargement du rapport une fois qu'il a été généré",
    REPORT_FINISHED: "L'assistant a recueilli suffisamment d'informations pour générer un rapport d'état.<br/><br/>Vérifiez et cliquez sur Suivant pour générer le rapport.",
    GENERATING_REPORT: "Génération du rapport, veuillez patienter...",
    STATUS_SERVER_INFO: "Vous ne devez autoriser le téléchargement de rapports que si votre réseau informatique est sécurisé et que votre administrateur vous y a autorisé.",
    REPORT_FINISH: "Terminer",
    REPORT_CREATED: "Le rapport d'état suivant a été créé avec succès :<br/><br/><strong>{0}</strong>",
    REPORT_FINISH_SERVER: "Pour télécharger un rapport, utilisez la section Rapport d'état dans les paramètres système.",
    STOP_SERVER: "Si vous fermez cet assistant, les rapports ne seront plus disponibles en téléchargement.",
    SERVE_REPORT: "Les rapports sont disponibles en téléchargement  sur une autre machine à l'adresse :\n\n{0}\n\nIls sont disponibles en téléchargement sur des MV sur cette machine à l'adresse :\n\n{1}"
})