({
    // Layout
    SYS_INFO_HEADER: "Paramètres système",
    SYS_INFO_WALLPAPER_TITLE: "Papier peint",
    SYS_INFO_POWER_TITLE: "Alimentation",
    SYS_INFO_TOUCHPAD_TITLE: "Interface",
    SYS_INFO_TRANSMITTER_TITLE: "Synchronizer",
    SYS_INFO_AUTH_TITLE: "Connexion",
    SYS_INFO_SOFTWARE_TITLE: "Logiciel",
    SYS_INFO_HARDWARE_TITLE: "Matériel",
    SYS_INFO_NETWORK_TITLE: "Gestion de réseau",
    STATUS_REPORT_HEADER: "Rapport d'état",
    WALLPAPER_HEADER: "Cliquez sur l'image du papier peint que vous souhaitez utiliser",
    VENDOR_LABEL: "Fournisseur :",
    MODEL_LABEL: "Modèle :",
    BIOS_REV_LABEL: "Révision BIOS :",
    TOTAL_MEM_LABEL: "Mémoire physique totale :",
    MEMORY_MASK: "{0:n} Mo",
    FREE_MEM_LABEL: "Mémoire physique disponible :",
    FREE_STORAGE_LABEL: "Espace disque disponible :",
    TOTAL_STORAGE_LABEL: "Espace disque total :",
    DISK_SPACE_MASK: "{0:n} Mo",
    CPU_MODEL_LABEL: "Modèle UC physique :",
    GPU_MODEL_LABEL: "Modèle GPU physique :",
    ETH0_MAC_ADDRESS_LABEL: "Adresse MAC filaire :",
    ETH0_MODEL_LABEL: "Modèle filaire :",
    HOST_AMT_PT_LABEL: "Ad. MAC pass-through :",
    ON_TEXT: "Activé(e)",
    OFF_TEXT: "Désactivé(e)",
    WIRELESS_MAC_ADDRESS_LABEL: "Adresse MAC sans fil :",
    WIRELESS_MODEL_LABEL: "Modèle sans fil :",
    XENCLIENT_VERSION_LABEL: "Version de OpenXT :",
    XENCLIENT_VERSION_MASK: "{0} (branche {1})",
    XENCLIENT_BUILD_LABEL: "Build OpenXT :",
    XENCLIENT_BUILD_MASK: "{0} ({1:d MMMM y})",
    TOOLS_VERSION_LABEL: "Version du CD Outils :",
    UPDATE_TITLE: "Mise à jour logicielle",
    UPDATE_TOOLTIP: "Votre administrateur doit fournir l'adresse URL pour mettre à jour OpenXT",
    UPDATE_ACTION: "Rechercher les mises à jour",
    CANCEL_DOWNLOAD_ACTION: "Annuler le téléchargement",
    DISCARD_UPDATE_ACTION: "Ignorer mise à jour",
    UPDATE_SHUTDOWN: "Le téléchargement a réussi, redémarrez votre périphérique pour appliquer la mise à jour",
    LID_CLOSE_LABEL: "Action à la fermeture du capot",
    LID_CLOSE_AC_POWER_LABEL: "Secteur :",
    SLEEP_ALL_OPTION: "Mettre le système en veille",
    DO_NOTHING_OPTION: "Ne rien faire",
    LID_CLOSE_BATTERY_LABEL: "Batterie :",
    BRIGHTNESS_LABEL: "Luminosité de l'écran",
    TOUCHPAD_OPTIONS: "Options du touchpad",
    TAP_TO_CLICK_LABEL: "Tap du touchpad pour cliquer :",
    SCROLLING_LABEL: "Défilement du touchpad :",
    SPEED_LABEL: "Vitesse du touchpad",
    SLOW: "Lent",
    FAST: "Rapide",
    LEFT: "Gauche",
    RIGHT: "Droite",
    POINTER_TRAIL: "Traces de la souris",
    NONE_TEXT: "Aucune",
    SHORT_TEXT: "Courtes",
    LONG_TEXT: "Longues",
    KEYBOARD_LAYOUT: "Configuration du clavier",
    LANGUAGE_HEADER: "Langue",
    TRANSMITTER_STATE_LABEL: "État :",
    TRANSMITTER_STATE_UNREGISTERED: "Non enregistré",
    TRANSMITTER_STATE_PREREGISTERED: "Pré-enregistré",
    TRANSMITTER_STATE_CONNECTED: "Connecté",
    TRANSMITTER_STATE_DISCONNECTED: "Déconnecté",
    TRANSMITTER_URL_LABEL: "Nom d'hôte du Synchronizer :",
    TRANSMITTER_VERSION_LABEL: "Version :",
    TRANSMITTER_BUILD_LABEL: "Build : ",
    TRANSMITTER_LOGGEDIN_LABEL: "Utilisateur enregistré :",
    TRANSMITTER_HEADER: "Enregistrez-vous auprès d'un Synchronizer pour télécharger des nouvelles MV et les sauvegarder.",
    REGISTER_ACTION: "Enregistrer",
    CONNECT_ACTION: "Connecter avec Synchronizer",
    AUTH_SET_PASSWORD_TEXT: "Définissez un mot de passe pour activer l'authentification locale.",
    SET_PASSWORD_ACTION: "Définir le mot de passe",
    CHANGE_PASSWORD_ACTION: "Modifier le mot de passe",
    AUTH_REQUIRED_TEXT: "Mot de passe au démarrage :",
    AUTH_SET_TIMEOUT_TEXT: "Délai de verrouillage de l'écran :",
    STATUS_REPORT: "Un rapport d'état collecte les informations de diagnostic sur ce périphérique et les enregistre dans un fichier.<br/><br/>Vous pouvez générer  un rapport à tout moment en appuyant sur CTRL+ALT+R",
    CREATE_STATUS_REPORT: "Créer un rapport d'état",
    STATUS_SERVER_HEADER: "Téléchargement du rapport",
    STATUS_SERVER: "Reportez-vous au chapitre Dépannage du guide de l'utilisateur OpenXT pour obtenir de l'aide sur le téléchargement de vos rapports d'état.",
    BEGIN_STATUS_SERVER: "Autoriser le téléchargement des rapports",
    STATUS_SERVER_INFO: "Vous ne devez autoriser le téléchargement de rapports que si votre réseau informatique est sécurisé et que votre administrateur vous y a autorisé.",
    CLOSE_ACTION: "Fermer",
    SAVE_ACTION: "Enregistrer",
    SYS_INFO_DISPLAY_TITLE: "Affichage",
    SEAMLESS_HEADER: "Changement de souris",
    SWITCHER_LABEL: "Changement de souris :",
    RESISTANCE_LABEL: "Changement de la résistance:",
    KEYBOARD_LABEL: "Clavier suit la souris :",
    ADAPTER_LABEL: "Définissez l'ordre de vos cartes graphiques pour les mouvements de souris homogènes.",
    LANGUAGE_WARNING: "Le paramètre de langue a été modifié et l'interface utilisateur doit être redémarrée.",
    // Other
    AUTH_MANAGED_TEXT: "Utilisez les informations d'identification de votre Synchronizer pour ouvrir une session.",
    MINUTE: "minute",
    MINUTES: "minutes",
    NEVER: "jamais",
    ALREADY_CONNECTED: "Vous êtes déjà connecté au Synchronizer.",
    UPDATE_HEADER: "Mise à jour logicielle",
    CANNOT_UPGRADE: "Version de OpenXT installée : {0}\nDernière version de OpenXT : {1}\n\nIl n'est pas possible de mettre à jour vers cette version de OpenXT.",
    CAN_UPGRADE: "Version  de OpenXT installée : {0}\nDernière version de OpenXT : {1}\n\nUne nouvelle version de OpenXT a été détectée, voulez-vous télécharger cette mise à jour ?\n\nReportez-vous à la documentation pour en savoir plus sur l'impact de cette mise à jour sur votre système.",
    UP_TO_DATE: "Version de OpenXT installée : {0}\nDernière version de OpenXT : {1}\n\nVous utilisez la dernière version de OpenXT, mais vous pouvez l'actualiser en la téléchargeant et en l'installant de nouveau.\n\nReportez-vous à la documentation pour en savoir plus sur l'impact de cette mise à jour sur votre système.",
    START_DOWNLOAD_ACTION: "Télécharger",
    SERVE_REPORT: "Les rapports sont disponibles en téléchargement sur une autre machine à l'adresse :\n\n{0}\n\nIls sont disponibles en téléchargement sur des MV sur cette machine à l'adresse :\n\n{1}",
    STOP_STATUS_SERVER: "Désactiver le téléchargement des rapports",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "Suisse",
    KEYBOARD_LAYOUT_CN: "Chine",
    KEYBOARD_LAYOUT_FR: "France",
    KEYBOARD_LAYOUT_DE: "Allemagne",
    KEYBOARD_LAYOUT_IT: "Italie",
    KEYBOARD_LAYOUT_JP: "Japon",
    KEYBOARD_LAYOUT_ES: "Espagne",
    KEYBOARD_LAYOUT_GB: "Royaume-Uni",
    KEYBOARD_LAYOUT_US: "États-Unis",
    KEYBOARD_LAYOUT_RU: "Russie",
    KEYBOARD_LAYOUT_CA: "Canada",
    KEYBOARD_LAYOUT_BR: "Brésil",
    KEYBOARD_LAYOUT_NL: "Pays-Bas",
    KEYBOARD_LAYOUT_NO: "Norvège",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Corée",
    KEYBOARD_LAYOUT_BE: "Belgique",
    KEYBOARD_LAYOUT_DK: "Danemark",
    KEYBOARD_LAYOUT_IN: "Inde",
    KEYBOARD_LAYOUT_SE: "Suède",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English"
})
