({
    // Layout
    DEFERRED_INSTALL_TITLE: "Bienvenue dans OpenXT",
    EULA_HEADER: "CLUF",
    KEYBOARD_HEADER: "Configuration du clavier",
    KEYBOARD_INSTR: "Sélectionnez une configuration de clavier.",
    LANGUAGE_HEADER: "Langue",
    LANGUAGE_INSTR: "Sélectionnez une langue.",
    ROOT_PASSWORD_HEADER: "Mot de passe du système",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "Suisse",
    KEYBOARD_LAYOUT_CN: "Chine",
    KEYBOARD_LAYOUT_FR: "France",
    KEYBOARD_LAYOUT_DE: "Allemagne",
    KEYBOARD_LAYOUT_IT: "Italie",
    KEYBOARD_LAYOUT_JP: "Japon",
    KEYBOARD_LAYOUT_ES: "Espagne",
    KEYBOARD_LAYOUT_GB: "Royaume-Uni",
    KEYBOARD_LAYOUT_US: "États-Unis",
    KEYBOARD_LAYOUT_RU: "Russie",
    KEYBOARD_LAYOUT_CA: "Canada",
    KEYBOARD_LAYOUT_BR: "Brésil",
    KEYBOARD_LAYOUT_NL: "Pays-Bas",
    KEYBOARD_LAYOUT_NO: "Norvège",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Corée",
    KEYBOARD_LAYOUT_BE: "Belgique",
    KEYBOARD_LAYOUT_DK: "Danemark",
    KEYBOARD_LAYOUT_IN: "Inde",
    KEYBOARD_LAYOUT_SE: "Suède",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English",
    // Errors
    EULA_ERROR: "Veuillez accepter ce CLUF pour utiliser OpenXT. Si vous annulez, OpenXT sera fermé.",
    KEYBOARD_ERROR: "Sélectionnez une configuration de clavier.",
    SET_SYSTEM_PASSWORD: "OpenXT requiert un mot de passe système."
})
