({
    // Controls
    START: "Démarrer",
    BACKGROUND_START: "Démarrage silencieux",
    SHUT_DOWN: "Arrêter",
    FORCE_SHUT_DOWN: "Forcer arrêt",
    LOGIN: "Connexion",
    DETAILS: "Détails",
    DELETE: "Supprimer",
    // Tooltips
    XC_TOOLS_NOT_INSTALLED: "<strong>Les outils OpenXT ne sont pas installés</strong><br/><br/>Double-cliquez sur le CD virtuel des outils OpenXT dans le SE de votre MV pour l'installer.",
    XC_TOOLS_OLD_VERSION: "<strong>Les outils OpenXT ne sont pas à jour</strong><br/><br/>Double-cliquez sur le CD virtuel des outils OpenXT dans le SE de votre MV pour le mettre à niveau.",
    // Layout
    NAME_MASK: "Nom : {0}",
    STATUS_MASK: "État : {0}",
    SLOT_MASK: "Touche de sélection : CTRL + {0}",
    // VM States
    VM_CREATED : "démarrage",
    VM_STOPPED : "inactif",
    VM_STOPPING : "arrêt en cours",
    VM_REBOOTING : "redémarrage",
    VM_REBOOTED : "redémarré",
    VM_PAUSED : "actif",
    VM_SUSPENDING : "mise en veille prolongée",
    VM_SUSPENDED : "en veille prolongée",
    VM_RUNNING : "actif",
    VM_LOCKED : "verrouillé",
    VM_ASLEEP : "en veille",
    // XenConstants.DesktopStates
    PUBLISHING: "téléchargement",
    BACKING_UP: "sauvegarde en cours",
    DOWNLOADING: "téléchargement",
    UPDATING: "mise à jour",
    FORCE_UPDATING: "forcer la mise à jour",
    READY: "prêt",
    LOCKED: "verrouillé",
    REMOTE_LOCKED: "verrouillé",
    UNMANAGED: "non géré",
    // XenConstants.SyncOpStates
    PREPARING: "Préparation",
    PREPARATION_FAILED: "Échec de la préparation",
    TRANSFER_PENDING: "Transfert en attente",
    COMPUTING_DIGEST: "Calcul de la somme de contrôle",
    TRANSFER_ACTIVE: "Transfert en cours",
    TRANSFER_PAUSED: "Suspendu",
    TRANSFER_FAILED: "Échec",
    TRANSFER_NETINT_STALLED: "En attente... serveur inaccessible",
    TRANSFER_ADMCTL_STALLED: "En attente... serveur occupé",
    INSTALLING_IMAGE: "Installation de l'image",
    TRANSFER_FINISHED: "Transfert terminé",
    SHUTDOWN_REQUIRED: "Arrêt requis",
    CLEAN_SHUTDOWN_REQUIRED: "Arrêt correct requis",
    BACKGROUND_FAILED: "Échec de l'opération d'arrière-plan"
})
