({
    // Layout
    START: "Démarrer",
    BACKGROUND_START: "Démarrage silencieux",
    SHUT_DOWN: "Arrêter",
    REBOOT: "Redémarrer",
    HIBERNATE: "Veille prolongée",
    SLEEP: "Veille",
    FORCE_SHUT_DOWN: "Forcer arrêt",
    LOGIN: "Connexion",
    UPLOAD_VM: "Télécharger MV",
    BACKUP_NOW: "Sauvegarder maintenant",
    CHECK_NOW: "Vérifier",
    ADD_DEVICE: "Ajouter un périphérique",
    DELETE: "Supprimer",
    DETAILS: "Détails",
    PAUSE: "Suspendre",
    RESUME: "Continuer",
    RETRY: "Réessayer",
    CANCEL: "Annuler",
    GENERAL: "Général",
    DEVICES: "Périphériques",
    DEVICE: "Périphérique",
    NO_DEVICES: "Aucun périphérique connecté",
    OPTIONS: "Options",
    ACTIONS: "Actions",
    ALWAYS_USE: "Toujours utiliser avec cette MV",
    DISCONNECT: "Déconnecter",
    SYNCHRONIZATION: "Synchronisation",
    HARDWARE: "Matériel",
    ICON: "Icône",
    ADVANCED: "Avancé",
    NAME: "Nom :",
    VCPUS: "vCPU :",
    MEMORY: "Mémoire (Mo) :",
    AUTOBOOT: "Autoboot :",
    AUTOBOOT_TOOLTIP: "Démarrer cette MV au démarrage de l'hôte.",
    POWER_BEHAVIOUR: "Contrôle de l'alimentation :",
    POWER_BEHAVIOUR_TOOLTIP: "Lorsque la MV est arrêtée, mise en veille ou en veille prolongée, le périphérique hôte fait de même.",
    POWER_BEHAVIOUR_ENABLED: "Le contrôle de l'alimentation affecte la MV et l'hôte",
    POWER_BEHAVIOUR_DISABLED: "Le contrôle de l'alimentation affecte uniquement la MV",
    SWITCHER_KEY: "Touche de sélection :",
    TOOLS_CD: "CD Outils :",
    INSTALLED_TOOLS_MASK: "Installé : {0}",
    THREED_GFX: "Graphiques 3D :",
    TYPE: "Type :",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 bits",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 bits",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 bits",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 bits",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 bits (expérimental)",
    TYPE_UNKNOWN: "Indéterminé",
    DESCRIPTION: "Description :",
    REGISTERED_USER: "Utilisateur enregistré :",
    BACKUP_MODE: "Mode de sauvegarde :",
    BACKUP_NONE: "Aucune",
    BACKUP_USER: "Données utilisateur",
    BACKUP_ALL: "Toutes les données",
    BACKUP_SCHEDULE: "Planification de sauvegarde :",
    UPDATE_SCHEDULE: "Planification des mises à jour :",
    LEASE_EXPIRATION: "Expiration du bail :",
    SAVE_ACROSS_REBOOTS: "Enregistrer les modifications des redémarrages :",
    DESKTOP_NAME: "Nom du bureau :",
    CURRENT_VERSION: "Version actuelle :",
    BASE_VERSION: "Version parente :",
    WIRELESS_NETWORK: "Réseau sans fil :",
    WIRED_NETWORK: "Réseau filaire :",
    WIRED_NIC: "Adresse MAC filaire :",
    DISK_SPACE: "Espace disque :",
    ALLOW_OEM: "Autoriser l'installation de Windows OEM :",
    EXPOSE_HARDWARE_INFO: "Exposer les informations matérielles physiques :",
    DISPLAY_VM: "Afficher MV dans la barre de sélection :",
    AMT_PASSTHROUGH: "Intel AMT pass-through :",
    OEM_ACPI_PASSTHROUGH: "Exposer le matériel OEM physique :",
    BOOT_ORDER: "Ordre de démarrage :",
    EDIT: "Modifier",
    SAVE: "Enregistrer",
    CLOSE: "Fermer",
    MANAGED_ENABLED: "MV gérée",
    THREED_GRAPHICS_ENABLED: "Graphiques 3D activés",
    PUBLISH_APP_ENABLED: "Publier des applications",
    ENABLED: "Activé(e)",
    DISABLED: "Désactivé(e)",
    NONE: "Aucune",
    INSTALLED_NONE: "Tools non installé",
    NEVER: "Jamais",
    ATTACHED: "Attaché",
    SHARED_WIRELESS: "Sans fil partagé",
    SHARED_3G: "3G partagé (expérimental)",
    BRIDGED: "Relié par un pont",
    SHARED: "Partagé",
    INTERNAL: "Interne",
    BRIDGED_MASK: "Relié par un pont sur {0}",
    SHARED_MASK: "Partagé sur {0}",
    INTERNAL_MASK: "Interne sur {0}",
    POLICY_DISABLED: "Désactivé par une stratégie",
    CHANGE_VERSION: "Changer la version",
    NAME_VALERROR: "Un nom est requis. Il ne peut pas dépasser 60 caractères et peut contenir des lettres, des chiffres, des espaces et certains signes de ponctuation (notamment trait de soulignement, tiret, parenthèses, point, apostrophe et virgule).",
    DESCRIPTION_VALERROR: "La description ne doit pas dépasser 200 caractères et peut contenir des lettres, des chiffres, des espaces et certains signes de ponctuation (notamment trait de soulignement, tiret, parenthèses, point, apostrophe et virgule).",
    MEMORY_MASK: "{0:n}",
    SYSTEM_MEMORY_MASK: "Total : {0:n}, disponible : {1:n}",
    DISK_SPACE_MASK: "Privé : {0}, partagé : {1}",
    BACKUP_FREQUENCY_MASK: "{0:n} heure(s)",
    UPDATE_FREQUENCY_MASK: "{0:n} minute(s)",
    LEASE_EXPIRATION_MASK: "{0:n} jour(s)",
    BACKUP_LAST_MASK: "Dernière sauvegarde : {0:d MMMM y H:mm} (UTC)",
    UPDATE_LAST_MASK: "Dernière mise à jour : {0:d MMMM y H:mm} (UTC)",
    BACKUP_SCHEDULE_MASK: "Prochaine sauvegarde : {0:d MMMM y H:mm} (UTC)",
    UPDATE_SCHEDULE_MASK: "Prochaine recherche de mises à jour : {0:d MMMM y H:mm} (UTC)",
    LEASE_SCHEDULE_MASK: "Prochaine : {0:d MMMM y H:mm} (UTC)",
    BACKUP_LAST_MASK_1: "Dernière sauvegarde il y a {0:n} heure(s), {1:n} minute(s)",
    UPDATE_LAST_MASK_1: "Dernière mise à jour il y a {0:n} heure(s), {1:n} minute(s)",
    BACKUP_NEXT_MASK: "Prochaine sauvegarde dans {0:n} heure(s), {1:n} minute(s)",
    UPDATE_NEXT_MASK: "Prochaine recherche de mise à jour dans {0:n} heure(s), {1:n} minute(s)",
    LEASE_NEXT_MASK: "Prochaine dans {0:n} jour(s), {1:n} heure(s)",
    NETWORK_INFORMATION: "Un réseau <strong>relié par un pont</strong> connecte une MV directement au réseau externe.<br/>Un réseau <strong>partagé</strong> réutilise la même adresse IP de réseau pour toutes les MV.<br/>Le réseau <strong>interne</strong> n'est connecté à aucun réseau externe.",
    TRANSFER: "Transférer",
    TRANSFER_STATE: "État :",
    TRANSFER_PROGRESS: "Progression :",
    TRANSFER_SPEED_MASK: "{0:f} Mo/s",
    SWITCHER_KEY_MASK: "CTRL + {0}",
    SWITCHER_DROPDWON_MASK: " ({0})",
    THIS_VM: "cette MV",
    CD_DRIVE: "Lecteur CD",
    HARD_DRIVE: "Disque dur",
    NETWORK: "Réseau",
    BOOT_TITLE: "Ajouter une option de démarrage...",
    HDX_TOOLTIP: "Seule une machine virtuelle à la fois peut exécuter cette fonctionnalité sur le système. Pour activer cette dernière, la machine virtuelle doit être arrêtée et les outils OpenXT ainsi que les pilotes vidéo Intel doivent être installés.",
    MEMORY_TOOLTIP: "Cette fonctionnalité ne peut pas être modifiée lorsque la machine virtuelle est en veille prolongée.",
    VCPU_TOOLTIP: "Cette fonctionnalité ne peut pas être modifiée lorsque la machine virtuelle est en veille prolongée.",
    DISK_SPACE_TOOLTIP: "Privé : quantité d'espace disque utilisée par cette machine virtuelle.<br/>Partagé : quantité d'espace disque partagée avec d'autres machine virtuelles sur ce système.",
    AMT_PT_TOOLTIP: "L'activation d'Intel Active Management Technology (AMT) Management Engine (ME) offre une gestion de réseau au niveau matériel qui permet l'accès hors bande aux périphériques OpenXT à des fins d'administration. Cette fonctionnalité ne peut être activée que sur une MV.",
    ACPI_PT_TOOLTIP: "Expose la table ACPI SLIC hôte à la MV afin de déverrouiller les éditions OEM de Windows.",
    SMBIOS_PT_TOOLTIP: "Expose les types d'enregistrement SMBIOS décrivant le matériel hôte à la MV plutôt que ceux fournis par OpenXT.",
    OEM_ACPI_PT_TOOLTIP: "Expose le matériel OEM directement à la MV. Cette fonctionnalité ne peut être activée que sur une MV.",
    POWER: "Alimentation",
    COMMUNICATION: "Prise en charge des applications transparentes :",
    COMMUNICATION_TOOLTIP: "Contrôle les paramètres de pare-feu de la machine virtuelle de façon à ce que les applications transparentes fonctionnent.",
    ADVANCED_WARNING: "Cette section est dédiée aux fonctionnalités avancées et ne doit être modifiée que si vous comprenez leur impact sur le système.",
    INTEL_AMT: "OpenXT doit être redémarré pour que Intel AMT ME pass-through prenne effet.",
    MEMORY_CHANGE: "Les modifications apportées à la mémoire seront appliquées au prochain démarrage de la machine virtuelle.",
    BACKUP_VM: "Sauvegarder MV",
    VM_UPDATE_CHECK: "Rechercher les mises à jour de MV",
    DELETE_VM_HEADER: "Supprimer machine virtuelle",
    DELETE_VM: "Êtes-vous sûr de vouloir supprimer la machine virtuelle '{0}' ?",
    ACCEPT_DELETE: "Oui, la supprimer",
    XEN_MGR_DELETE: "Supprimer MV",
    USB_UNASSIGN: "Ce périphérique USB est actuellement utilisé par cette MV. Si vous le désélectionnez, il sera retiré de force de cette MV, ce qui peut entraîner la perte de données. Vous pouvez le retirer correctement en l'éjectant du système d'exploitation de votre MV.",
    UPLOAD_VM_STATUS: "Vous pouvez uniquement télécharger une machine virtuelle lorsqu'elle arrêtée.",
    ADD_DEVICE_STATUS: "Vous pouvez uniquement connecter un périphérique lorsque la machine virtuelle est en marche et que les outils OpenXT sont installés",
    DELETE_VM_STATUS: "Vous pouvez uniquement supprimer une machine virtuelle lorsqu'elle est arrêtée ou en veille prolongée",
    FORCE_UPDATE: "Erreur de la mise à jour forcée de la MV",
    USB_DISABLED: "Impossible d'ajouter un périphérique car la gestion des périphériques a été désactivée pour cette MV"
})
