({
    // Default message in AlertDialog
    UNKNOWN_ERROR: "Unknown internal error",
    UNKNOWN: "Unknown",
    // Alerts
    servicevm_requested_attention: "<strong>Attention Requested</strong><br/>VM '{0}' in slot {1} is requesting your attention. To switch focus to VM '{0}', open it from the Services menu.",
    uservm_requested_attention: "<strong>Attention Requested</strong><br/>VM '{0}' is requesting your attention. To switch focus to VM '{0}', press CTRL+{1} or click on it's icon.",
    storage_space_low: "<strong>Disk space low</strong><br/>Only {0}% of your disk space is currently free.",
    vm_updated_reboot_required: "<strong>Restart {0} VM</strong><br/>To apply recent updates, you must restart your {0} VM.",
    vm_updated_clean_reboot_required: "<strong>Start and restart {0} VM</strong><br/>To apply the recent updates, you must first start your {0} VM and then restart it.",
    vm_lease_near_expiry: "<strong>Renew {0} VM lease</strong><br/>Your {0} VM lease is about to expire. To renew it, you must connect to the synchronizer.",
    platform_update_ready: "<strong>OpenXT update is ready</strong><br/>To apply this update, you must restart your physical computer.",
    battery_critical: "<strong>Battery is running low</strong><br/>To avoid losing work, connect your computer to a power source or shut it down.",
    GENERIC_MESSAGE: "<strong>{0}</strong><br/>{1}",
    GENERIC_PROGRESS_MESSAGE: "<strong>{0}</strong><br/>{1}<br/><div class='citrixProgressBar citrixProgressBarEmpty'><div class='citrixProgressBarFull' style='width: {2}%;'><div class='citrixProgressBarTile'></div><span style='visibility:hidden'>&nbsp;</span></div><div class='citrixProgressBarLabel'>{2}%</div></div>",
    MEASURED_BOOT_FAILED: "'Measured Launch' failed.\n\nYour system may be compromised, continue with caution.",
    MEASURED_BOOT_DISABLED: "'Measured Launch' has not been enabled on this device. Please consult the documentation, or contact your system administrator.",
    // Notifications
    SAFE_GRAPHICS_MODE: "Safe graphics mode",
    AUTH_FOR_AUTO_START: "You have virtual machines that require authentication before they can automatically boot. Press Control + Alt + Backspace to enable secure authentication.",
    UNLICENSED_WARNING: "This copy of OpenXT is not licensed - contact your administrator",
    AUTH_START: "Press Control + Alt + Backspace to enable secure authentication.",
    AUTH_START_HEADING: "Authorization needed",
    CTRL_SWITCH: "To return to this screen, use:<div class='ctrlText'><span class='ctrlButton'>CTRL</span> + <span class='ctrlButton'>0</span></div>",
    SEVERAL_VMS: "Running several virtual machines without OpenXT tools installed can cause poor system performance. If possible, OpenXT tools should be installed.",
    // Errors
    AUTH_SSL_CACERT_ERROR: "The client no longer trusts the security certificate of your synchronizer server. To continue to use synchronizer functionality, you must re-register with it.\n\nDo you wish to do this now?",
    AJAX_FAILED: "AJAX request failed\r\nid: {0}; method: {1}",
    UNEXPECTED_RESULT: "Unexpected result from signalRegister for interface ",
    SIGNAL_ERROR: "Error receiving signals; queue: {0}",
    UNEXPECTED_RCV_RESULT: "Unexpected result from receiveSignals",
    SERVICE_NOT_RUNNING: "The {0} service is not running.",
    XT_BED_NOT_RUNNING_ACTION: "This action cannot be completed because the Synchronizer daemon is not running.",
    XT_VERSION_MISMATCH_INFO: "Cannot connect to Synchronizer.  '{0}' server is not compatible with a '{1}' client.",
    // XenConstants.ToolstackCodes
    NOT_ENOUGH_FREE_MEMORY: "Not enough free memory was available for your request",
    VM_BAD_STATE: "The virtual machine is in an unexpected state",
    VM_UNEXPECTED_SHUTDOWN_REASON: "The shutdown reason didn't match the expected one",
    VM_NOT_SHUTDOWN: "The virtual machine didn't shutdown",
    VM_ALREADY_CREATED: "The virtual machine is already created",
    VT_MISSING: "Hardware virtualization must be enabled before a virtual machine can be used. Please check your BIOS settings.",
    VM_TAP_MOUNT_FAILURE: "The virtual machine failed to start due to not being in a ready state.<br/>This may be due to another process updating it, please try again in a few moments.",
    HDX_AUTOSTART_MULTIPLE: "HDX and Autostart cannot be simultaneously activated on more than one VM.",
    VM_HIBERNATE_FAILED: "The virtual machine failed to hibernate",
    VM_EDIT_DISABLED: "Editing of properties is disabled by this VM's active policy",
    NO_SUCH_DEVICE: "No such device",
    VM_CANNOT_DELETE_RUNNING: "Unable to delete the VM while it is running",
    VM_COUNT_HIGH: "Too many virtual machines",
    DISK_NOT_EXIST: "No such disk",
    INCORRECT_DISK_TYPE: "Incorrect disk type",
    INCORRECT_DEVICE_TYPE: "Incorrect device type",
    HDX_CHANGE_WHILE_RUNNING: "Unable to turn HDX on or off while the VM is running",
    HDX_ENABLE_NO_TOOLS: "Unable to turn on HDX without OpenXT tools installed",
    HDX_NO_VTD: "Unable to start VM with HDX because VT-d is not enabled",
    DISK_DEVICE_EXISTS: "Failed to add specified disk, device already exists",
    TOOLS_REQUIRED: "Performing this action requires OpenXT tools to be installed on the VM",
    PROPERTY_READ_ONLY: "Property is read-only",
    PROPERTY_WRITE_ONLY: "Property is write-only",
    NO_DIAGNOSTICS: "Currently not gathering diagnostic information",
    INCORRECT_DISK_HASH: "Disk hash does not match",
    TOO_MANY_HDX: "Unable to start VM, too many VMs with HDX are already running",
    VM_PASSTHRU_RUNNING: "Unable to start VM, another VM with AMT pass-through is already running",
    POLICY_SUPPRESSED_ACTION: "This action has been suppressed by the active policy settings",
    VM_HIBERNATE_CHANGE: "Unable to change this VM property while it is hibernated",
    NIC_NOT_FOUND: "No such network interface",
    IO_ERROR: "IO error",
    VM_RESUME_FAILED: "Failed to resume VM from sleep",
    OPERATION_SUPPRESSED_ACTION: "Unable to complete requested action because another background operation is in progress",
    VM_NO_RPC_AGENT: "The VM is not configured to use rpc agent",
    VM_SLEEP_TIMEOUT: "Timeout waiting for VM to sleep",
    VM_HIBERNATE_TIMEOUT: "Timeout waiting for VM to hibernate",
    VM_SHUTDOWN_TIMEOUT: "Timeout waiting for VM to shutdown",
    DEVICE_ATTACHED_ELSEWHERE: "The device is currently being passed through to another VM",
    ADAPTER_NOT_SECONDARY: "The graphics card cannot be passed through as a secondary adapter",
    NETWORK_NOT_RUNNNING: "Network backend domain is not running",
    OEM_ACPI_RUNNING: "Unable to start VM, another VM with oem-acpi features is already running",
    UNKNOWN_GPU: "Unknown GPU",
    VM_TXT_SLEEP_DISABLED: "Host sleep is disabled while in TXT measured launch",
    UNSUPPORTED_LANGUAGE: "Unsupported language",
    RULE_PARSE_ERROR: "Rule parse error",
    ENCRYPTION_KEY_EXISTS: "Encryption key already exists",
    VHD_ALREADY_ENCRYPTED: "VHD file already contains encryption key",
    NETWORK_DAEMON_TIMEOUT: "Timeout waiting for network daemon to become ready",
    FILE_DOES_NOT_EXIST: "The generated report doesn't exist",
    NETWORK_ISSUE: "Network issue detected, please check your internet connection",
    INVALID_CASE_ID: "An error occurred, please check you have a valid support number",
    USER_UNAUTHORIZED: "User unauthorized, please check your credentials",
    TERMS_NOT_AGREED: "You have not agreed to the latest version of the legal terms",
    // XenConstants.UpdateCodes
    UPDATE_INTERNAL_ERROR: "An internal error occurred",
    UPDATE_DOWNLOAD_FAILED: "Download failed",
    UPDATE_DOWNLOAD_CANCELLED: "Download cancelled",
    UPDATE_MISSING_METADATA: "Metadata was missing",
    UPDATE_MALFORMED_METADATA: "Metadata was malformed",
    UPDATE_UPDATE_NOT_APPLICABLE: "Update not applicable",
    UPDATE_ALREADY_RUNNING: "Update already running",
    UPDATE_VM_RUNNING: "Update cannot be applied while guest VMs are running.\nPlease shut down any running VMs and try again.",
    UPDATE_CORRUPT_FILE: "Corrupt file encountered",
    UPDATE_UP_TO_DATE: "Already up to date",
    UPDATE_FILE_NOT_FOUND: "Update repository not found, please check your URL",
    UPDATE_CANNOT_RESOLVE_HOST: "Cannot resolve host, please check your URL",
    UPDATE_CANNOT_CONNECT_HOST: "Unable to connect to host, please check your URL",
    UPDATE_SIGNATURE_FAILED: "Update signature has failed verification",
    UPDATE_POLICY_DISABLED: "Updates are disabled by policy"
})
