({
    // Layout
    CREATE_FROM_MEDIA: "Create local VM",
    CREATE_VM_WIZARD_NAME_HEADER: "Name & Template",
    TEMPLATE_LABEL: "Template:",
    VM_NAME_LABEL: "VM Name:",
    DESCRIPTION_LABEL: "Description:",
    VM_MODE_HEADER: "VM Mode",
    VM_MODE_NATIVE_LABEL: "Run this VM only and hide OpenXT",
    VM_MODE_NATIVE_INFO: "Recommended if you only plan to install one VM",
    VM_MODE_NOT_NATIVE_LABEL: "Run multiple VMs and show OpenXT",
    VM_MODE_NOT_NATIVE_INFO: "Recommended if you plan to install more than one VM",
    TELL_ME_MORE: "Tell me more",
    VM_MODE_NATIVE_TOOLTIP: "This mode makes a single VM run like a native OS. Settings are simplified because networking, power settings, and USB devices are controlled from within the OS.<br/><br/>With this mode, the only way to return to OpenXT is by using the keyboard shortcut CTRL + 0.",
    VM_MODE_NOT_NATIVE_TOOLTIP: "This mode lets you run multiple VMs at the same time. Settings, such as networking and assigning USB devices and 3D graphics, are accessed from OpenXT.<br/><br/>With this mode you can use the switcher bar to switch between VMs or go back to OpenXT.",
    XENCLIENT_ACCESS_TIP: "To access OpenXT from the VM, press CTRL + 0",
    CREATE_VM_WIZARD_ICON_HEADER: "Icon",
    CREATE_VM_WIZARD_MEMORY_HEADER: "Memory & CPUs",
    CREATE_VM_WIZARD_MEMORY_ALT_HEADER: "Memory",
    MEMORY_LABEL: "Memory:",
    MB_INDICATOR_TEXT: "(MB)",
    GB_INDICATOR_TEXT: "(GB)",
    TOTAL_MEM_MASK: "Total Memory: {0:n}",
    FREE_MEM_MASK: "Free Memory: {0:n}",
    VCPUS_LABEL: "vCPUs:",
    CREATE_VM_WIZARD_STORAGE_HEADER: "Storage & Networking",
    STORAGE_LABEL: "Virtual Disk Size:",
    ENCRYPT_LABEL: "Disk Encryption:",
    WIRED_LABEL: "Wired Network:",
    WIRELESS_LABEL: "Wireless Network:",
    TYPE_BRIDGED: "Bridged",
    TYPE_SHARED: "Shared",
    TYPE_INTERNAL: "Internal",
    TYPE_WIFI: "Shared Wireless",
    TYPE_MODEM: "Shared 3G",
    TYPE_VPN: "VPN",
    TYPE_BRIDGED_MANY: "Bridged on {0} ({1})",
    TYPE_SHARED_MANY: "Shared on {0} ({1})",
    TYPE_INTERNAL_MANY: "Internal on {0} ({1})",
    TYPE_WIFI_MANY: "Shared Wireless on {0} ({1})",
    TYPE_MODEM_MANY: "Shared 3G on {0} ({1})",
    TYPE_VPN_MANY: "VPN on {0} ({1})",
    NO_WIRELESS_NETWORK: "No wireless networks present",
    NO_WIRED_NETWORK: "No wired networks present",
    WIRED_NETWORK_INFORMATION: "A <strong>bridged</strong> network connects a VM directly to the external network.<br/>A <strong>shared</strong> network reuses a single network IP address for all VMs.<br/>The <strong>internal</strong> network is not connected to any external network.",
    CREATE_VM_WIZARD_FINISH_HEADER: "Finish",
    CREATE_VM_WIZARD_FINISH: "You are ready to start the VM and install an OS, select your installation source:",
    ISO_LABEL: "ISO File",
    CD_ROM_LABEL: "CD-ROM",
    CD_ROM_WARNING: "All CD-ROMs are assigned to other VMs",
    NETWORK_LABEL: "Network",
    AUTOSTART_OFF_LABEL: "Create VM & Install OS later",
    ISO_BOOT_WARNING: "Ensure all physical CD-ROMs are ejected before you continue",
    ISO_BOOT_INFO: "After OS installation, change the virtual CD in the VM details to <strong>xc-tools.iso</strong> to install OpenXT Tools",
    CD_BOOT_WARNING: "Ensure the installation media is inserted into the CD-ROM drive before you continue",
    CD_BOOT_INFO: "After OS installation, double-click <strong>OpenXT Tools Virtual CD</strong> to install OpenXT Tools",
    NETWORK_BOOT_WARNING: "Network boot will change the VM boot order. After OS installation, change it in the VM details",
    NETWORK_BOOT_INFO: "After OS installation, double-click <strong>OpenXT Tools Virtual CD</strong> to install OpenXT Tools",
    OFF_BOOT_INFO: "After OS installation, double-click <strong>OpenXT Tools Virtual CD</strong> to install OpenXT Tools",
    CREATING_VM: "Please wait while the VM is created.",
    ENCRYPT_MESSAGE: "Encrypting disk. Please increase randomness by moving the mouse.",
    ENCRYPTION_256: "AES-128",
    ENCRYPTION_512: "AES-256",
    ENCRYPTION_NONE: "None",
    ENABLED: "Enabled",
    DISABLED: "Disabled",
    NETWORK_NONE: "None",
    // Errors
    NAME_VALERROR: "Name is required. It cannot exceed 60 characters and can contain letters, digits, spaces and some punctuation (including underscore, dash, brackets, period, apostrophe, and comma).",
    DESCRIPTION_VALERROR: "Description should not exceed 200 characters and can contain letters, digits, whitespace and some punctuation (including underscore, dash, brackets, period, apostrophe, and comma).",
    VM_ERRORS: "The virtual machine has been created, but there were errors. Please check your settings for the new virtual machine."
})
