({
    // Layout
    CREATE_STATUS_REPORT: "Create Status Report",
    REPORT_WELCOME: "Welcome",
    REPORT_DESCRIPTION: "This wizard will collate diagnostic information from this system.<br/><ul><li>It will collate the Xen dmesg output, details of the hardware configuration of your machine, information about the build of Xen that you are using, plus various logs.<br/><br/></li><li>The collated information will be downloadable as a .tar.bz2 for archiving or sending to a Technical Support Representative.</li></ul>",
    REPORT_VM_DESCRIPTION: "This tool can optionally acquire diagnostic information from VMs, including logs and screenshots of the currently running VMs. These can prove to be extremely helpful with diagnosis of technical issues.",
    REPORT_INCLUDE_VMSCREENS: "Include screenshots of the VMs in this report",
    REPORT_INCLUDE_VMS: "Include other diagnostic information from the VMs in this report",
    REPORT_INFO: "The logs may contain private information and if this is of concern, explicitly exclude the VM logs from the archive. Opting to exclude VM information from the report may prevent diagnosis of your issue.",
    REPORT_SUMMARY: "Description",
    REPORT_DETAILS: "Please enter a summary of the issue and a detailed description",
    SUMMARY_LABEL: "Summary:",
    SUMMARY_VALERROR: "Summary is required. It cannot exceed 60 characters and can contain letters, digits, spaces and some punctuation (including underscore, dash, brackets, period, apostrophe, and comma).",
    DESCRIPTION_LABEL: "Description:",
    REPORT_SUMMARY_INFO: "Please try to use no more than eight words for the summary.",
    REPORT_STEPS: "Reproduction",
    REPORT_REPRO: "Please describe, if possible, specific steps to reproduce the issue.",
    REPORT_REPRO_LABEL: "Steps to Reproduce:",
    REPORT_TICKET: "If you have a technical support case number or ticket number, please enter it here.",
    REPORT_TICKET_LABEL: "Support Number:",
    REPORT_GENERATION: "Generation",
    REPORT_SERVER_DESCRIPTION: "Once generated, this wizard will make the report available for download by running a temporary dedicated web server on this machine. You can then enter the URL that it announces into your web browser.<br/><br/>If you don't intend to download it straight away, uncheck the following box.",
    REPORT_SERVER: "Enable downloading of report once generation has completed",
    REPORT_FINISHED: "The wizard has collected enough information to generate a status report.<br/><br/>Review your input and click Next to generate the report.",
    GENERATING_REPORT: "Generating report, please wait...",
    STATUS_SERVER_INFO: "You should only make the reports available for download if your computer network is secure and your administrator allows you to do so.",
    REPORT_UPLOAD: "Upload",
    REPORT_FINISH: "Finish",
    REPORT_CREATED: "The following status report was created successfully:<br/><br/><strong>{0}</strong>",
    REPORT_FINISH_SERVER: "To download a report, use the Status Report section in Information.",
    STOP_SERVER: "Closing this wizard will stop reports from being available for download.",
    SERVE_REPORT: "Reports are available for download onto another machine at:\n\n{0}\n\nThey are available for download to VMs on this machine at:\n\n{1}",
    AGREE_TERMS: "Agree to terms",
    UPLOADING_REPORT: "Uploading report, please wait..."
})