({
    // Layout
    DEFERRED_INSTALL_TITLE: "Welcome to OpenXT",
    EULA_HEADER: "EULA",
    KEYBOARD_HEADER: "Keyboard Layout",
    KEYBOARD_INSTR: "Please select a keyboard layout.",
    LANGUAGE_HEADER: "Language",
    LANGUAGE_INSTR: "Please select a language.",
    ROOT_PASSWORD_HEADER: "System Password",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "Switzerland",
    KEYBOARD_LAYOUT_CN: "China",
    KEYBOARD_LAYOUT_FR: "France",
    KEYBOARD_LAYOUT_DE: "Germany",
    KEYBOARD_LAYOUT_IT: "Italy",
    KEYBOARD_LAYOUT_JP: "Japan",
    KEYBOARD_LAYOUT_ES: "Spain",
    KEYBOARD_LAYOUT_GB: "United Kingdom",
    KEYBOARD_LAYOUT_US: "United States",
    KEYBOARD_LAYOUT_RU: "Russia",
    KEYBOARD_LAYOUT_CA: "Canada",
    KEYBOARD_LAYOUT_BR: "Brazil",
    KEYBOARD_LAYOUT_NL: "Netherlands",
    KEYBOARD_LAYOUT_NO: "Norway",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Korea",
    KEYBOARD_LAYOUT_BE: "Belgium",
    KEYBOARD_LAYOUT_DK: "Denmark",
    KEYBOARD_LAYOUT_IN: "India",
    KEYBOARD_LAYOUT_SE: "Sweden",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English",
    // Errors
    EULA_ERROR: "Please accept this EULA to use OpenXT. If you cancel, OpenXT will shut down.",
    KEYBOARD_ERROR: "Please select a keyboard layout.",
    SET_SYSTEM_PASSWORD: "OpenXT requires a system password."
})
