({
    // Controls (Normal)
    START: "Start",
    BACKGROUND_START: "Quiet Start",
    WAKE: "Wake",
    SWITCH: "Switch",
    SHUT_DOWN: "Shut Down",
    REBOOT: "Restart",
    HIBERNATE: "Hibernate",
    SLEEP: "Sleep",
    FORCE_SHUT_DOWN: "Force Off",
    LOGIN: "Login",
    // Managed VM
    VM_DOWNLOADING: "Downloading",
    // Controls (ICA)
    ICASTART: "Start",
    ICABACKGROUND_START: "Quiet Start",
    ICASWITCH: "Switch",
    ICASHUT_DOWN: "Stop",
    ICAFORCE_SHUT_DOWN: "Force Off",
    ICALOGIN: "Login",
    // Layout
    ADD_DEVICE: "Add USB Device",
    DELETE: "Delete",
    DETAILS: "Details",
    PAUSE: "Pause",
    RESUME: "Resume",
    RETRY: "Retry",
    CANCEL: "Cancel",
    GENERAL: "General",
    DEVICES: "USB Devices",
    PCI_DEVICES: "PCI Pass Through",
    PASSTHRU_DEVICE: "Passed Through Devices",
    PRIVATE_DEVICE: "Private Devices",
    PLATFORM_DEVICE: "Shared Devices",
    NO_DEVICES: "No devices connected",
    NO_PCI_DEVICES: "No devices passed through",
    OPTIONS: "Options",
    ACTIONS: "Actions",
    ALWAYS_USE: "Always Use With This VM",
    DISCONNECT: "Remove",
    ADD_PCI: "Add PCI Device",
    HARDWARE: "Hardware",
    ICON: "Icon",
    CUSTOM: "Custom",
    ADVANCED: "Advanced",
    NAME: "Name:",
    CONNECTION_NAME: "Connection Name:",
    URL: "XenDesktop server URL:",
    VCPUS: "vCPUs:",
    MEMORY: "Memory (MB):",
    AUTOBOOT: "Autoboot:",
    AUTOBOOT_TOOLTIP: "Start this VM when the host starts.",
    POWER_BEHAVIOUR: "Power Control:",
    POWER_BEHAVIOUR_TOOLTIP: "When the VM shuts down, hibernates or sleeps, the host device will do the same.",
    POWER_BEHAVIOUR_ENABLED: "Power control affects VM and host",
    POWER_BEHAVIOUR_DISABLED: "Power control affects VM only",
    SWITCHER_KEY: "Switcher Key:",
    VIRTUAL_CD: "Virtual CD:",
    TOOLS_CD: "OpenXT Guest Tools",
    GUEST_TOOLS: "Guest Tools Version:",
    INSTALLED_TOOLS_MASK: "Installed: {0}",
    THREED_GFX: "3D Graphics (experimental):",
    TYPE: "Type:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32bit",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32bit",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32bit",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64bit",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32bit (experimental)",
    TYPE_UNKNOWN: "Unknown",
    DESCRIPTION: "Description:",
    WIRELESS_NETWORK: "Wireless Network:",
    WIRED_NETWORK: "Wired Network:",
    WIRED_NIC: "Wired MAC Address:",
    NETWORKS: "Networks",
    NETWORK_TH: "Network",
    MAC_TH: "MAC Address",
    TYPE_TH: "Type",
    BACKEND_TH: "Backend",
    DELETE_NETWORK: "Remove",
    ADD_NETWORK: "Add Network",
    NO_NETWORKS: "No networks used",
    NIC_DELETE_CONFIRM: "Are you sure you want to remove this network? This action cannot be undone.",
    DISK_SPACE: "Disk Space:",
    RESTRICT_RESOLUTION: "Restrict Display Resolutions:",
    ALLOW_OEM: "Allow OEM Windows Install:",
    EXPOSE_HARDWARE_INFO: "Expose Physical Hardware Information:",
    DISPLAY_VM: "Show VM in Switcher Bar:",
    SHOW_SWITCHER: "Show Switcher Bar:",
    WIRELESS_CONTROL: "Control Wireless in VM:",
    WIRELESS_CONTROL_TOOLTIP: "Wireless network connections can be controlled from within this VM.",
    NATIVE_DISABLED_TOOLTIP: "This feature is chosen automatically when running in Single VM Mode.",
    POLICY_TITLE: "Isolation Policies",
    HARDWARE_TITLE: "Hardware Compatibility",
    VIRTUAL_TITLE: "Virtual Compatibility",
    AMT_PASSTHROUGH: "Intel AMT Passthrough:",
    OEM_ACPI_PASSTHROUGH: "Expose Physical OEM Hardware:",
    NETWORKING_WIRED_POLICY: "Wired Network Access:",
    NETWORKING_WIRELESS_POLICY: "Wireless Network Access:",
    CD_ACCESS_POLICY: "CD Reading:",
    CD_RECORDING_POLICY: "CD Writing:",
    AUDIO_ACCESS_POLICY: "Audio Playback:",
    AUDIO_RECORDING_POLICY: "Audio Recording:",
    USB_POLICY: "USB Access:",
    STUB_DOMAIN: "Stub Domain:",
    VIRIDIAN: "Emulate Microsoft Hyper-V:",
    HVM: "Hardware Virtual Machine",
    KERNEL: "Kernel Path:",
    KERNEL_EXTRACT: "Kernel Extraction Path:",
    COMMAND_LINE: "Command Line:",
    INIT_RD: "Initial Ramdisk:",
    BOOT_ORDER: "Boot Order:",
    EDIT: "Edit",
    SAVE: "Save",
    CLOSE: "Close",
    MANAGED_ENABLED: "Managed VM",
    THREED_GRAPHICS_ENABLED: "3D Graphics Enabled",
    NATIVE_MODE_ENABLED: "Single VM Mode",
    ENABLED: "Enabled",
    DISABLED: "Disabled",
    NONE: "None",
    INSTALLED_NONE: "No tools installed",
    ATTACHED: "Attached",
    TYPE_BRIDGED: "Bridged",
    TYPE_SHARED: "Shared",
    TYPE_INTERNAL: "Internal",
    TYPE_WIFI: "Shared Wireless",
    TYPE_MODEM: "Shared 3G",
    TYPE_VPN: "VPN",
    NO_WIRELESS_NETWORK: "No wireless networks present",
    NO_WIRED_NETWORK: "No wired networks present",
    WIRED_POLICY_DISABLED: "Wired networking is <strong>disabled</strong> by policy",
    WIRELESS_POLICY_DISABLED: "Wireless networking is <strong>disabled</strong> by policy",
    MEMORY_MASK: "{0:n}",
    SYSTEM_MEMORY_MASK: "Total: {0:n}, Free: {1:n}",
    DISK_SPACE_MASK: "Private: {0}, Shared: {1}",
    NETWORK_INFORMATION: "A <strong>bridged</strong> network connects a VM directly to the external network.<br/>A <strong>shared</strong> network reuses a single network IP address for all VMs.<br/>The <strong>internal</strong> network is not connected to any external network.",
    TRANSFER: "Transfer",
    TRANSFER_STATE: "State:",
    TRANSFER_PROGRESS: "Progress:",
    TRANSFER_SPEED_MASK: "{0:f} MB/s",
    SWITCHER_KEY_MASK: "CTRL + {0}",
    SWITCHER_DROPDWON_MASK: " ({0})",
    THIS_VM: "this VM",
    CD_DRIVE: "CD Drive",
    HARD_DRIVE: "Hard Drive",
    NETWORK: "Network",
    NETWORK_UNKNOWN: "Unknown",
    NETWORK_INACTIVE: "Inactive",
    BOOT_TITLE: "Add a boot option...",
    HDX_TOOLTIP: "To enable this feature, the virtual machine must be off and have OpenXT tools and appropriate video drivers installed.",
    DISK_SPACE_TOOLTIP: "Private: Amount of disk space used only by this virtual machine.<br/>Shared: Amount of disk space shared with other virtual machines on the system.",
    AMT_PT_TOOLTIP: "Enabling the Intel Active Management Technology (AMT) Management Engine (ME) provides hardware-based network management that allows out-of-band access to OpenXT devices for administration purposes. Only one VM can have this enabled.",
    ACPI_PT_TOOLTIP: "Expose the host ACPI SLIC table to the VM to unlock OEM editions of Windows.",
    SMBIOS_PT_TOOLTIP: "Expose the SMBIOS record types describing host hardware to the VM instead of those supplied by OpenXT.",
    OEM_ACPI_PT_TOOLTIP: "Expose the OEM hardware directly to the VM. Only one VM can have this enabled.",
    POWER: "Power",
    COMMUNICATION: "Seamless Application Support:",
    COMMUNICATION_TOOLTIP: "Controls virtual machine firewall settings so that seamless applications will work.",
    PCI_WARNING: "This section is for advanced features and should only be modified if you understand their impact on the system. A host restart may be required before changes will take affect.",
    ADVANCED_WARNING: "This section is for advanced features and should only be modified if you understand their impact on the system. Changes will only take affect after a VM restart.",
    THREED_ENABLED: "3D Graphics (HDX) has been enabled for this VM. This is an experimental feature which may cause graphics issues, flickering and other instabilities.",
    INTEL_AMT: "Intel AMT ME Pass-through will not take effect until OpenXT is restarted.",
    MEMORY_CHANGE: "The memory change will take place when the virtual machine is next booted.",
    VCPU_CHANGE: "The vCPUs change will take place when the virtual machine is next booted.",
    VM_UPDATE_CHECK: "Check for VM Update",
    DELETE_VM_HEADER: "Delete Virtual Machine",
    DELETE_VM: "Are you sure you wish to delete the virtual machine named '{0}'?",
    ACCEPT_DELETE: "Yes, delete it",
    XEN_MGR_DELETE: "Delete VM",
    USB_UNASSIGN: "This USB device is currently in use by this VM. Removing it will force remove it from this VM and could result in data loss. You can cleanly remove this device by ejecting it from within your VM operating system.",
    PCI_UNASSIGN: "Are you sure you wish to stop passing through this PCI device?",
    ADD_DEVICE_STATUS: "You can only connect a device when the virtual machine is on and has OpenXT tools installed",
    DELETE_VM_STATUS: "You can only delete a virtual machine when its state is off or hibernated",
    FORCE_UPDATE: "Error force updating the VM",
    USB_DISABLED: "Unable to add a device as device management has been disabled for this VM",
    LOADING: "Loading...",
    DISKS: "Disks",
    DISK_TH: "Disk",
    DISK_SIZE_TH: "Virtual Size",
    DISK_SIZE_ACTUAL_TH: "Utilized Size",
    ENCRYPTION_TH: "Encryption",
    PERSISTENT_TH: "Persistence",
    PERSISTENT_TOOLTIP: "This setting indicates if changes to the data on the disk remain across VM boots.",
    NO_DISKS: "No virtual disks",
    DISK_DELETE_CONFIRM: "Are you sure you want to delete this disk? This action cannot be undone.",
    DELETE_DISK: "Delete",
    ADD_DISK: "Create Disk",
    TAKE_SNAPSHOT: "Snapshot",
    RESTORE_SNAPSHOT: "Restore",
    CONFIRM_SNAPSHOT: "Snapshot taken successfully",
    TOTAL: "Total",
    DISK_RESET_ENABLED: "All disks attached to this VM will reset on VM boot",
    ENCRYPTION_ENABLED: "All disks attached to this VM are encrypted",
    CDLOCK_ENABLED: "This VM has a CD lock",
    USB_ENABLED: "This VM has a USB device passed through",
    START_VM_NO_DISKS: "The virtual machine named '{0}' does not have any virtual disks. Are you sure you wish to start this machine?",
    START_VM_NO_DISKS_HEADER: "Start Virtual Machine",
    ACCEPT_START: "Yes, start it",
    // Errors
    NAME_VALERROR: "Name is required. It cannot exceed 60 characters and can contain letters, digits, spaces and some punctuation (including underscore, dash, brackets, period, apostrophe, and comma).",
    URL_VALERROR: "Please enter a valid host name.",
    DESCRIPTION_VALERROR: "Description should not exceed 200 characters and can contain letters, digits, whitespace and some punctuation (including underscore, dash, brackets, period, apostrophe, and comma)."
})
