({
    // Notifications
    SAFE_GRAPHICS_MODE: "Sicherer Grafikmodus",
    AUTH_FOR_AUTO_START: "Sie haben virtuelle Maschinen, für die Authentifizierung erforderlich ist, bevor sie automatisch gestartet werden können. Drücken Soe STRG + ALT + LÖSCHEN, um sichere Authentifizierung zu aktivieren.",
    AUTH_START: "Drücken Sie STRG+ALT+LÖSCHEN, um sichere Authentifizierung zu aktivieren.",
    CTRL_SWITCH: "So kehren Sie zu diesem Bildschirm zurück:<div class='ctrlText'><span class='ctrlButton'>STRG</span> + <span class='ctrlButton'>0</span></div>",
    SEVERAL_VMS: "Das Ausführen mehrerer virtueller Maschinen, ohne dass OpenXT-Tools installiert ist, kann die Systemleistung verschlechtern. OpenXT-Tools sollten möglichst installiert sein.",
    // Alerts
    LOW_SPACE_WARNING: "Wenig Speicherplatz auf Datenträger. Zurzeit sind {0}% verfügbar.",
    LOW_SPACE_TOOLTIP: "<strong>Wenig Speicherplatz auf Datenträger</strong><br/><br/>Zurzeit sind {0}% verfügbar.",
    // Errors
    AUTH_SSL_CACERT_ERROR: "Der Client vertraut dem Sicherheitszertifikat Ihres Synchronizer-Servers nicht mehr. Wenn Sie den Synchronizer weiter verwenden möchten, müssen Sie sich erneut bei ihm registrieren.\n\nMöchten Sie dies jetzt tun?",
    AJAX_FAILED: "AJAX-Anfrage fehlgeschlagen\r\nID: {0}; Methode: {1}",
    UNEXPECTED_RESULT: "Unerwartetes Ergebnis von signalRegister für Oberfläche ",
    SIGNAL_ERROR: "Fehler beim Signalempfang; Warteschlange: {0}",
    UNEXPECTED_RCV_RESULT: "Unerwartetes Ergebnis von receiveSignals",
    SERVICE_NOT_RUNNING: "Der Dienst '{0}' wird nicht ausgeführt.",
    XT_BED_NOT_RUNNING_ACTION: "Diese Aktion kann nicht abgeschlossen werden, weil der Synchronizer-Daemon nicht ausgeführt wird.",
    XT_VERSION_MISMATCH_INFO: "Verbindung zum Synchronizer nicht möglich. '{0}'-Server ist nicht mit einem '{1}'-Client kompatibel.",
    // XenConstants.ToolstackCodes
    NOT_ENOUGH_FREE_MEMORY: "Für Ihre Anfrage war nicht genügend Speicher vorhanden.",
    VM_BAD_STATE: "Die virtuelle Maschine ist in einem unerwarteten Zustand.",
    VM_UNEXPECTED_SHUTDOWN_REASON: "Der Grund für das Herunterfahren war nicht der erwartete.",
    VM_NOT_SHUTDOWN: "Die virtuelle Maschine wurde nicht heruntergefahren.",
    VM_ALREADY_CREATED: "Die virtuelle Maschine wurde bereits erstellt.",
    VT_MISSING: "Hardwarevirtualisierung muss aktiviert sein, bevor eine virtuelle Maschine verwendet werden kann. Überprüfen Sie die BIOS-Einstellungen.",
    VM_TAP_MOUNT_FAILURE: "Die virtuelle Maschine konnte nicht gestartet werden, weil sie nicht im Zustand 'Bereit' ist.<br/>Dies kann daran liegen, dass sie gerade von einem anderen Prozess aktualisiert wird. Versuchen Sie es in Kürze erneut.",
    HDX_AUTOSTART_MULTIPLE: "HDX und Autostart können nicht auf mehreren VMs gleichzeitig aktiviert werden.",
    VM_HIBERNATE_FAILED: "Die virtuelle Maschine wurde nicht in den Ruhezustand versetzt.",
    VM_EDIT_DISABLED: "Das Bearbeiten von Eigenschaften wird durch eine aktive Richtlinie dieser VM deaktiviert.",
    NO_SUCH_DEVICE: "Ein solches Gerät existiert nicht",
    VM_CANNOT_DELETE_RUNNING: "Die VM kann nicht gelöscht werden, während sie ausgeführt wird.",
    VM_COUNT_HIGH: "Zu viele virtuelle Maschinen",
    DISK_NOT_EXIST: "Eine solche Festplatte existiert nicht",
    INCORRECT_DISK_TYPE: "Falscher Festplattentyp",
    INCORRECT_DEVICE_TYPE: "Falscher Gerätetyp",
    HDX_CHANGE_WHILE_RUNNING: "HDX kann nicht ein- oder ausgeschaltet werden, während die VM ausgeführt wird.",
    HDX_ENABLE_NO_TOOLS: "HDX kann erst nach der Installation der OpenXT-Tools aktiviert werden.",
    HDX_NO_VTD: "VM mit HDX kann nicht gestartet werden, weil VT-d nicht aktiviert ist.",
    DISK_DEVICE_EXISTS: "Angegebene Festplatte konnte nicht hinzugefügt werden. Gerät existiert bereits.",
    TOOLS_REQUIRED: "Für diesen Vorgang müssen OpenXT-Tools auf der VM installiert sein.",
    PROPERTY_READ_ONLY: "Eigenschaft ist schreibgeschützt.",
    PROPERTY_WRITE_ONLY: "Eigenschaft ist lesegeschützt.",
    NO_DIAGNOSTICS: "Zurzeit werden keine Diagnoseinformationen gesammelt.",
    INCORRECT_DISK_HASH: "Festplatten-Hash stimmt nicht überein.",
    TOO_MANY_HDX: "VM kann nicht gestartet werden. Es werden bereits zu viele VMs mit HDX ausgeführt.",
    VM_PASSTHRU_RUNNING: "VM kann nicht gestartet werden. Eine andere VM mit AMT-Passthrough wird bereits ausgeführt.",
    POLICY_SUPPRESSED_ACTION: "Diese Aktion wird durch die aktiven Richtlinieneinstellungen unterdrückt.",
    VM_HIBERNATE_CHANGE: "Diese VM-Eigenschaft kann nicht geändert werden, während die VM im Ruhezustand ist.",
    NIC_NOT_FOUND: "Eine solche NIC existiert nicht",
    IO_ERROR: "E/A-Fehler",
    VM_RESUME_FAILED: "VM konnte aus dem Standbymodus nicht wiederhergestellt werden.",
    OPERATION_SUPPRESSED_ACTION: "Die angeforderte Aktion kann nicht ausgeführt werden, weil ein anderer Vorgang im Hintergrund ausgeführt wird.",
    VM_NO_RPC_AGENT: "Diese VM ist nicht für die Verwendung des rpc-Agents konfiguriert.",
    VM_SLEEP_TIMEOUT: "Timeout wartet darauf, dass die VM in den Standbymodus übergeht.",
    VM_HIBERNATE_TIMEOUT: "Timeout wartet darauf, dass die VM in den Ruhezustand übergeht.",
    VM_SHUTDOWN_TIMEOUT: "Timeout wartet darauf, dass die VM heruntergefahren wird.",
    DEVICE_ATTACHED_ELSEWHERE: "Das Gerät wird zurzeit an eine andere VM weitergegeben.",
    ADAPTER_NOT_SECONDARY: "Die Grafikkarte kann nicht als sekundärer Adapter weitergegeben werden.",
    NETWORK_NOT_RUNNNING: "Die Backend-Domäne des Netzwerks wird nicht ausgeführt.",
    OEM_ACPI_RUNNING: "VM kann nicht gestartet werden. Es wird bereits eine andere VM mit oem-acpi-Features ausgeführt.",
    UNKNOWN_GPU: "Unbekannter Grafikprozessor",
    VM_TXT_SLEEP_DISABLED: "Standbymodus auf dem Host ist deaktiviert, wenn der Start mit TXT gemessen wird",
    UNSUPPORTED_LANGUAGE: "Nicht unterstützte Sprache",
    RULE_PARSE_ERROR: "Regelparsingfehler",
    // XenConstants.UpdateCodes
    UPDATE_INTERNAL_ERROR: "Ein interner Fehler ist aufgetreten.",
    UPDATE_DOWNLOAD_FAILED: "Download fehlgeschlagen",
    UPDATE_DOWNLOAD_CANCELLED: "Download abgebrochen",
    UPDATE_MISSING_METADATA: "Metadaten fehlten",
    UPDATE_MALFORMED_METADATA: "Metadaten waren fehlerhaft",
    UPDATE_UPDATE_NOT_APPLICABLE: "Update nicht zutreffend",
    UPDATE_ALREADY_RUNNING: "Update wird bereits ausgeführt",
    UPDATE_VM_RUNNING: "Update kann nicht angewendet werden, während Gast-VMs ausgeführt werden.\nFahren Sie alle VMs, die gerade ausgeführt werden, herunter und versuchen Sie es erneut.",
    UPDATE_CORRUPT_FILE: "Beschädigte Datei gefunden",
    UPDATE_UP_TO_DATE: "Bereits aktualisiert",
    UPDATE_FILE_NOT_FOUND: "Update-Repository wurde nicht gefunden. Überprüfen Sie die URL.",
    UPDATE_CANNOT_RESOLVE_HOST: "Host kann nicht aufgelöst werden. Überprüfen Sie die URL.",
    UPDATE_CANNOT_CONNECT_HOST: "Verbindung zum Host kann nicht hergestellt werden. Überprüfen Sie die URL.",
    UPDATE_SIGNATURE_FAILED: "Updatesignatur hat Überprüfung nicht bestanden.",
    UPDATE_POLICY_DISABLED: "Updates sind durch eine Richtlinie deaktiviert.",
    // XenClient.Resource.RegisterStatus
    NETWORK_DISCONNECTED_2: "Keine Verbindung zum Netzwerk",
    SERVER_UNREACHABLE: "Verbindung zum Server kann nicht hergestellt werden. Überprüfen Sie die URL.",
    CERT_CA_MISSING: "OpenXT konnte dieses Gerät nicht registrieren. Überprüfen Sie die Synchronizer-Konfiguration und ob OpenXT korrekt installiert ist: ",
    CERT_VERIFY_FAILED: "Server kann nicht authentifiziert werden:",
    CERT_GENERIC: "Allgemeiner Fehler",
    CERT_TRUST_ROOT_CERT_FAILED: "Stammzertifikat wird nicht vertraut.",
    CERT_AUTH_CODE_MISMATCH: "Der Authentifizierungscode stimmt nicht mit dem vom Zertifikat generierten Code überein.",
    CERT_GET_CHAIN_FAILED: "Zertifikatskette konnte nicht vom Server abgerufen werden.",
    HOSTNAME_INVALID: "Ungültiger Hostname bei Registrierung angegeben",
    CERT_NO_CN: "Kein allgemeiner Name im Serverzertifikat",
    CERT_HOSTNAME_CN_MISMATCH: "Allgemeiner Name im Zertifikat stimmt nicht mit dem Hostnamen für die Registrierung überein. Der allgemeine Name im Zertifikat ist: {0}"
})
