({
    HEADER: "Information",
    SOFTWARE_TITLE: "Software",
    SERVICES_TITLE: "Services",
    HARDWARE_TITLE: "Hardware",
    NETWORK_TITLE: "Networking",
    SERVICES_HEADER: "Installed Services",
    VENDOR: "Vendor",
    NAME: "Name",
    VERSION: "Version",
    STATUS_REPORT_HEADER: "Status Report",
    VENDOR_LABEL: "Vendor:",
    MODEL_LABEL: "Model:",
    BIOS_REV_LABEL: "BIOS Revision:",
    TOTAL_MEM_LABEL: "Total Physical Memory:",
    MEMORY_MASK: "{0:n} MB",
    FREE_MEM_LABEL: "Free Physical Memory:",
    FREE_STORAGE_LABEL: "Free Disk Space:",
    TOTAL_STORAGE_LABEL: "Total Disk Space:",
    DISK_SPACE_MASK: "{0:n} MB",
    CPU_MODEL_LABEL: "Physical CPU Model:",
    GPU_MODEL_LABEL: "Physical GPU Model:",
    ETH0_MAC_ADDRESS_LABEL: "Wired MAC Address:",
    ETH0_MODEL_LABEL: "Wired Model:",
    HOST_AMT_PT_LABEL: "MAC Address Pass-through:",
    ON_TEXT: "Enabled",
    OFF_TEXT: "Disabled",
    WIRELESS_MAC_ADDRESS_LABEL: "Wireless MAC Address:",
    WIRELESS_MODEL_LABEL: "Wireless Model:",
    XENCLIENT_VERSION_LABEL: "OpenXT Version:",
    XENCLIENT_VERSION_MASK: "{0}",
    XENCLIENT_BRANCH_MASK: "{0} branch",
    XENCLIENT_BUILD_LABEL: "OpenXT Build:",
    XENCLIENT_BUILD_MASK: "{0} ({1:d MMMM y})",
    TOOLS_VERSION_LABEL: "Tools CD Version:",
    STATUS_REPORT: "Creating a status report will collect diagnostic information from this device and package it into a single file.<br/><br/>This can be done at any time by pressing CTRL+ALT+R",
    CREATE_STATUS_REPORT: "Create Status Report",
    STATUS_SERVER_HEADER: "Report Download",
    STATUS_SERVER: "Please refer to the Troubleshooting chapter of the OpenXT user guide for help downloading your status reports.",
    BEGIN_STATUS_SERVER: "Make Reports Downloadable",
    STATUS_SERVER_INFO: "You should only make the reports available for download if your computer network is secure and your administrator allows you to do so.",
    CLOSE_ACTION: "Close",
    SAVE_ACTION: "Save",
    // Other
    SERVE_REPORT: "Reports are available for download onto another machine at:\n\n{0}\n\nThey are available for download to VMs on this machine at:\n\n{1}",
    STOP_STATUS_SERVER: "Stop Report Availability"
})
