({
    // Layout
    CREATE_FROM_MEDIA: "Von Installations-CD erstellen",
    CREATE_VM_WIZARD_NAME_HEADER: "Name & Typ",
    TYPE_LABEL: "Typ:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 Bit",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 Bit",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 Bit",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 Bit",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 Bit (experimentell)",
    TYPE_UNKNOWN: "Unbekannt",
    VM_NAME_LABEL: "VM-Name:",
    DESCRIPTION_LABEL: "Beschreibung:",
    CREATE_VM_WIZARD_ICON_HEADER: "Symbol",
    CREATE_VM_WIZARD_MEMORY_HEADER: "Speicher & CPUs",
    CREATE_VM_WIZARD_MEMORY_ALT_HEADER: "Speicher",
    MEMORY_LABEL: "Speicher:",
    MB_INDICATOR_TEXT: "(MB)",
    GB_INDICATOR_TEXT: "(GB)",
    TOTAL_MEM_MASK: "Speicher insgesamt: {0:n}",
    FREE_MEM_MASK: "Verfügbarer Speicher: {0:n}",
    VCPUS_LABEL: "vCPUs:",
    CREATE_VM_WIZARD_STORAGE_HEADER: "Speicher & Netzwerke",
    STORAGE_LABEL: "Größe der virtuellen Festplatte:",
    WIRELESS_LABEL: "Drahtlosnetzwerk:",
    NETWORK_WIRELESS_OPTION: "NAT-Drahtlosnetzwerk",
    NETWORK_3G_OPTION: "NAT 3G (experimentell)",
    WIRED_LABEL: "Netzwerk:",
    NETWORK_BRIDGED_OPTION: "Direkt",
    NETWORK_SHARED_OPTION: "NAT",
    NETWORK_INTERNAL_OPTION: "Intern",
    NETWORK_BRIDGED_MASK: "Direkt auf {0}",
    NETWORK_SHARED_MASK: "NAT auf {0}",
    NETWORK_INTERNAL_MASK: "Intern auf {0}",
    WIRED_NETWORK_INFORMATION: "Ein <strong>direktes</strong> Netzwerk verbindet eine VM direkt mit dem externen Netzwerk.<br/>Ein <strong>NAT</strong>-Netzwerk verwendet dieselbe Netzwerk-IP-Adresse für alle VMs.<br/>Das <strong>interne</strong> Netzwerk ist mit keinem externen Netzwerk verbunden.",
    CREATE_VM_WIZARD_FINISH_HEADER: "Fertig stellen",
    CREATE_VM_WIZARD_FINISH_PARA1: "Sie sind jetzt bereit, vom Betriebssysteminstallationsdatenträger eine VM zu erstellen.",
    AUTOSTART_LABEL: "VM starten & Betriebssystem installieren",
    AUTOSTART_OFF_LABEL: "VM erstellen & Betriebssystem später installieren",
    CREATE_VM_WIZARD_FINISH_PARA2: "Doppelklicken Sie nach der Installation des Betriebssystems auf die <strong>virtuelle OpenXT-Tools-CD</strong>, um OpenXT-Tools zu installieren.",
    // Errors
    NAME_VALERROR: "Ein Name ist erforderlich. Er darf höchstens 60 Zeichen enthalten: Buchstaben, Zahlen, Leerzeichen und manche Satzzeichen (u. a. Unterstrich, Bindestrich, Klammer, Punkt, Apostroph und Komma).",
    DESCRIPTION_VALERROR: "Die Beschreibung darf höchstens 200 Zeichen enthalten: Buchstaben, Zahlen, Leerzeichen und manche Satzzeichen (u. a. Unterstrich, Bindestrich, Klammer, Punkt, Apostroph und Komma).",
    VM_ERRORS: "Die virtuelle Maschine wurde erstellt, aber es sind Fehler aufgetreten. Überprüfen Sie die Einstellungen für die neue virtuelle Maschine."
})
