({
    // Layout
    CREATE_STATUS_REPORT: "Statusbericht erstellen",
    REPORT_WELCOME: "Willkommen",
    REPORT_DESCRIPTION: "Dieser Assistent sammelt Diagnoseinformationen von diesem System.<br/><ul><li>Er stellt die dmesg-Ausgabe von Xen, Details der Hardwarekonfiguration Ihrer Maschine, Informationen über den Xen-Build, den Sie verwenden, sowie verschiedene Protokolle zusammen.<br/><br/></li><li>Diese Informationen können Sie als .tar.bz2-Datei herunterladen, archivieren oder an den technischen Support senden.</li></ul>",
    REPORT_VM_DESCRIPTION: "Dieses Tool kann Diagnoseinformationen von VMs sammeln, u. a. auch Protokolle und Screenshots der zurzeit ausgeführten VMs. Diese Informationen können bei der Diagnose technischer Probleme sehr hilfreich sein.",
    REPORT_INCLUDE_VMSCREENS: "Screenshots der VMs in diesem Bericht einschließen",
    REPORT_INCLUDE_VMS: "Weitere Diagnoseinformationen von dieser VM in diesem Bericht einschließen",
    REPORT_INFO: "Die Protokolle enthalten u. U. vertrauliche Informationen. Wenn dies für Sie problematisch ist, schließen Sie die VM-Protokolle explizit aus. Das Ausschließen von VM-Informationen aus dem Bericht kann die Diagnose des Problems verhindern.",
    REPORT_SUMMARY: "Beschreibung",
    REPORT_DETAILS: "Geben Sie eine Zusammenfassung des Problems und eine detaillierte Beschreibung ein.",
    SUMMARY_LABEL: "Zusammenfassung:",
    SUMMARY_VALERROR: "Eine Zusammenfassung ist erforderlich. Sie darf höchstens 60 Zeichen enthalten: Buchstaben, Zahlen, Leerzeichen und manche Satzzeichen (u. a. Unterstrich, Bindestrich, Klammer, Punkt, Apostroph und Komma).",
    DESCRIPTION_LABEL: "Beschreibung:",
    REPORT_SUMMARY_INFO: "Verwenden Sie möglichst nicht mehr als acht Wörter für die Zusammenfassung.",
    REPORT_STEPS: "Reproduktion",
    REPORT_REPRO: "Beschreiben Sie möglichst die genauen Schritte zur Reproduktion des Problems.",
    REPORT_REPRO_LABEL: "Reproduktionsschritte:",
    REPORT_TICKET: "Wenn Sie eine Fall- oder Referenznummer vom technischen Support haben, geben Sie sie hier ein.",
    REPORT_TICKET_LABEL: "Supportnummer:",
    REPORT_GENERATION: "Erstellung",
    REPORT_SERVER_DESCRIPTION: "Nach der Erstellung macht der Assistent den Bericht als Download verfügbar, indem auf dieser Maschine ein temporärer, dedizierter Webserver ausgeführt wird. Anschließend können Sie die angegebene URL in Ihren Webbrowser eingeben.<br/><br/>Wenn Sie ihn nicht sofort herunterladen möchten, deaktivieren Sie das folgende Kontrollkästchen.",
    REPORT_SERVER: "Download des Berichts nach dessen Erstellung ermöglichen",
    REPORT_FINISHED: "Der Assistent hat genügend Informationen für die Erstellung eines Statusberichts gesammelt.<br/><br/>Überprüfen Sie Ihre Eingaben und klicken Sie auf 'Weiter', um den Bericht zu erstellen.",
    GENERATING_REPORT: "Bericht wird erstellt. Bitte warten...",
    STATUS_SERVER_INFO: "Sie sollten Berichte nur zum Download verfügbar machen, wenn Ihr Computernetzwerk gesichert ist und Ihr Administrator dies zulässt.",
    REPORT_FINISH: "Fertig stellen",
    REPORT_CREATED: "Der folgende Statusbericht wurde erfolgreich erstellt:<br/><br/><strong>{0}</strong>",
    REPORT_FINISH_SERVER: "Um einen Bericht herunterzuladen, verwenden Sie den Statusbericht-Bereich in den Systemeinstellungen.",
    STOP_SERVER: "Wenn Sie diesen Assistenten schließen, können keine Berichte mehr heruntergeladen werden.",
    SERVE_REPORT: "Berichte können von hier auf einer anderen Maschine herunte\n\n{0}\n\nrgeladen werden:Sie können von hier auf VMs auf dieser Mas\n\n{1}chine heruntergeladen werden:"
})