({
    // Layout
    SYS_INFO_HEADER: "Systemeinstellungen",
    SYS_INFO_WALLPAPER_TITLE: "Hintergrund",
    SYS_INFO_POWER_TITLE: "Energiemodus",
    SYS_INFO_TOUCHPAD_TITLE: "Oberfläche",
    SYS_INFO_TRANSMITTER_TITLE: "Synchronizer",
    SYS_INFO_AUTH_TITLE: "Anmeldung",
    SYS_INFO_SOFTWARE_TITLE: "Software",
    SYS_INFO_HARDWARE_TITLE: "Hardware",
    SYS_INFO_NETWORK_TITLE: "Netzwerke",
    STATUS_REPORT_HEADER: "Statusbericht",
    WALLPAPER_HEADER: "Klicken Sie auf den gewünschten Hintergrund.",
    VENDOR_LABEL: "Hersteller:",
    MODEL_LABEL: "Modell:",
    BIOS_REV_LABEL: "BIOS-Version:",
    TOTAL_MEM_LABEL: "Physikalischer Speicher insgesamt:",
    MEMORY_MASK: "{0:n} MB",
    FREE_MEM_LABEL: "Verfügbarer physikalischer Speicher:",
    FREE_STORAGE_LABEL: "Verfügbarer Speicherplatz:",
    TOTAL_STORAGE_LABEL: "Speicherplatz insgesamt:",
    DISK_SPACE_MASK: "{0:n} MB",
    CPU_MODEL_LABEL: "Prozessor:",
    GPU_MODEL_LABEL: "Grafikprozessor:",
    ETH0_MAC_ADDRESS_LABEL: "MAC-Adresse der Netzwerkkarte:",
    ETH0_MODEL_LABEL: "Netzwerkkarte:",
    HOST_AMT_PT_LABEL: "Passthrough von MAC-Adresse:",
    ON_TEXT: "Aktiviert",
    OFF_TEXT: "Deaktiviert",
    WIRELESS_MAC_ADDRESS_LABEL: "MAC-Adresse der Drahtlosnetzwerkkarte:",
    WIRELESS_MODEL_LABEL: "Drahtlosnetzwerkkarte:",
    XENCLIENT_VERSION_LABEL: "OpenXT-Version:",
    XENCLIENT_VERSION_MASK: "{0} ({1}-Zweig)",
    XENCLIENT_BUILD_LABEL: "OpenXT-Build:",
    XENCLIENT_BUILD_MASK: "{0} ({1:d. MMMM y})",
    TOOLS_VERSION_LABEL: "Tools-CD-Version:",
    UPDATE_TITLE: "Softwareupdate",
    UPDATE_TOOLTIP: "Ihr Administrator sollte Ihnen eine URL zum Aktualisieren von OpenXT geben.",
    UPDATE_ACTION: "Nach Updates suchen",
    CANCEL_DOWNLOAD_ACTION: "Download abbrechen",
    DISCARD_UPDATE_ACTION: "Update verwerfen",
    UPDATE_SHUTDOWN: "Download war erfolgreich. Starten Sie das Gerät neu, um das Update anzuwenden.",
    LID_CLOSE_LABEL: "Zuklappaktion",
    LID_CLOSE_AC_POWER_LABEL: "Netzbetrieb:",
    SLEEP_ALL_OPTION: "Standbymodus für gesamtes System",
    DO_NOTHING_OPTION: "Keine Aktion",
    LID_CLOSE_BATTERY_LABEL: "Batteriebetrieb:",
    BRIGHTNESS_LABEL: "Bildschirmhelligkeit",
    TOUCHPAD_OPTIONS: "Touchpad-Optionen",
    TAP_TO_CLICK_LABEL: "Touchpad-Tippen als Klicken festlegen:",
    SCROLLING_LABEL: "Touchpad-Bildlauf festlegen:",
    SPEED_LABEL: "Touchpad-Geschwindigkeit:",
    SLOW: "Langsam",
    FAST: "Schnell",
    LEFT: "Links",
    RIGHT: "Rechts",
    POINTER_TRAIL: "Mauszeigerspur",
    NONE_TEXT: "Ohne",
    SHORT_TEXT: "Kurz",
    LONG_TEXT: "Lang",
    KEYBOARD_LAYOUT: "Tastaturlayout",
    LANGUAGE_HEADER: "Sprache",
    TRANSMITTER_STATE_LABEL: "Status:",
    TRANSMITTER_STATE_UNREGISTERED: "Nicht registriert",
    TRANSMITTER_STATE_PREREGISTERED: "Vorab registriert",
    TRANSMITTER_STATE_CONNECTED: "Verbunden",
    TRANSMITTER_STATE_DISCONNECTED: "Getrennt",
    TRANSMITTER_URL_LABEL: "Synchronizer-Hostname:",
    TRANSMITTER_VERSION_LABEL: "Version:",
    TRANSMITTER_BUILD_LABEL: "Build:",
    TRANSMITTER_LOGGEDIN_LABEL: "Registrierter Benutzer:",
    TRANSMITTER_HEADER: "Registrieren Sie sich bei einem Synchronizer, um neue VMs herunterzuladen und Sicherungskopien davon zu erstellen.",
    REGISTER_ACTION: "Registrieren",
    CONNECT_ACTION: "Mit Synchronizer verbinden",
    AUTH_SET_PASSWORD_TEXT: "Legen Sie ein Kennwort fest, um lokale Authentifizierung zu ermöglichen.",
    SET_PASSWORD_ACTION: "Kennwort festlegen",
    CHANGE_PASSWORD_ACTION: "Kennwort ändern",
    AUTH_REQUIRED_TEXT: "Kennwort bei Anmeldung:",
    AUTH_SET_TIMEOUT_TEXT: "Zeitlimit für Bildschirmsperre:",
    STATUS_REPORT: "Wenn Sie einen Statusbericht erstellen, werden Diagnoseinformationen von diesem Gerät in einer einzigen Datei gesammelt.<br/><br/>Dies ist jederzeit möglich, indem Sie STRG+ALT+R drücken.",
    CREATE_STATUS_REPORT: "Statusbericht erstellen",
    STATUS_SERVER_HEADER: "Berichtdownload",
    STATUS_SERVER: "Im Kapitel zur Problembehandlung in der OpenXT-Benutzerdokumentation finden Sie Informationen zum Herunterladen von Statusberichten.",
    BEGIN_STATUS_SERVER: "Berichte können heruntergeladen werden",
    STATUS_SERVER_INFO: "Sie sollten Berichte nur zum Download verfügbar machen, wenn Ihr Computernetzwerk gesichert ist und Ihr Administrator dies zulässt.",
    CLOSE_ACTION: "Schließen",
    SAVE_ACTION: "Speichern",
    SYS_INFO_DISPLAY_TITLE: "Anzeige",
    SEAMLESS_HEADER: "Mauswechsel",
    SWITCHER_LABEL: "Mauswechsel:",
    RESISTANCE_LABEL: "Umschaltwiderstand:",
    KEYBOARD_LABEL: "Tastatur folgt Maus:",
    ADAPTER_LABEL: "Legen Sie die Reihenfolge der Anzeigeadapter für nahtlose Mausbewegungen fest.",
    LANGUAGE_WARNING: "Die Spracheinstellung wurde geändert und die Benutzeroberfläche muss neu gestartet werden.",
    // Other
    AUTH_MANAGED_TEXT: "Melden Sie sich mit Ihren Synchronizer-Anmeldeinformationen an.",
    MINUTE: "Minute",
    MINUTES: "Minuten",
    NEVER: "Nie",
    ALREADY_CONNECTED: "Sie haben bereits eine Verbindung zum Synchronizer.",
    UPDATE_HEADER: "Softwareupdate",
    CANNOT_UPGRADE: "Installierte OpenXT-Version: {0}\nAktuelle OpenXT-Version: {1}\n\nEin Update auf diese OpenXT-Version ist nicht möglich.",
    CAN_UPGRADE: "Installierte OpenXT-Version: {0}\nAktuelle OpenXT-Version: {1}\n\nEine neuere Version von OpenXT wurde ermittelt. Möchten Sie dieses Update herunterladen?\n\nIn der Dokumentation finden Sie weitere Informationen dazu, welche Auswirkungen dies auf Ihr System haben kann.",
    UP_TO_DATE: "Installierte OpenXT-Version: {0}\nAktuelle OpenXT-Version: {1}\n\nSie führen die aktuelle Version von OpenXT aus, aber Sie können sie aktualisieren, indem Sie sie erneut herunterladen und anwenden.\n\nIn der Dokumentation finden Sie weitere Informationen dazu, welche Auswirkungen dies auf Ihr System haben kann.",
    START_DOWNLOAD_ACTION: "Herunterladen",
    SERVE_REPORT: "Berichte können von hier auf einer anderen Maschine heruntergeladen werden:\n\n{0}\n\nSie können von hier auf VMs auf dieser Maschine heruntergeladen werden:\n\n{1}",
    STOP_STATUS_SERVER: "Berichtverfügbarkeit beenden",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "Schweiz",
    KEYBOARD_LAYOUT_CN: "China",
    KEYBOARD_LAYOUT_FR: "Frankreich",
    KEYBOARD_LAYOUT_DE: "Deutschland",
    KEYBOARD_LAYOUT_IT: "Italien",
    KEYBOARD_LAYOUT_JP: "Japan",
    KEYBOARD_LAYOUT_ES: "Spanien",
    KEYBOARD_LAYOUT_GB: "Vereinigtes Königreich",
    KEYBOARD_LAYOUT_US: "Vereinigte Staaten",
    KEYBOARD_LAYOUT_RU: "Russland",
    KEYBOARD_LAYOUT_CA: "Kanada",
    KEYBOARD_LAYOUT_BR: "Brasilien",
    KEYBOARD_LAYOUT_NL: "Niederlande",
    KEYBOARD_LAYOUT_NO: "Norwegen",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Korea",
    KEYBOARD_LAYOUT_BE: "Belgien",
    KEYBOARD_LAYOUT_DK: "Dänemark",
    KEYBOARD_LAYOUT_IN: "Indien",
    KEYBOARD_LAYOUT_SE: "Schweden",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English"
})
