({
    // Layout
    DEFERRED_INSTALL_TITLE: "Willkommen bei OpenXT",
    EULA_HEADER: "Endbenutzer-Lizenzvereinbarung",
    KEYBOARD_HEADER: "Tastaturlayout",
    KEYBOARD_INSTR: "Wählen Sie ein Tastaturlayout aus.",
    LANGUAGE_HEADER: "Sprache",
    LANGUAGE_INSTR: "Wählen Sie eine Sprache aus.",
    ROOT_PASSWORD_HEADER: "Systemkennwort",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "Schweiz",
    KEYBOARD_LAYOUT_CN: "China",
    KEYBOARD_LAYOUT_FR: "Frankreich",
    KEYBOARD_LAYOUT_DE: "Deutschland",
    KEYBOARD_LAYOUT_IT: "Italien",
    KEYBOARD_LAYOUT_JP: "Japan",
    KEYBOARD_LAYOUT_ES: "Spanien",
    KEYBOARD_LAYOUT_GB: "Vereinigtes Königreich",
    KEYBOARD_LAYOUT_US: "Vereinigte Staaten",
    KEYBOARD_LAYOUT_RU: "Russland",
    KEYBOARD_LAYOUT_CA: "Kanada",
    KEYBOARD_LAYOUT_BR: "Brasilien",
    KEYBOARD_LAYOUT_NL: "Niederlande",
    KEYBOARD_LAYOUT_NO: "Norwegen",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Korea",
    KEYBOARD_LAYOUT_BE: "Belgien",
    KEYBOARD_LAYOUT_DK: "Dänemark",
    KEYBOARD_LAYOUT_IN: "Indien",
    KEYBOARD_LAYOUT_SE: "Schweden",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English",
    // Errors
    EULA_ERROR: "Nehmen Sie diese Endbenutzer-Lizenzvereinbarung an, um OpenXT zu verwenden. Wenn Sie abbrechen, wird OpenXT heruntergefahren.",
    KEYBOARD_ERROR: "Wählen Sie ein Tastaturlayout aus.",
    SET_SYSTEM_PASSWORD: "Für OpenXT ist ein Systemkennwort erforderlich."
})
