({
    // Controls
    START: "Starten",
    BACKGROUND_START: "Start im Hintergrund",
    SHUT_DOWN: "Herunterfahren",
    FORCE_SHUT_DOWN: "Ausschalten erzwingen",
    LOGIN: "Anmeldung",
    DETAILS: "Details",
    DELETE: "Löschen",
    // Tooltips
    XC_TOOLS_NOT_INSTALLED: "<strong>OpenXT-Tools nicht installiert</strong><br/><br/>Doppelklicken Sie auf die virtuelle OpenXT-Tools-CD im Betriebssystem Ihrer VM, um sie zu installieren.",
    XC_TOOLS_OLD_VERSION: "<strong>OpenXT-Tools veraltet</strong><br/><br/>Doppelklicken Sie auf die virtuelle OpenXT-Tools-CD im Betriebssystem Ihrer VM, um sie zu aktualisieren.",
    // Layout
    NAME_MASK: "Name: {0}",
    STATUS_MASK: "Status: {0}",
    SLOT_MASK: "Umschalttaste: STRG + {0}",
    // VM States
    VM_CREATED : "Wird gestartet",
    VM_STOPPED : "Aus",
    VM_STOPPING : "Wird angehalten",
    VM_REBOOTING : "Wird neu gestartet",
    VM_REBOOTED : "Neu gestartet",
    VM_PAUSED : "an",
    VM_SUSPENDING : "Im Ruhezustand",
    VM_SUSPENDED : "Im Ruhezustand",
    VM_RUNNING : "an",
    VM_LOCKED : "Gesperrt",
    VM_ASLEEP : "Im Standbymodus",
    // XenConstants.DesktopStates
    PUBLISHING: "Wird hochgeladen",
    BACKING_UP: "Sicherungskopie wird erstellt",
    DOWNLOADING: "Wird heruntergeladen",
    UPDATING: "Wird aktualisiert",
    FORCE_UPDATING: "Erzwungene Aktualisierung wird durchgeführt",
    READY: "Bereit",
    LOCKED: "Gesperrt",
    REMOTE_LOCKED: "Gesperrt",
    UNMANAGED: "Nicht verwaltet",
    // XenConstants.SyncOpStates
    PREPARING: "Wird vorbereitet",
    PREPARATION_FAILED: "Vorbereitung fehlgeschlagen",
    TRANSFER_PENDING: "Übertragung ausstehend",
    COMPUTING_DIGEST: "Prüfsumme wird berechnet",
    TRANSFER_ACTIVE: "Wird übertragen",
    TRANSFER_PAUSED: "Angehalten",
    TRANSFER_FAILED: "Fehlgeschlagen",
    TRANSFER_NETINT_STALLED: "Bitte warten... Server nicht erreichbar",
    TRANSFER_ADMCTL_STALLED: "Bitte warten... Server ist ausgelastet",
    INSTALLING_IMAGE: "Image wird installiert",
    TRANSFER_FINISHED: "Übertragung abgeschlossen",
    SHUTDOWN_REQUIRED: "Herunterfahren erforderlich",
    CLEAN_SHUTDOWN_REQUIRED: "Sauberes Herunterfahren erforderlich",
    BACKGROUND_FAILED: "Hintergrundvorgang fehlgeschlagen"
})
