({
    // Layout
    START: "Starten",
    BACKGROUND_START: "Start im Hintergrund",
    SHUT_DOWN: "Herunterfahren",
    REBOOT: "Neustart",
    HIBERNATE: "Ruhezustand",
    SLEEP: "Standbymodus",
    FORCE_SHUT_DOWN: "Ausschalten erzwingen",
    LOGIN: "Anmeldung",
    UPLOAD_VM: "VM hochladen",
    BACKUP_NOW: "Jetzt sichern",
    CHECK_NOW: "Jetzt suchen",
    ADD_DEVICE: "Gerät hinzufügen",
    DELETE: "Löschen",
    DETAILS: "Details",
    PAUSE: "Anhalten",
    RESUME: "Fortsetzen",
    RETRY: "Wiederholen",
    CANCEL: "Abbrechen",
    GENERAL: "Allgemein",
    DEVICES: "Geräte",
    DEVICE: "Gerät",
    NO_DEVICES: "Keine Geräte angeschlossen",
    OPTIONS: "Optionen",
    ACTIONS: "Aktionen",
    ALWAYS_USE: "Immer mit dieser VM verwenden",
    DISCONNECT: "Trennen",
    SYNCHRONIZATION: "Synchronisierung",
    HARDWARE: "Hardware",
    ICON: "Symbol",
    ADVANCED: "Erweitert",
    NAME: "Name:",
    VCPUS: "vCPUs:",
    MEMORY: "Speicher (MB):",
    AUTOBOOT: "Autoboot:",
    AUTOBOOT_TOOLTIP: "Diese VM starten, wenn der Host gestartet wird.",
    POWER_BEHAVIOUR: "Energiesteuerung:",
    POWER_BEHAVIOUR_TOOLTIP: "Wenn die VM heruntergefahren wird oder im Ruhezustand oder Standbymodus ist, tut das Hostgerät das gleiche.",
    POWER_BEHAVIOUR_ENABLED: "Energiesteuerung gilt für VM und Host",
    POWER_BEHAVIOUR_DISABLED: "Energiesteuerung gilt nur für VM",
    SWITCHER_KEY: "Umschalttaste:",
    TOOLS_CD: "Tools-CD:",
    INSTALLED_TOOLS_MASK: "Installiert: {0}",
    THREED_GFX: "3D-Grafiken:",
    TYPE: "Typ:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 Bit",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 Bit",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 Bit",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 Bit",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 Bit (experimentell)",
    TYPE_UNKNOWN: "Unbekannt",
    DESCRIPTION: "Beschreibung:",
    REGISTERED_USER: "Registrierter Benutzer:",
    BACKUP_MODE: "Sicherungsmodus:",
    BACKUP_NONE: "Ohne",
    BACKUP_USER: "Benutzerdaten",
    BACKUP_ALL: "Alle Daten",
    BACKUP_SCHEDULE: "Sicherungszeitplan:",
    UPDATE_SCHEDULE: "Aktualisierungszeitplan:",
    LEASE_EXPIRATION: "Leaseablaufdatum:",
    SAVE_ACROSS_REBOOTS: "Änderungen für Neustarts speichern:",
    DESKTOP_NAME: "Desktopname:",
    CURRENT_VERSION: "Aktuelle Version:",
    BASE_VERSION: "Übergeordnete Version:",
    WIRELESS_NETWORK: "Drahtlosnetzwerk:",
    WIRED_NETWORK: "Netzwerk:",
    WIRED_NIC: "MAC-Adresse der Netzwerkkarte:",
    DISK_SPACE: "Speicherplatz:",
    ALLOW_OEM: "OEM-Windows-Installation zulassen:",
    EXPOSE_HARDWARE_INFO: "Physikalische Hardwareinformationen verfügbar machen:",
    DISPLAY_VM: "VM in Umschaltleiste anzeigen:",
    AMT_PASSTHROUGH: "Intel AMT-Passthrough:",
    OEM_ACPI_PASSTHROUGH: "Physikalische OEM-Hardware verfügbar machen:",
    BOOT_ORDER: "Startreihenfolge:",
    EDIT: "Bearbeiten",
    SAVE: "Speichern",
    CLOSE: "Schließen",
    MANAGED_ENABLED: "Verwaltete VM",
    THREED_GRAPHICS_ENABLED: "3D-Grafiken aktiviert",
    PUBLISH_APP_ENABLED: "Anwendungsveröffentlichung",
    ENABLED: "Aktiviert",
    DISABLED: "Deaktiviert",
    NONE: "Ohne",
    INSTALLED_NONE: "Keine Tools installiert",
    NEVER: "Nie",
    ATTACHED: "Zugewiesen",
    SHARED_WIRELESS: "NAT-Drahtlosnetzwerk",
    SHARED_3G: "NAT 3G (experimentell)",
    BRIDGED: "Direkt",
    SHARED: "NAT",
    INTERNAL: "Intern",
    BRIDGED_MASK: "Direkt auf {0}",
    SHARED_MASK: "NAT auf {0}",
    INTERNAL_MASK: "Intern auf {0}",
    POLICY_DISABLED: "Durch Richtlinie deaktiviert",
    CHANGE_VERSION: "Version ändern",
    NAME_VALERROR: "Ein Name ist erforderlich. Er darf höchstens 60 Zeichen enthalten: Buchstaben, Zahlen, Leerzeichen und manche Satzzeichen (u. a. Unterstrich, Bindestrich, Klammer, Punkt, Apostroph und Komma).",
    DESCRIPTION_VALERROR: "Die Beschreibung darf höchstens 200 Zeichen enthalten: Buchstaben, Zahlen, Leerzeichen und manche Satzzeichen (u. a. Unterstrich, Bindestrich, Klammer, Punkt, Apostroph und Komma).",
    MEMORY_MASK: "{0:n}",
    SYSTEM_MEMORY_MASK: "Insgesamt: {0:n}, Verfügbar: {1:n}",
    DISK_SPACE_MASK: "Privat: {0}, Freigegeben: {1}",
    BACKUP_FREQUENCY_MASK: "{0:n} Stunde(n)",
    UPDATE_FREQUENCY_MASK: "{0:n} Minute(n)",
    LEASE_EXPIRATION_MASK: "{0:n} Tag(e)",
    BACKUP_LAST_MASK: "Letzte Sicherung am {0:d. MMMM y H:mm} (UTC)",
    UPDATE_LAST_MASK: "Letzte Aktualisierung am {0:d. MMMM y H:mm} (UTC)",
    BACKUP_SCHEDULE_MASK: "Nächste Sicherung am {0:d. MMMM y H:mm} (UTC)",
    UPDATE_SCHEDULE_MASK: "Nächste Updatesuche am {0:d. MMMM y H:mm} (UTC)",
    LEASE_SCHEDULE_MASK: "Nächstes Mal am {0:d. MMMM y H:mm} (UTC)",
    BACKUP_LAST_MASK_1: "Letzte Sicherung war vor {0:n} Stunde(n), {1:n} Minute(n)",
    UPDATE_LAST_MASK_1: "Letzte Aktualisierung war vor {0:n} Stunde(n), {1:n} Minute(n)",
    BACKUP_NEXT_MASK: "Nächste Sicherung in {0:n} Stunde(n), {1:n} Minute(n)",
    UPDATE_NEXT_MASK: "Nächste Updatesuche in {0:n} Stunde(n), {1:n} Minute(n)",
    LEASE_NEXT_MASK: "Nächstes Mal in {0:n} Tag(en), {1:n} Stunde(n)",
    NETWORK_INFORMATION: "Ein <strong>direktes</strong> Netzwerk verbindet eine VM direkt mit dem externen Netzwerk.<br/>Ein <strong>NAT</strong>-Netzwerk verwendet dieselbe Netzwerk-IP-Adresse für alle VMs.<br/>Das <strong>interne</strong> Netzwerk ist mit keinem externen Netzwerk verbunden.",
    TRANSFER: "Übertragung",
    TRANSFER_STATE: "Status:",
    TRANSFER_PROGRESS: "Fortschritt:",
    TRANSFER_SPEED_MASK: "{0:f} MB/s",
    SWITCHER_KEY_MASK: "STRG + {0}",
    SWITCHER_DROPDWON_MASK: " ({0})",
    THIS_VM: "diese VM",
    CD_DRIVE: "CD-Laufwerk",
    HARD_DRIVE: "Festplatte",
    NETWORK: "Netzwerk",
    BOOT_TITLE: "Startoption hinzufügen...",
    HDX_TOOLTIP: "Es kann nur eine virtuelle Maschine mit dieser Fähigkeit auf dem System ausgeführt werden. Um dieses Feature zu aktivieren, muss die virtuelle Maschine ausgeschaltet sein und es müssen OpenXT-Tools und Intel-Videotreiber installiert sein.",
    MEMORY_TOOLTIP: "Dieses Feature kann nicht geändert werden, während die virtuelle Maschine im Ruhezustand ist.",
    VCPU_TOOLTIP: "Dieses Feature kann nicht geändert werden, während die virtuelle Maschine im Ruhezustand ist.",
    DISK_SPACE_TOOLTIP: "Privat: Speicherplatz, der nur von dieser virtuellen Maschine verwendet wird.<br/>Freigegeben: Speicherplatz, der mit anderen virtuellen Maschinen im System gemeinsam verwendet wird.",
    AMT_PT_TOOLTIP: "Wenn Sie Intel Active Management Technology (AMT) Management Engine (ME) aktivieren, wird hardwarebasierte Netzwerkverwaltung ermöglicht, mit der Out-of-band-Zugriff auf OpenXT-Geräte zu Verwaltungszwecken möglich ist. Dies kann nur für eine VM aktiviert werden.",
    ACPI_PT_TOOLTIP: "ACPI_SLIC-Tabelle des Hosts für die VM verfügbar machen, um OEM-Editionen von Windows zu entsperren.",
    SMBIOS_PT_TOOLTIP: "SMBIOS-Datensatztypen verfügbar machen, die die Hosthardware für die VM beschreiben, anstatt denen, die von OpenXT bereitgestellt wurden.",
    OEM_ACPI_PT_TOOLTIP: "OEM-Hardware direkt für die VM verfügbar machen. Dies kann nur für eine VM aktiviert werden.",
    POWER: "Energiemodus",
    COMMUNICATION: "Unterstützung für Seamless-Anwendungen:",
    COMMUNICATION_TOOLTIP: "Steuert Firewalleinstellungen virtueller Machinen, damit Seamless-Anwendungen funktionieren.",
    ADVANCED_WARNING: "Dieser Bereich ist für fortgeschrittene Features und sollte nur angepasst werden, wenn Sie mit den Auswirkungen auf das System vertraut sind.",
    INTEL_AMT: "Intel AMT ME-Passthrough wird erst nach dem Neustart von OpenXT wirksam.",
    MEMORY_CHANGE: "Die Speicheränderung wird beim nächsten Start der virtuellen Maschine wirksam.",
    BACKUP_VM: "VM sichern",
    VM_UPDATE_CHECK: "Nach VM-Updates suchen",
    DELETE_VM_HEADER: "Virtuelle Maschine löschen",
    DELETE_VM: "Möchten Sie die virtuelle Maschine '{0}' wirklich löschen?",
    ACCEPT_DELETE: "Ja, löschen",
    XEN_MGR_DELETE: "VM löschen",
    USB_UNASSIGN: "Dieses USB-Gerät wird zurzeit von dieser VM verwendet. Wenn Sie die Auswahl aufheben, wird das Entfernen des Geräts von dieser VM erzwungen. Dies kann zu Datenverlust führen. Sie können das Gerät sauber entfernen, indem Sie es vom Betriebssystem Ihrer VM aus auswerfen.",
    UPLOAD_VM_STATUS: "Sie können eine virtuelle Maschine nur hochladen, wenn ihr Zustand 'Aus' ist.",
    ADD_DEVICE_STATUS: "Sie können ein Gerät nur anschließen, wenn die virtuelle Maschine eingeschaltet ist und OpenXT-Tools installiert sind.",
    DELETE_VM_STATUS: "Sie können eine virtuelle Maschine nur hochladen, wenn ihr Zustand 'Aus' oder 'Im Ruhezustand' ist.",
    FORCE_UPDATE: "Fehler bei erzwungener Aktualisierung der VM",
    USB_DISABLED: "Es können keine Geräte hinzugefügt werden, weil die Geräteverwaltung für diese VM deaktiviert wurde."
})
