({
    // Notifications
    SAFE_GRAPHICS_MODE: "安全图形模式",
    AUTH_FOR_AUTO_START: "您的虚拟机需要先进行身份验证才能自动启动。请按 Ctrl+Alt+Backspace 启用安全身份验证。",
    AUTH_START: "请按 Ctrl+Alt+Backspace 启用安全身份验证。",
    CTRL_SWITCH: "要返回此屏幕，请使用:<div class='ctrlText'><span class='ctrlButton'>Ctrl</span> + <span class='ctrlButton'>0</span></div>",
    SEVERAL_VMS: "运行未安装 OpenXT Tools 的多台虚拟机可能会导致系统性能不佳。如有可能，应安装 OpenXT Tools。",
    // Alerts
    LOW_SPACE_WARNING: "磁盘空间不足。当前可用空间仅占 {0}%。",
    LOW_SPACE_TOOLTIP: "<strong>磁盘空间不足</strong><br/><br/>当前可用空间仅占 {0}%。",
    // Errors
    AJAX_FAILED: "AJAX 请求失败\r\nID: {0}；方法: {1}",
    UNEXPECTED_RESULT: "接口的 signalRegister 返回意外结果 ",
    SIGNAL_ERROR: "接收信号时出错；队列: {0}",
    UNEXPECTED_RCV_RESULT: "receiveSignals 返回意外结果",
    SERVICE_NOT_RUNNING: "{0} 服务未运行。",
    XT_BED_NOT_RUNNING_ACTION: "由于 Synchronizer 守护程序未运行，因而无法完成此操作。",
    XT_VERSION_MISMATCH_INFO: "无法连接到 Synchronizer。“{0}”服务器与“{1}”客户端不兼容。",
    // XenConstants.ToolstackCodes
    NOT_ENOUGH_FREE_MEMORY: "可用内存不足，无法实现您的请求",
    VM_BAD_STATE: "虚拟机状态异常",
    VM_UNEXPECTED_SHUTDOWN_REASON: "关闭原因与预期原因不符",
    VM_NOT_SHUTDOWN: "虚拟机未关闭",
    VM_ALREADY_CREATED: "虚拟机已创建",
    VT_MISSING: "必须先启用硬件虚拟化功能，才能使用虚拟机。请检查您的 BIOS 设置。",
    VM_TAP_MOUNT_FAILURE: "虚拟机因未处于就绪状态而无法启动。<br/>这可能是由于其他进程正在更新该虚拟机，请稍后再试。",
    HDX_AUTOSTART_MULTIPLE: "无法在多台 VM 上同时激活 HDX 和自动激活功能。",
    VM_HIBERNATE_FAILED: "虚拟机无法休眠",
    VM_EDIT_DISABLED: "此 VM 的活动策略禁用了编辑属性功能",
    NO_SUCH_DEVICE: "无此类设备",
    VM_CANNOT_DELETE_RUNNING: "VM 正在运行，无法将其删除",
    VM_COUNT_HIGH: "虚拟机过多",
    DISK_NOT_EXIST: "无此类磁盘",
    INCORRECT_DISK_TYPE: "磁盘类型不正确",
    INCORRECT_DEVICE_TYPE: "设备类型不正确",
    HDX_CHANGE_WHILE_RUNNING: "VM 正在运行，无法打开或关闭 HDX",
    HDX_ENABLE_NO_TOOLS: "OpenXT Tools 未安装，无法打开 HDX",
    HDX_NO_VTD: "VT-d 未启用，无法启动启用了 HDX 的 VM",
    DISK_DEVICE_EXISTS: "设备已存在，无法添加指定磁盘",
    TOOLS_REQUIRED: "执行此操作需要在 VM 上安装 OpenXT Tools",
    PROPERTY_READ_ONLY: "属性为只读",
    PROPERTY_WRITE_ONLY: "属性为只写",
    NO_DIAGNOSTICS: "当前未收集诊断信息",
    INCORRECT_DISK_HASH: "磁盘哈希值不一致",
    TOO_MANY_HDX: "已在运行的启用了 HDX 的 VM 过多，无法启动 VM",
    VM_PASSTHRU_RUNNING: "另一启用了 AMT Passthrough 功能的 VM 已在运行，无法启动 VM",
    POLICY_SUPPRESSED_ACTION: "此操作已被活动策略设置禁止",
    VM_HIBERNATE_CHANGE: "此 VM 已休眠，无法更改其属性",
    NIC_NOT_FOUND: "无此类网络接口",
    IO_ERROR: "IO 错误",
    VM_RESUME_FAILED: "无法将 VM 从睡眠状态恢复",
    OPERATION_SUPPRESSED_ACTION: "另一项后台操作正在进行，无法完成请求的操作",
    VM_NO_RPC_AGENT: "VM 未配置为使用 RPC 代理",
    VM_SLEEP_TIMEOUT: "等待 VM 进入睡眠状态超时",
    VM_HIBERNATE_TIMEOUT: "等待 VM 进入休眠状态超时",
    VM_SHUTDOWN_TIMEOUT: "等待 VM 关闭超时",
    DEVICE_ATTACHED_ELSEWHERE: "当前正将设备传递到其他 VM",
    ADAPTER_NOT_SECONDARY: "无法作为二级适配器传递图形卡",
    NETWORK_NOT_RUNNNING: "网络后端域未运行",
    OEM_ACPI_RUNNING: "另一启用了 OEM-ACPI 功能的 VM 已在运行，无法启动 VM",
    UNKNOWN_GPU: "未知 GPU",
    VM_TXT_SLEEP_DISABLED: "主机睡眠模式在 TXT 测量启动环境中处于禁用状态",
    UNSUPPORTED_LANGUAGE: "不支持的语言",
    RULE_PARSE_ERROR: "规则解析错误",
    // XenConstants.UpdateCodes
    UPDATE_INTERNAL_ERROR: "发生内部错误",
    UPDATE_DOWNLOAD_FAILED: "下载失败",
    UPDATE_DOWNLOAD_CANCELLED: "下载已取消",
    UPDATE_MISSING_METADATA: "元数据丢失",
    UPDATE_MALFORMED_METADATA: "元数据格式不正确",
    UPDATE_UPDATE_NOT_APPLICABLE: "更新不适用",
    UPDATE_ALREADY_RUNNING: "更新已在运行",
    UPDATE_VM_RUNNING: "来宾 VM 运行过程中无法应用更新。\n请关闭所有正在运行的 VM 并重试。",
    UPDATE_CORRUPT_FILE: "遇到已损坏的文件",
    UPDATE_UP_TO_DATE: "已处于最新状态",
    UPDATE_FILE_NOT_FOUND: "找不到更新存储库，请核对您的 URL",
    UPDATE_CANNOT_RESOLVE_HOST: "无法解析主机，请核对您的 URL",
    UPDATE_CANNOT_CONNECT_HOST: "无法连接到主机，请核对您的 URL",
    UPDATE_SIGNATURE_FAILED: "无法验证更新签名",
    UPDATE_POLICY_DISABLED: "更新已被策略禁用",
    // XenClient.Resource.RegisterStatus
    NETWORK_DISCONNECTED_2: "未连接任何网络",
    SERVER_UNREACHABLE: "无法连接到服务器，请核对 URL",
    CERT_CA_MISSING: "OpenXT 无法注册此设备。请检查 Synchronizer 的配置，并确定 OpenXT 是否已正确安装: ",
    CERT_VERIFY_FAILED: "无法验证服务器:",
    CERT_GENERIC: "发生一般性错误",
    CERT_TRUST_ROOT_CERT_FAILED: "无法信任根证书",
    CERT_AUTH_CODE_MISMATCH: "身份验证代码与证书生成的代码不匹配",
    CERT_GET_CHAIN_FAILED: "无法从服务器获取证书链",
    HOSTNAME_INVALID: "传递到注册中的主机名无效",
    CERT_NO_CN: "服务器证书中无公用名",
    CERT_HOSTNAME_CN_MISMATCH: "证书中的公用名与传递到注册中的主机名不匹配，证书中的公用名为: {0}"
})
