({
    // Layout
    CREATE_FROM_MEDIA: "从安装磁盘创建",
    CREATE_VM_WIZARD_NAME_HEADER: "名称和类型",
    TYPE_LABEL: "类型:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 位",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 位",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 位",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 位",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 位(实验版本)",
    TYPE_UNKNOWN: "未知",
    VM_NAME_LABEL: "VM 名称:",
    DESCRIPTION_LABEL: "说明:",
    CREATE_VM_WIZARD_ICON_HEADER: "图标",
    CREATE_VM_WIZARD_MEMORY_HEADER: "内存和 CPU",
    CREATE_VM_WIZARD_MEMORY_ALT_HEADER: "内存",
    MEMORY_LABEL: "内存:",
    MB_INDICATOR_TEXT: "(MB)",
    GB_INDICATOR_TEXT: "(GB)",
    TOTAL_MEM_MASK: "内存总量: {0:n}",
    FREE_MEM_MASK: "可用内存: {0:n}",
    VCPUS_LABEL: "vCPU:",
    CREATE_VM_WIZARD_STORAGE_HEADER: "存储和网络连接",
    STORAGE_LABEL: "虚拟磁盘大小:",
    WIRELESS_LABEL: "无线网络:",
    NETWORK_WIRELESS_OPTION: "共享无线网络",
    NETWORK_3G_OPTION: "共享 3G (实验网络)",
    WIRED_LABEL: "有线网络:",
    NETWORK_BRIDGED_OPTION: "桥接",
    NETWORK_SHARED_OPTION: "共享",
    NETWORK_INTERNAL_OPTION: "内部",
    NETWORK_BRIDGED_MASK: "在 {0} 上桥接",
    NETWORK_SHARED_MASK: "在 {0} 上共享",
    NETWORK_INTERNAL_MASK: "在 {0} 内部",
    WIRED_NETWORK_INFORMATION: "<strong>桥接</strong>网络可将 VM 直接连接到外部网络。<br/><strong>共享</strong>网络可对所有 VM 重复使用一个网络 IP 地址。<br/><strong>内部</strong>网络未连接到任何外部网络。",
    CREATE_VM_WIZARD_FINISH_HEADER: "完成",
    CREATE_VM_WIZARD_FINISH_PARA1: "您已准备好从操作系统安装磁盘创建 VM。",
    AUTOSTART_LABEL: "启动 VM 并安装操作系统",
    AUTOSTART_OFF_LABEL: "稍后创建 VM 并安装操作系统",
    CREATE_VM_WIZARD_FINISH_PARA2: "操作系统安装完成后，双击 <strong>OpenXT Tools Virtual CD</strong> 可安装 OpenXT Tools。",
    // Errors
    NAME_VALERROR: "名称为必填项，且不得超过 60 个字符，可以包含字母、数字、空格以及某些标点符号(包括下划线、破折号、括号、句号、省略号和逗号)。",
    DESCRIPTION_VALERROR: "“说明”部分不应超过 200 个字符，可以包含字母、数字、空格以及某些标点符号(包括下划线、破折号、括号、句号、省略号和逗号)。",
    VM_ERRORS: "虚拟机已创建，但存在错误。请检查您为新虚拟机所做的设置。"
})
