({
    // Layout
    CREATE_STATUS_REPORT: "创建状态报告",
    REPORT_WELCOME: "欢迎",
    REPORT_DESCRIPTION: "此向导将整理此系统中的诊断信息。<br/><ul><li>此向导将整理 Xen dmesg 输出、您计算机的硬件配置详细信息、与构建要使用的 Xen 有关的信息以及各种日志。<br/><br/></li><li>整理后的信息将可以 .tar.bz2 格式下载，以便存档或发送给技术支持代表。</li></ul>",
    REPORT_VM_DESCRIPTION: "此工具可以有选择性地从 VM 中获取诊断信息，包括当前正在运行的 VM 的日志和屏幕截图。这些信息已证明对诊断技术问题非常有帮助。",
    REPORT_INCLUDE_VMSCREENS: "在此报告中包含 VM 的屏幕截图",
    REPORT_INCLUDE_VMS: "在此报告中包含 VM 中的其他诊断信息",
    REPORT_INFO: "日志中可能包含个人信息，如果这些信息非常重要，请明确指出不要将 VM 日志包含在存档文件中。选择不将 VM 信息包括在报告中可能会阻碍对您的问题进行诊断。",
    REPORT_SUMMARY: "说明",
    REPORT_DETAILS: "请输入问题摘要及详细说明",
    SUMMARY_LABEL: "摘要:",
    SUMMARY_VALERROR: "“摘要”为必填项，且不得超过 60 个字符，可以包含字母、数字、空格以及某些标点符号(包括下划线、破折号、括号、句号、省略号和逗号)。",
    DESCRIPTION_LABEL: "说明:",
    REPORT_SUMMARY_INFO: "对于摘要部分，使用的词语数请尽量不要超过八个。",
    REPORT_STEPS: "重现",
    REPORT_REPRO: "如有可能，请描述重现此问题的具体步骤。",
    REPORT_REPRO_LABEL: "重现步骤:",
    REPORT_TICKET: "如果您有技术支持案例编号或票据编号，请在此处输入。",
    REPORT_TICKET_LABEL: "技术支持案例编号:",
    REPORT_GENERATION: "生成",
    REPORT_SERVER_DESCRIPTION: "生成报告后，此向导将在此计算机上运行一台临时的专用 Web 服务器，从而使报告可供下载。您随后可以将该 Web 服务器公告的 URL 输入到 Web 浏览器中。<br/><br/>如果不打算立即下载，请取消选择下面的框。",
    REPORT_SERVER: "生成过程完成后启用报告下载功能",
    REPORT_FINISHED: "此向导已收集了足够的信息，可以生成状态报告。<br/><br/>请核对您输入的信息，并单击“下一步”生成报告。",
    GENERATING_REPORT: "正在生成报告，请稍候...",
    STATUS_SERVER_INFO: "仅应在计算机网络非常安全，且管理员允许的情况下，才使报告可供下载。",
    REPORT_FINISH: "完成",
    REPORT_CREATED: "以下状态报告已成功创建:<br/><br/><strong>{0}</strong>",
    REPORT_FINISH_SERVER: "要下载报告，请使用“系统设置”中的“状态报告”部分。",
    STOP_SERVER: "关闭此向导将使报告不再可供下载。",
    SERVE_REPORT: "可以将以下位置处的报告下载到其他计算机中:\n\n{0}\n\n可以将以下位置处的报告下载到此计算机上的 VM 中:\n\n{1}"
})