({
    // Layout
    SYS_INFO_HEADER: "系统设置",
    SYS_INFO_WALLPAPER_TITLE: "墙纸",
    SYS_INFO_POWER_TITLE: "电源",
    SYS_INFO_TOUCHPAD_TITLE: "接口",
    SYS_INFO_TRANSMITTER_TITLE: "Synchronizer",
    SYS_INFO_AUTH_TITLE: "登录",
    SYS_INFO_SOFTWARE_TITLE: "软件",
    SYS_INFO_HARDWARE_TITLE: "硬件",
    SYS_INFO_NETWORK_TITLE: "网络连接",
    STATUS_REPORT_HEADER: "状态报告",
    WALLPAPER_HEADER: "单击您喜爱的墙纸图像",
    VENDOR_LABEL: "供应商:",
    MODEL_LABEL: "型号:",
    BIOS_REV_LABEL: "BIOS 修订版:",
    TOTAL_MEM_LABEL: "物理内存总量:",
    MEMORY_MASK: "{0:n} MB",
    FREE_MEM_LABEL: "可用物理内存:",
    FREE_STORAGE_LABEL: "可用磁盘空间:",
    TOTAL_STORAGE_LABEL: "磁盘空间总量:",
    DISK_SPACE_MASK: "{0:n} MB",
    CPU_MODEL_LABEL: "物理 CPU 型号:",
    GPU_MODEL_LABEL: "物理 GPU 型号:",
    ETH0_MAC_ADDRESS_LABEL: "有线网络 MAC 地址:",
    ETH0_MODEL_LABEL: "有线网络型号:",
    HOST_AMT_PT_LABEL: "MAC 地址传递:",
    ON_TEXT: "已启用",
    OFF_TEXT: "已禁用",
    WIRELESS_MAC_ADDRESS_LABEL: "无线网络 MAC 地址:",
    WIRELESS_MODEL_LABEL: "无线网络型号:",
    XENCLIENT_VERSION_LABEL: "OpenXT 版本:",
    XENCLIENT_VERSION_MASK: "{0} ({1})",
    XENCLIENT_BUILD_LABEL: "OpenXT 内部版本:",
    XENCLIENT_BUILD_MASK: "{0} ({1:y-M-d})",
    TOOLS_VERSION_LABEL: "Tools CD 版本:",
    UPDATE_TITLE: "软件更新",
    UPDATE_TOOLTIP: "管理员应提供用于更新 OpenXT 的 URL",
    UPDATE_ACTION: "检查更新",
    CANCEL_DOWNLOAD_ACTION: "取消下载",
    DISCARD_UPDATE_ACTION: "放弃更新",
    UPDATE_SHUTDOWN: "下载成功，请重新启动您的设备以应用更新",
    LID_CLOSE_LABEL: "合盖操作",
    LID_CLOSE_AC_POWER_LABEL: "使用交流电源:",
    SLEEP_ALL_OPTION: "使整个系统进入睡眠状态",
    DO_NOTHING_OPTION: "不执行任何操作",
    LID_CLOSE_BATTERY_LABEL: "使用电池:",
    BRIGHTNESS_LABEL: "屏幕亮度",
    TOUCHPAD_OPTIONS: "触控板选项",
    TAP_TO_CLICK_LABEL: "触控板轻敲单击:",
    SCROLLING_LABEL: "触控板滚动:",
    SPEED_LABEL: "触控板速度",
    SLOW: "慢",
    FAST: "快",
    LEFT: "左",
    RIGHT: "右",
    POINTER_TRAIL: "鼠标指针尾巴",
    NONE_TEXT: "无",
    SHORT_TEXT: "短",
    LONG_TEXT: "长",
    KEYBOARD_LAYOUT: "键盘布局",
    LANGUAGE_HEADER: "语言",
    TRANSMITTER_STATE_LABEL: "状态:",
    TRANSMITTER_STATE_UNREGISTERED: "未注册",
    TRANSMITTER_STATE_PREREGISTERED: "已预先注册",
    TRANSMITTER_STATE_CONNECTED: "已连接",
    TRANSMITTER_STATE_DISCONNECTED: "已断开连接",
    TRANSMITTER_URL_LABEL: "Synchronizer 主机名:",
    TRANSMITTER_VERSION_LABEL: "版本:",
    TRANSMITTER_BUILD_LABEL: "内部版本:",
    TRANSMITTER_LOGGEDIN_LABEL: "注册用户:",
    TRANSMITTER_HEADER: "注册到 Synchronizer 以下载新 VM 并进行备份。",
    REGISTER_ACTION: "注册",
    CONNECT_ACTION: "与 Synchronizer 建立连接",
    AUTH_SET_PASSWORD_TEXT: "设置一个密码以启用本地身份验证。",
    SET_PASSWORD_ACTION: "设置密码",
    CHANGE_PASSWORD_ACTION: "更改密码",
    AUTH_REQUIRED_TEXT: "启动密码:",
    AUTH_SET_TIMEOUT_TEXT: "屏幕锁定超时:",
    STATUS_REPORT: "创建状态报告时将从此设备中收集诊断信息，并将其打包到一个文件中。<br/><br/>可以随时按 Ctrl+Alt+R 创建状态报告",
    CREATE_STATUS_REPORT: "创建状态报告",
    STATUS_SERVER_HEADER: "报告下载",
    STATUS_SERVER: "有关下载状态报告方面的帮助信息，请参阅《OpenXT 用户指南》中的“故障排除”一章。",
    BEGIN_STATUS_SERVER: "使报告可供下载",
    STATUS_SERVER_INFO: "仅应在计算机网络非常安全，且管理员允许的情况下，才使报告可供下载。",
    CLOSE_ACTION: "关闭",
    SAVE_ACTION: "保存",
    SYS_INFO_DISPLAY_TITLE: "显示",
    SEAMLESS_HEADER: "鼠标切换",
    SWITCHER_LABEL: "鼠标切换:",
    RESISTANCE_LABEL: "切换电阻:",
    KEYBOARD_LABEL: "键盘跟随鼠标:",
    ADAPTER_LABEL: "设置适配器的显示顺序，以实现无缝鼠标移动。",
    LANGUAGE_WARNING: "语言设置已更改，需要重新启动用户界面。",
    // Other
    AUTH_MANAGED_TEXT: "请使用您的 Synchronizer 凭据进行登录。",
    MINUTE: "分钟",
    MINUTES: "分钟",
    NEVER: "从不",
    ALREADY_CONNECTED: "您已连接到 Synchronizer。",
    UPDATE_HEADER: "软件更新",
    CANNOT_UPGRADE: "已安装的 OpenXT 版本: {0}\n最新的 OpenXT 版本: {1}\n\n无法更新为此版本的 OpenXT。",
    CAN_UPGRADE: "已安装的 OpenXT 版本: {0}\n最新的 OpenXT 版本: {1}\n\n检测到较新版本的 OpenXT，是否要下载此更新?\n\n有关这一点如何影响您的系统方面的详细信息，请参阅相关文档。",
    UP_TO_DATE: "已安装的 OpenXT 版本: {0}\n最新的 OpenXT 版本: {1}\n\n您运行的是最新版本的 OpenXT，但可以通过再次下载并应用该版本进行更新。\n\n有关这一点如何影响您的系统方面的详细信息，请参阅相关文档。",
    START_DOWNLOAD_ACTION: "下载",
    SERVE_REPORT: "可以将以下位置处的报告下载到其他计算机中:\n\n{0}\n\n可以将以下位置处的报告下载到此计算机上的 VM 中:\n\n{1}",
    STOP_STATUS_SERVER: "停止报告可用性",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "瑞士",
    KEYBOARD_LAYOUT_CN: "中国",
    KEYBOARD_LAYOUT_FR: "法国",
    KEYBOARD_LAYOUT_DE: "德国",
    KEYBOARD_LAYOUT_IT: "意大利",
    KEYBOARD_LAYOUT_JP: "日本",
    KEYBOARD_LAYOUT_ES: "西班牙",
    KEYBOARD_LAYOUT_GB: "英国",
    KEYBOARD_LAYOUT_US: "美国",
    KEYBOARD_LAYOUT_RU: "Russia",
    KEYBOARD_LAYOUT_CA: "Canada",
    KEYBOARD_LAYOUT_BR: "Brazil",
    KEYBOARD_LAYOUT_NL: "Netherlands",
    KEYBOARD_LAYOUT_NO: "挪威",
    KEYBOARD_LAYOUT_LATAM: "拉美",
    KEYBOARD_LAYOUT_KR: "Korea",
    KEYBOARD_LAYOUT_BE: "Belgium",
    KEYBOARD_LAYOUT_DK: "Denmark",
    KEYBOARD_LAYOUT_IN: "India",
    KEYBOARD_LAYOUT_SE: "瑞典",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English"
})
