({
    // Layout
    DEFERRED_INSTALL_TITLE: "欢迎使用 OpenXT",
    EULA_HEADER: "EULA",
    KEYBOARD_HEADER: "键盘布局",
    KEYBOARD_INSTR: "请选择一种键盘布局。",
    LANGUAGE_HEADER: "语言",
    LANGUAGE_INSTR: "请选择一种语言。",
    ROOT_PASSWORD_HEADER: "系统密码",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "瑞士",
    KEYBOARD_LAYOUT_CN: "中国",
    KEYBOARD_LAYOUT_FR: "法国",
    KEYBOARD_LAYOUT_DE: "德国",
    KEYBOARD_LAYOUT_IT: "意大利",
    KEYBOARD_LAYOUT_JP: "日本",
    KEYBOARD_LAYOUT_ES: "西班牙",
    KEYBOARD_LAYOUT_GB: "英国",
    KEYBOARD_LAYOUT_US: "美国",
    KEYBOARD_LAYOUT_RU: "Russia",
    KEYBOARD_LAYOUT_CA: "Canada",
    KEYBOARD_LAYOUT_BR: "Brazil",
    KEYBOARD_LAYOUT_NL: "Netherlands",
    KEYBOARD_LAYOUT_NO: "挪威",
    KEYBOARD_LAYOUT_LATAM: "拉美",
    KEYBOARD_LAYOUT_KR: "Korea",
    KEYBOARD_LAYOUT_BE: "Belgium",
    KEYBOARD_LAYOUT_DK: "Denmark",
    KEYBOARD_LAYOUT_IN: "India",
    KEYBOARD_LAYOUT_SE: "瑞典",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English",
    // Errors
    EULA_ERROR: "请先接受此 EULA 才能使用 OpenXT。如果取消，OpenXT 将关闭。",
    KEYBOARD_ERROR: "请选择一种键盘布局。",
    SET_SYSTEM_PASSWORD: "OpenXT 需要系统密码。"
})
