({
    // Controls
    START: "启动",
    BACKGROUND_START: "安静启动",
    SHUT_DOWN: "关机",
    FORCE_SHUT_DOWN: "强制关机",
    LOGIN: "登录",
    DETAILS: "详细信息",
    DELETE: "删除",
    // Tooltips
    XC_TOOLS_NOT_INSTALLED: "<strong>OpenXT Tools 未安装</strong><br/><br/>双击 VM 操作系统中的 OpenXT Tools Virtual CD 可进行安装。",
    XC_TOOLS_OLD_VERSION: "<strong>OpenXT Tools 已过期</strong><br/><br/>双击 VM 操作系统中的 OpenXT Tools Virtual CD 可进行升级。",
    // Layout
    NAME_MASK: "名称: {0}",
    STATUS_MASK: "状态: {0}",
    SLOT_MASK: "切换程序键: Ctrl+{0}",
    // VM States
    VM_CREATED : "正在启动",
    VM_STOPPED : "关",
    VM_STOPPING : "正在停止",
    VM_REBOOTING : "正在重新启动",
    VM_REBOOTED : "已重新启动",
    VM_PAUSED : "开",
    VM_SUSPENDING : "正在进入休眠状态",
    VM_SUSPENDED : "休眠",
    VM_RUNNING : "开",
    VM_LOCKED : "已锁定",
    VM_ASLEEP : "睡眠",
    // XenConstants.DesktopStates
    PUBLISHING: "正在上载",
    BACKING_UP: "正在备份",
    DOWNLOADING: "正在下载",
    UPDATING: "正在更新",
    FORCE_UPDATING: "强制更新",
    READY: "已就绪",
    LOCKED: "已锁定",
    REMOTE_LOCKED: "已锁定",
    UNMANAGED: "未托管",
    // XenConstants.SyncOpStates
    PREPARING: "正在准备",
    PREPARATION_FAILED: "准备失败",
    TRANSFER_PENDING: "传输待定",
    COMPUTING_DIGEST: "正在计算校验和",
    TRANSFER_ACTIVE: "正在传输",
    TRANSFER_PAUSED: "已暂停",
    TRANSFER_FAILED: "失败",
    TRANSFER_NETINT_STALLED: "正在等待... 服务器无法访问",
    TRANSFER_ADMCTL_STALLED: "正在等待... 服务器正忙",
    INSTALLING_IMAGE: "正在安装映像",
    TRANSFER_FINISHED: "传输已完成",
    SHUTDOWN_REQUIRED: "需要关闭",
    CLEAN_SHUTDOWN_REQUIRED: "需要完全关闭",
    BACKGROUND_FAILED: "后台操作失败"
})
