({
    // Layout
    START: "启动",
    BACKGROUND_START: "安静启动",
    SHUT_DOWN: "关机",
    REBOOT: "重新启动",
    HIBERNATE: "休眠",
    SLEEP: "睡眠",
    FORCE_SHUT_DOWN: "强制关机",
    LOGIN: "登录",
    UPLOAD_VM: "上载 VM",
    BACKUP_NOW: "立即备份",
    CHECK_NOW: "立即检查",
    ADD_DEVICE: "添加设备",
    DELETE: "删除",
    DETAILS: "详细信息",
    PAUSE: "暂停",
    RESUME: "恢复",
    RETRY: "重试",
    CANCEL: "取消",
    GENERAL: "常规",
    DEVICES: "设备",
    DEVICE: "设备",
    NO_DEVICES: "未连接任何设备",
    OPTIONS: "选项",
    ACTIONS: "操作",
    ALWAYS_USE: "始终与此 VM 结合使用",
    DISCONNECT: "断开连接",
    SYNCHRONIZATION: "同步",
    HARDWARE: "硬件",
    ICON: "图标",
    ADVANCED: "高级",
    NAME: "名称:",
    VCPUS: "vCPU:",
    MEMORY: "内存(MB):",
    AUTOBOOT: "自动启动:",
    AUTOBOOT_TOOLTIP: "主机启动时启动此 VM。",
    POWER_BEHAVIOUR: "电源控制:",
    POWER_BEHAVIOUR_TOOLTIP: "VM 关机、休眠或睡眠时，主机设备将执行相同的操作。",
    POWER_BEHAVIOUR_ENABLED: "电源控制将对 VM 和主机产生影响",
    POWER_BEHAVIOUR_DISABLED: "电源控制将仅对 VM 产生影响",
    SWITCHER_KEY: "切换程序键:",
    TOOLS_CD: "Tools CD:",
    INSTALLED_TOOLS_MASK: "已安装: {0}",
    THREED_GFX: "三维图形:",
    TYPE: "类型:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 位",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 位",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 位",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 位",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 位(实验版本)",
    TYPE_UNKNOWN: "未知",
    DESCRIPTION: "说明:",
    REGISTERED_USER: "注册用户:",
    BACKUP_MODE: "备份模式:",
    BACKUP_NONE: "无",
    BACKUP_USER: "用户数据",
    BACKUP_ALL: "所有数据",
    BACKUP_SCHEDULE: "备份计划:",
    UPDATE_SCHEDULE: "更新计划:",
    LEASE_EXPIRATION: "租借期限:",
    SAVE_ACROSS_REBOOTS: "保存对重新启动所做的更改:",
    DESKTOP_NAME: "桌面名称:",
    CURRENT_VERSION: "当前版本:",
    BASE_VERSION: "父版本:",
    WIRELESS_NETWORK: "无线网络:",
    WIRED_NETWORK: "有线网络:",
    WIRED_NIC: "有线网络 MAC 地址:",
    DISK_SPACE: "磁盘空间:",
    ALLOW_OEM: "允许安装 Windows OEM 版:",
    EXPOSE_HARDWARE_INFO: "公开物理硬件信息:",
    DISPLAY_VM: "在切换程序栏中显示 VM:",
    AMT_PASSTHROUGH: "Intel AMT Passthrough:",
    OEM_ACPI_PASSTHROUGH: "公开物理 OEM 硬件:",
    BOOT_ORDER: "启动顺序:",
    EDIT: "编辑",
    SAVE: "保存",
    CLOSE: "关闭",
    MANAGED_ENABLED: "托管 VM",
    THREED_GRAPHICS_ENABLED: "已启用三维图形",
    PUBLISH_APP_ENABLED: "应用程序发布组件",
    ENABLED: "已启用",
    DISABLED: "已禁用",
    NONE: "无",
    INSTALLED_NONE: "未安装任何工具",
    NEVER: "从不",
    ATTACHED: "已连接",
    SHARED_WIRELESS: "共享无线网络",
    SHARED_3G: "共享 3G (实验网络)",
    BRIDGED: "桥接",
    SHARED: "共享",
    INTERNAL: "内部",
    BRIDGED_MASK: "在 {0} 上桥接",
    SHARED_MASK: "在 {0} 上共享",
    INTERNAL_MASK: "在 {0} 内部",
    POLICY_DISABLED: "已被策略禁用",
    CHANGE_VERSION: "更改版本",
    NAME_VALERROR: "名称为必填项，且不得超过 60 个字符，可以包含字母、数字、空格以及某些标点符号(包括下划线、破折号、括号、句号、省略号和逗号)。",
    DESCRIPTION_VALERROR: "“说明”部分不应超过 200 个字符，可以包含字母、数字、空格以及某些标点符号(包括下划线、破折号、括号、句号、省略号和逗号)。",
    MEMORY_MASK: "{0:n}",
    SYSTEM_MEMORY_MASK: "总大小: {0:n}，可用大小: {1:n}",
    DISK_SPACE_MASK: "专用: {0}，共享: {1}",
    BACKUP_FREQUENCY_MASK: "{0:n} 小时",
    UPDATE_FREQUENCY_MASK: "{0:n} 分钟",
    LEASE_EXPIRATION_MASK: "{0:n} 天",
    BACKUP_LAST_MASK: "上次备份时间: {0:y-M-d H:mm} (UTC)",
    UPDATE_LAST_MASK: "上次更新时间: {0:y-M-d H:mm} (UTC)",
    BACKUP_SCHEDULE_MASK: "下次备份时间: {0:y-M-d H:mm} (UTC)",
    UPDATE_SCHEDULE_MASK: "下次更新检查时间: {0:y-M-d H:mm} (UTC)",
    LEASE_SCHEDULE_MASK: "下次租借时间: {0:y-M-d H:mm} (UTC)",
    BACKUP_LAST_MASK_1: "上次备份时间为 {0:n} 小时 {1:n} 分钟之前",
    UPDATE_LAST_MASK_1: "上次更新时间为 {0:n} 小时 {1:n} 分钟之前",
    BACKUP_NEXT_MASK: "下次备份于 {0:n} 小时 {1:n} 分钟后进行",
    UPDATE_NEXT_MASK: "下次更新检查于 {0:n} 小时 {1:n} 分钟后进行",
    LEASE_NEXT_MASK: "下次租借于 {0:n} 天 {1:n} 小时后进行",
    NETWORK_INFORMATION: "<strong>桥接</strong>网络可将 VM 直接连接到外部网络。<br/><strong>共享</strong>网络可对所有 VM 重复使用一个网络 IP 地址。<br/><strong>内部</strong>网络未连接到任何外部网络。",
    TRANSFER: "传输",
    TRANSFER_STATE: "状态:",
    TRANSFER_PROGRESS: "进度:",
    TRANSFER_SPEED_MASK: "{0:f} MB/s",
    SWITCHER_KEY_MASK: "Ctrl+{0}",
    SWITCHER_DROPDWON_MASK: " ({0})",
    THIS_VM: "此 VM",
    CD_DRIVE: "CD 驱动器",
    HARD_DRIVE: "硬盘驱动器",
    NETWORK: "网络",
    BOOT_TITLE: "添加一个启动选项...",
    HDX_TOOLTIP: "系统中只有一台虚拟机每次在运行时可以提供此功能。要启动此功能，必须关闭该虚拟机，并且该虚拟机必须已安装 OpenXT Tools 和 Intel 视频驱动程序。",
    MEMORY_TOOLTIP: "如果虚拟机处于休眠状态，则无法修改此功能。",
    VCPU_TOOLTIP: "如果虚拟机处于休眠状态，则无法修改此功能。",
    DISK_SPACE_TOOLTIP: "专用: 仅由此虚拟机使用的磁盘空间量。<br/>共享: 与系统中的其他虚拟机共享的磁盘空间量。",
    AMT_PT_TOOLTIP: "启用 Intel Active Management Technology (AMT) Management Engine (ME) 可提供基于硬件的网络管理功能，允许用户出于管理目的对 OpenXT 设备进行带外访问。只有一台 VM 可以启用此功能。",
    ACPI_PT_TOOLTIP: "向 VM 公开主机 ACPI SLIC 表以解除 Windows OEM 版的锁定。",
    SMBIOS_PT_TOOLTIP: "向 VM 公开用于描述主机硬件的 SMBIOS 记录类型而非 OpenXT 提供的记录类型。",
    OEM_ACPI_PT_TOOLTIP: "直接向 VM 公开 OEM 硬件。只有一台 VM 能够启用此功能。",
    POWER: "电源",
    COMMUNICATION: "无缝应用程序支持:",
    COMMUNICATION_TOOLTIP: "控制虚拟机防火墙设置，以便无缝应用程序能够正确运行。",
    ADVANCED_WARNING: "此部分面向高级功能，仅应在您了解其对系统所产生影响的前提下才能进行修改。",
    INTEL_AMT: "Intel AMT ME Pass-through 在重新启动 OpenXT 后才能生效。",
    MEMORY_CHANGE: "如果下一个要启动的是虚拟机，则内存将发生变化。",
    BACKUP_VM: "备份 VM",
    VM_UPDATE_CHECK: "检查 VM 更新",
    DELETE_VM_HEADER: "删除虚拟机",
    DELETE_VM: "是否确实要删除名为“{0}”的虚拟机?",
    ACCEPT_DELETE: "是，删除",
    XEN_MGR_DELETE: "删除 VM",
    USB_UNASSIGN: "此 USB 设备当前正由此 VM 使用。取消选择此设备会强制从此 VM 中将其删除，且可能会导致数据丢失。可以通过从其他 VM 操作系统内部弹出此设备来将其彻底删除。",
    UPLOAD_VM_STATUS: "仅在虚拟机处于关闭状态时才能进行上载",
    ADD_DEVICE_STATUS: "仅在虚拟机处于启动状态且已安装 OpenXT Tools 时才能连接设备",
    DELETE_VM_STATUS: "仅在虚拟机处于关闭或休眠状态时才能将其删除",
    FORCE_UPDATE: "强制更新此 VM 时出错",
    USB_DISABLED: "设备管理功能已对此 VM 禁用，无法添加设备"
})
