({
    // Notifications
    SAFE_GRAPHICS_MODE: "セーフ グラフィック モード",
    AUTH_FOR_AUTO_START: "自動起動時に認証を必要とする仮想マシンがあります。Ctrl + Alt + BackSpace を押して、セキュア認証を有効にします。",
    AUTH_START: "Ctrl + Alt + BackSpace を押して、セキュア認証を有効にします。",
    CTRL_SWITCH: "この画面に戻るには、次のショートカット キーを使用します:<div class='ctrlText'><span class='ctrlButton'>Ctrl</span> + <span class='ctrlButton'>0</span></div>",
    SEVERAL_VMS: "OpenXT ツールをインストールせずに複数の仮想マシンを実行すると、システム パフォーマンスが低下します。可能なら、OpenXT ツールをインストールしてください。",
    // Alerts
    LOW_SPACE_WARNING: "ディスク領域が少なくなってきています。現在、{0}% の空きがあります。",
    LOW_SPACE_TOOLTIP: "<strong>ディスク領域が少なくなってきています。</strong><br/><br/>現在、{0}% の空きがあります。",
    // Errors
    AJAX_FAILED: "AJAX 要求に失敗しました\r\nid: {0}; メソッド: {1}",
    UNEXPECTED_RESULT: "インターフェイスに対する signalRegister からの予期しない結果 ",
    SIGNAL_ERROR: "シグナル受信エラー; キュー: {0}",
    UNEXPECTED_RCV_RESULT: "receiveSignals からの予期しない結果",
    SERVICE_NOT_RUNNING: "{0} サービスが実行されていません。",
    XT_BED_NOT_RUNNING_ACTION: "Synchronizer デーモンが実行されてないため、この操作を完了できません。",
    XT_VERSION_MISMATCH_INFO: "Synchronizer に接続できません。'{0}'  サーバーは '{1}' クライアントと互換性がありません。",
    // XenConstants.ToolstackCodes
    NOT_ENOUGH_FREE_MEMORY: "要求に対して使用できる十分な空きメモリがありません",
    VM_BAD_STATE: "仮想マシンが予期しない状態になっています",
    VM_UNEXPECTED_SHUTDOWN_REASON: "シャットダウンの理由が予期したものと一致しませんでした",
    VM_NOT_SHUTDOWN: "仮想マシンはシャットダウンしていませんでした",
    VM_ALREADY_CREATED: "仮想マシンが既に作成されています",
    VT_MISSING: "仮想マシンを使用する前に、ハードウェア仮想化を有効にする必要がります。BIOS 設定をチェックしてください。",
    VM_TAP_MOUNT_FAILURE: "準備状態になってないため、仮想マシンを開始できませんでした。<br/>これは、他の処理がそれを更新しているためである可能性があります。数分後に、もう一度試してみてください。",
    HDX_AUTOSTART_MULTIPLE: "１ つ以上の VM 上で HDX および自動開始を同時にアクティブにできません。",
    VM_HIBERNATE_FAILED: "仮想マシンを休止状態にできませんでした",
    VM_EDIT_DISABLED: "この VM のアクティブ ポリシーにより、プロパティの編集は無効になっています",
    NO_SUCH_DEVICE: "非同種のデバイス",
    VM_CANNOT_DELETE_RUNNING: "実行中に VM を削除できません",
    VM_COUNT_HIGH: "仮想マシンが多すぎます",
    DISK_NOT_EXIST: "非同種のディスク",
    INCORRECT_DISK_TYPE: "正しくないディスクの種類",
    INCORRECT_DEVICE_TYPE: "正しくないデバイスの種類",
    HDX_CHANGE_WHILE_RUNNING: "VM の実行中に HDX をオンまたはオフにできません",
    HDX_ENABLE_NO_TOOLS: "OpenXT ツールをインストールせずに HDX をオンにできません",
    HDX_NO_VTD: "VT-d が有効でないため、HDX がある VM を開始できません",
    DISK_DEVICE_EXISTS: "指定のディスクを追加できません。デバイスは既に存在します",
    TOOLS_REQUIRED: "この操作を実行するには、VM 上に OpenXT ツールをインストールする必要があります",
    PROPERTY_READ_ONLY: "プロパティは読み取り専用です",
    PROPERTY_WRITE_ONLY: "プロパティは書き込み専用です",
    NO_DIAGNOSTICS: "現在、診断情報を収集していません",
    INCORRECT_DISK_HASH: "ディスク ハッシュは一致しません",
    TOO_MANY_HDX: "VM を開始できません。既に実行中の HDX がある VM が多すぎます",
    VM_PASSTHRU_RUNNING: "VM を開始できません。AMT パススルーが有効な VM が既に実行中です",
    POLICY_SUPPRESSED_ACTION: "この操作はアクティブなポリシー設定により無効となっています",
    VM_HIBERNATE_CHANGE: "休止状態の間にこの VM のプロパティを変更できません",
    NIC_NOT_FOUND: "非同種のネットワーク インターフェイス",
    IO_ERROR: "IO エラー",
    VM_RESUME_FAILED: "スリープ状態から VM を再開できませんでした",
    OPERATION_SUPPRESSED_ACTION: "他のバックグラウンド操作が処理中のため、要求した操作を完了できませんでした",
    VM_NO_RPC_AGENT: "VM はRPC エージェントを使用するように構成されいません",
    VM_SLEEP_TIMEOUT: "VM がスリープになるのを待機中にタイムアウトしました",
    VM_HIBERNATE_TIMEOUT: "VM が休止状態になるのを待機中にタイムアウトしました",
    VM_SHUTDOWN_TIMEOUT: "VM がシャットダウンするのを待機中にタイムアウトしました",
    DEVICE_ATTACHED_ELSEWHERE: "デバイスは現在他の VM にパススルーされています",
    ADAPTER_NOT_SECONDARY: "セカンダリ アダプターのため、グラフィック カードはパススルーできません",
    NETWORK_NOT_RUNNNING: "ネットワーク バックエンド ドメインは実行していません",
    OEM_ACPI_RUNNING: "VM を開始できません。OEM－ACPI 機能があるもう一方の VM が既に実行中です",
    UNKNOWN_GPU: "不明な GPU",
    VM_TXT_SLEEP_DISABLED: "インテル TXT をメジャーメントに基づいて立ち上げている間は、ホスト スリープは無効です",
    UNSUPPORTED_LANGUAGE: "サポートされていない言語",
    RULE_PARSE_ERROR: "規則解析エラー",
    // XenConstants.UpdateCodes
    UPDATE_INTERNAL_ERROR: "内部エラーが発生しました",
    UPDATE_DOWNLOAD_FAILED: "ダウンロードに失敗しました",
    UPDATE_DOWNLOAD_CANCELLED: "ダウンロードがキャンセルされました",
    UPDATE_MISSING_METADATA: "メタデータがありませんでした",
    UPDATE_MALFORMED_METADATA: "メタデータの形式が不正でした",
    UPDATE_UPDATE_NOT_APPLICABLE: "更新を適用できません",
    UPDATE_ALREADY_RUNNING: "更新を既に実行中です",
    UPDATE_VM_RUNNING: "ゲスト VM を実行している間は更新を適用できません。\n実行中のすべての VM をシャットダウンしてもう一度試してください。",
    UPDATE_CORRUPT_FILE: "ファイルが破損しました",
    UPDATE_UP_TO_DATE: "既に最新版です",
    UPDATE_FILE_NOT_FOUND: "更新リポジトリが見つかりません。URL をチェックしてください",
    UPDATE_CANNOT_RESOLVE_HOST: "ホストを解決できません。URL をチェックしてください",
    UPDATE_CANNOT_CONNECT_HOST: "ホストに接続できません。URL をチェックしてください",
    UPDATE_SIGNATURE_FAILED: "更新署名の検証に失敗しました",
    UPDATE_POLICY_DISABLED: "ポリシーにより更新が無効になっています",
    // XenClient.Resource.RegisterStatus
    NETWORK_DISCONNECTED_2: "ネットワーク接続性がありません",
    SERVER_UNREACHABLE: "サーバーに接続できません。URL をチェックしてください。",
    CERT_CA_MISSING: "OpenXT はこのデバイスを登録できませんでした。Synchronizer 構成をチェックし、また OpenXT が適性にインストールされているかチェックしてください: ",
    CERT_VERIFY_FAILED: "認証できないサーバー:",
    CERT_GENERIC: "一般エラーが発生しました",
    CERT_TRUST_ROOT_CERT_FAILED: "ルート証明書の信頼に失敗しました",
    CERT_AUTH_CODE_MISMATCH: "認証コードは証明書から生成されたものと一致しません",
    CERT_GET_CHAIN_FAILED: "サーバーから証明書チェーンを取得できませんでした",
    HOSTNAME_INVALID: "登録した無効なホスト名",
    CERT_NO_CN: "サーバー証明書内の非共通の名前",
    CERT_HOSTNAME_CN_MISMATCH: "証明書内の共通名は登録したホスト名と一致しません。証明書内の共通名は次の通りです: {0}"
})
