({
    // Layout
    CREATE_FROM_MEDIA: "インストール ディスクから作成",
    CREATE_VM_WIZARD_NAME_HEADER: "名前と種類",
    TYPE_LABEL: "種類:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 ビット",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 ビット",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 ビット",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 ビット",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 ビット (試験的)",
    TYPE_UNKNOWN: "不明",
    VM_NAME_LABEL: "VM 名:",
    DESCRIPTION_LABEL: "説明:",
    CREATE_VM_WIZARD_ICON_HEADER: "アイコン",
    CREATE_VM_WIZARD_MEMORY_HEADER: "メモリと CPU",
    CREATE_VM_WIZARD_MEMORY_ALT_HEADER: "メモリ",
    MEMORY_LABEL: "メモリ:",
    MB_INDICATOR_TEXT: "(MB)",
    GB_INDICATOR_TEXT: "(GB)",
    TOTAL_MEM_MASK: "メモリ合計: {0:n}",
    FREE_MEM_MASK: "空きメモリ: {0:n}",
    VCPUS_LABEL: "vCPU:",
    CREATE_VM_WIZARD_STORAGE_HEADER: "ストレージとネットワーク",
    STORAGE_LABEL: "仮想ディスク サイズ:",
    WIRELESS_LABEL: "ワイヤレス ネットワーク:",
    NETWORK_WIRELESS_OPTION: "共有ネットワーク",
    NETWORK_3G_OPTION: "共有 3G (試験的)",
    WIRED_LABEL: "ワイヤード ネットワーク",
    NETWORK_BRIDGED_OPTION: "ブリッジ",
    NETWORK_SHARED_OPTION: "共有",
    NETWORK_INTERNAL_OPTION: "内部",
    NETWORK_BRIDGED_MASK: "{0} でブリッジ",
    NETWORK_SHARED_MASK: "{0} で共有",
    NETWORK_INTERNAL_MASK: "{0} 上の内部",
    WIRED_NETWORK_INFORMATION: "<strong>ブリッジ</strong> ネットワークは VM を直接外部ネットワークに接続します。<br/><strong>共有</strong>ネットワークはすべての VM で単一のネットワーク IP アドレスを再使用します。<br/><strong>内部</strong>ネットワークは外部ネットワークに接続しません。",
    CREATE_VM_WIZARD_FINISH_HEADER: "完了",
    CREATE_VM_WIZARD_FINISH_PARA1: "OS インストール ディスクから VM を作成する準備が整いました。",
    AUTOSTART_LABEL: "VM を開始して OS をインストールする",
    AUTOSTART_OFF_LABEL: "VM を作成して OS を後でインストールする",
    CREATE_VM_WIZARD_FINISH_PARA2: "OS をインストールした後、<strong>仮想 OpenXT ツール CD</strong> をダブルクリックして OpenXT ツールをインストールしてください。",
    // Errors
    NAME_VALERROR: "名前を入力してください。60 文字以内の文字、数字、スペース、句読点 (アンダースコア、ダッシュ、括弧、ピリオド、アポストロフィ、およびカンマを含む) を使用できます。",
    DESCRIPTION_VALERROR: "説明として、200 文字以内の数字、スペース、句読点 (アンダースコア、ダッシュ、括弧、ピリオド、アポストロフィ、およびカンマを含む) を使用できます。",
    VM_ERRORS: "仮想マシンが作成されましたが、エラーがあります。新しい仮想マシンの設定をチェックしてください。"
})
