({
    // Layout
    SYS_INFO_HEADER: "システム設定",
    SYS_INFO_WALLPAPER_TITLE: "壁紙",
    SYS_INFO_POWER_TITLE: "電源",
    SYS_INFO_TOUCHPAD_TITLE: "インターフェイス",
    SYS_INFO_TRANSMITTER_TITLE: "Synchronizer",
    SYS_INFO_AUTH_TITLE: "ログオン",
    SYS_INFO_SOFTWARE_TITLE: "ソフトウェア",
    SYS_INFO_HARDWARE_TITLE: "ハードウェア",
    SYS_INFO_NETWORK_TITLE: "ネットワーク",
    STATUS_REPORT_HEADER: "状態レポート",
    WALLPAPER_HEADER: "使用する壁紙のイメージをクリックしてください",
    VENDOR_LABEL: "ベンダー:",
    MODEL_LABEL: "モデル:",
    BIOS_REV_LABEL: "BIOS リビジョン:",
    TOTAL_MEM_LABEL: "合計物理メモリ:",
    MEMORY_MASK: "{0:n} MB",
    FREE_MEM_LABEL: "空き物理メモリ:",
    FREE_STORAGE_LABEL: "空きディスク領域:",
    TOTAL_STORAGE_LABEL: "全ディスク領域:",
    DISK_SPACE_MASK: "{0:n} MB",
    CPU_MODEL_LABEL: "物理 CPU モデル:",
    GPU_MODEL_LABEL: "物理 GPU モデル:",
    ETH0_MAC_ADDRESS_LABEL: "ワイヤード MAC アドレス:",
    ETH0_MODEL_LABEL: "ワイヤード モデル:",
    HOST_AMT_PT_LABEL: "MAC アドレス パススルー:",
    ON_TEXT: "有効",
    OFF_TEXT: "無効",
    WIRELESS_MAC_ADDRESS_LABEL: "ワイヤレス MAC アドレス:",
    WIRELESS_MODEL_LABEL: "ワイヤレス モデル:",
    XENCLIENT_VERSION_LABEL: "OpenXT のバージョン:",
    XENCLIENT_VERSION_MASK: "{0} ({1} ブランチ)",
    XENCLIENT_BUILD_LABEL: "OpenXT ビルド:",
    XENCLIENT_BUILD_MASK: "{0} ({1:y年 MMMM d日})",
    TOOLS_VERSION_LABEL: "ツール CD のバージョン:",
    UPDATE_TITLE: "ソフトウェア更新",
    UPDATE_TOOLTIP: "OpenXT を更新するための URL は、管理者により提供されます",
    UPDATE_ACTION: "更新のチェック",
    CANCEL_DOWNLOAD_ACTION: "ダウンロードのキャンセル",
    DISCARD_UPDATE_ACTION: "更新の破棄",
    UPDATE_SHUTDOWN: "ダウンロードに成功しました。更新を適用するにはデバイスを再起動してください。",
    LID_CLOSE_LABEL: "カバーを閉じたときの操作",
    LID_CLOSE_AC_POWER_LABEL: "電源に接続:",
    SLEEP_ALL_OPTION: "システム全体をスリープ状態にする",
    DO_NOTHING_OPTION: "何もしない",
    LID_CLOSE_BATTERY_LABEL: "バッテリー駆動:",
    BRIGHTNESS_LABEL: "画面の明るさ",
    TOUCHPAD_OPTIONS: "タッチパッド オプション",
    TAP_TO_CLICK_LABEL: "タッチパッド タップでクリック:",
    SCROLLING_LABEL: "タッチパッド スクロール:",
    SPEED_LABEL: "タッチパッド速度",
    SLOW: "遅い",
    FAST: "速い",
    LEFT: "左",
    RIGHT: "右",
    POINTER_TRAIL: "マウス ポインター軌跡",
    NONE_TEXT: "なし",
    SHORT_TEXT: "短く",
    LONG_TEXT: "長く",
    KEYBOARD_LAYOUT: "キーボード レイアウト",
    LANGUAGE_HEADER: "言語",
    TRANSMITTER_STATE_LABEL: "状態:",
    TRANSMITTER_STATE_UNREGISTERED: "未登録",
    TRANSMITTER_STATE_PREREGISTERED: "事前登録",
    TRANSMITTER_STATE_CONNECTED: "接続",
    TRANSMITTER_STATE_DISCONNECTED: "切断",
    TRANSMITTER_URL_LABEL: "Synchronizer ホスト名:",
    TRANSMITTER_VERSION_LABEL: "バージョン:",
    TRANSMITTER_BUILD_LABEL: "ビルド:",
    TRANSMITTER_LOGGEDIN_LABEL: "登録ユーザー:",
    TRANSMITTER_HEADER: "新しい VM のダウンロードおよびバックアップを行うため、Synchronizer に登録します。",
    REGISTER_ACTION: "登録",
    CONNECT_ACTION: "Synchronizer に接続",
    AUTH_SET_PASSWORD_TEXT: "ローカル認証を有効にするためのパスワードを設定します。",
    SET_PASSWORD_ACTION: "パスワードを設定",
    CHANGE_PASSWORD_ACTION: "パスワードを変更",
    AUTH_REQUIRED_TEXT: "スタートアップ時のパスワード:",
    AUTH_SET_TIMEOUT_TEXT: "画面ロック タイムアウト:",
    STATUS_REPORT: "状態レポートを作成すると、このデバイスから診断情報が収集されて単一のファイルにパッケージ化されます。<br/><br/>このレポートは Ctrl+Alt+R キーを押していつでも作成できます。",
    CREATE_STATUS_REPORT: "状態レポートを作成",
    STATUS_SERVER_HEADER: "レポートのダウンロード",
    STATUS_SERVER: "状態レポートのダウンロードについては、OpenXT ユーザー ガイドのトラブルシューティングについての説明を参照してください。",
    BEGIN_STATUS_SERVER: "レポートをダウンロードできるようにする",
    STATUS_SERVER_INFO: "コンピューター ネットワークがセキュリティで保護され、管理者により許可されている場合にのみ、レポートをダウンロードできるようにしてください。",
    CLOSE_ACTION: "閉じる",
    SAVE_ACTION: "保存",
    SYS_INFO_DISPLAY_TITLE: "ディスプレイ",
    SEAMLESS_HEADER: "マウス切り替え",
    SWITCHER_LABEL: "マウス切り替え",
    RESISTANCE_LABEL: "切り替え時のしきい値:",
    KEYBOARD_LABEL: "キーボードも切り替える:",
    ADAPTER_LABEL: "シームレスにマウスを動かすためのディスプレイ アダプターの順番を設定します。",
    LANGUAGE_WARNING: "言語設定が変更されました。ユーザー インターフェイスを再起動する必要があります。",
    // Other
    AUTH_MANAGED_TEXT: "Synchronizer 資格情報を使ってログオンしてください。",
    MINUTE: "分",
    MINUTES: "分",
    NEVER: "ロックしない",
    ALREADY_CONNECTED: "Synchronizer には既に接続しています。",
    UPDATE_HEADER: "ソフトウェア更新",
    CANNOT_UPGRADE: "インストール済みの OpenXT バージョン: {0}\n最新の OpenXT バージョン: {1}\n\nこのバージョンの OpenXT に更新できません。",
    CAN_UPGRADE: "インストール済みの OpenXT バージョン: {0}\n最新の OpenXT バージョン: {1}\n\n新しいバージョンの OpenXT が検出されました。この更新をダウンロードしますか?\n\nこれをシステムに適用する方法について詳しくは、ドキュメントを参照してください。",
    UP_TO_DATE: "インストール済みの OpenXT バージョン: {0}\n最新の OpenXT バージョン: {1}\n\n最新のバージョンの OpenXT を実行していますが、もう一度ダウンロードおよび適用してこれを更新することができます。\n\nこれをシステムに適用する方法について詳しくは、ドキュメントを参照してください。",
    START_DOWNLOAD_ACTION: "ダウンロード",
    SERVE_REPORT: "ほかのマシンでは、次の場所からレポートをダウンロードできます:\n\n{0}\n\nこのマシン上の VM では、次の場所からダウンロードできます:\n\n{1}",
    STOP_STATUS_SERVER: "レポートをダウンロードできなくする",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "スイス",
    KEYBOARD_LAYOUT_CN: "中国",
    KEYBOARD_LAYOUT_FR: "フランス",
    KEYBOARD_LAYOUT_DE: "ドイツ",
    KEYBOARD_LAYOUT_IT: "イタリア",
    KEYBOARD_LAYOUT_JP: "日本",
    KEYBOARD_LAYOUT_ES: "スペイン",
    KEYBOARD_LAYOUT_GB: "英国",
    KEYBOARD_LAYOUT_US: "米国",
    KEYBOARD_LAYOUT_RU: "Russia",
    KEYBOARD_LAYOUT_CA: "Canada",
    KEYBOARD_LAYOUT_BR: "Brazil",
    KEYBOARD_LAYOUT_NL: "Netherlands",
    KEYBOARD_LAYOUT_NO: "Norway",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Korea",
    KEYBOARD_LAYOUT_BE: "Belgium",
    KEYBOARD_LAYOUT_DK: "Denmark",
    KEYBOARD_LAYOUT_IN: "India",
    KEYBOARD_LAYOUT_SE: "Sweden",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English"
})
