({
    // Layout
    DEFERRED_INSTALL_TITLE: "OpenXT にようこそ",
    EULA_HEADER: "エンド ユーザー ライセンス契約",
    KEYBOARD_HEADER: "キーボード レイアウト",
    KEYBOARD_INSTR: "キーボード レイアウトを選択してください。",
    LANGUAGE_HEADER: "言語",
    LANGUAGE_INSTR: "言語を選択してください。",
    ROOT_PASSWORD_HEADER: "システム パスワード",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "スイス",
    KEYBOARD_LAYOUT_CN: "中国",
    KEYBOARD_LAYOUT_FR: "フランス",
    KEYBOARD_LAYOUT_DE: "ドイツ",
    KEYBOARD_LAYOUT_IT: "イタリア",
    KEYBOARD_LAYOUT_JP: "日本",
    KEYBOARD_LAYOUT_ES: "スペイン",
    KEYBOARD_LAYOUT_GB: "英国",
    KEYBOARD_LAYOUT_US: "米国",
    KEYBOARD_LAYOUT_RU: "Russia",
    KEYBOARD_LAYOUT_CA: "Canada",
    KEYBOARD_LAYOUT_BR: "Brazil",
    KEYBOARD_LAYOUT_NL: "Netherlands",
    KEYBOARD_LAYOUT_NO: "Norway",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Korea",
    KEYBOARD_LAYOUT_BE: "Belgium",
    KEYBOARD_LAYOUT_DK: "Denmark",
    KEYBOARD_LAYOUT_IN: "India",
    KEYBOARD_LAYOUT_SE: "Sweden",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English",
    // Errors
    EULA_ERROR: "OpenXT を使用するには、このエンド ユーザー ライセンス契約を承認してください。キャンセルを実行すると、OpenXT はシャットダウンします。",
    KEYBOARD_ERROR: "キーボード レイアウトを選択してください。",
    SET_SYSTEM_PASSWORD: "OpenXT はシステム パスワードを必要とします。"
})
