({
    // Controls
    START: "開始",
    BACKGROUND_START: "自動開始",
    SHUT_DOWN: "シャットダウン",
    FORCE_SHUT_DOWN: "強制終了",
    LOGIN: "ログオン",
    DETAILS: "詳細",
    DELETE: "削除",
    // Tooltips
    XC_TOOLS_NOT_INSTALLED: "<strong>OpenXT ツールがインストールされていません。</strong><br/><br/>VM OS 内で OpenXT ツールの仮想 CD をダブルクリックしてインストールしてください。",
    XC_TOOLS_OLD_VERSION: "<strong>OpenXT ツールが最新ではありません。</strong><br/><br/>VM OS 内で OpenXT ツールの仮想 CD をダブルクリックしてアップグレードしてください。",
    // Layout
    NAME_MASK: "名前: {0}",
    STATUS_MASK: "状態: {0}",
    SLOT_MASK: "スイッチャー キー: Ctrl + {0}",
    // VM States
    VM_CREATED : "起動中",
    VM_STOPPED : "オフ",
    VM_STOPPING : "停止中",
    VM_REBOOTING : "再起動中",
    VM_REBOOTED : "再起動済",
    VM_PAUSED : "オン",
    VM_SUSPENDING : "休止中",
    VM_SUSPENDED : "休止状態",
    VM_RUNNING : "オン",
    VM_LOCKED : "ロック",
    VM_ASLEEP : "スリープ状態",
    // XenConstants.DesktopStates
    PUBLISHING: "アップロード",
    BACKING_UP: "バックアップ中",
    DOWNLOADING: "ダウンロード中",
    UPDATING: "更新中",
    FORCE_UPDATING: "強制更新中",
    READY: "準備完了",
    LOCKED: "ロック",
    REMOTE_LOCKED: "ロック",
    UNMANAGED: "非管理",
    // XenConstants.SyncOpStates
    PREPARING: "準備中",
    PREPARATION_FAILED: "準備に失敗しました",
    TRANSFER_PENDING: "転送保留中",
    COMPUTING_DIGEST: "チェックサムの計算",
    TRANSFER_ACTIVE: "転送中",
    TRANSFER_PAUSED: "一時停止中",
    TRANSFER_FAILED: "失敗",
    TRANSFER_NETINT_STALLED: "待機中... サーバーに到達できません",
    TRANSFER_ADMCTL_STALLED: "待機中... サーバーがビジー状態です",
    INSTALLING_IMAGE: "イメージのインストール",
    TRANSFER_FINISHED: "転送完了",
    SHUTDOWN_REQUIRED: "シャットダウンの要求",
    CLEAN_SHUTDOWN_REQUIRED: "クリーン シャットダウンの要求",
    BACKGROUND_FAILED: "バックグランド操作に失敗しました"
})
