({
    // Layout
    START: "開始",
    BACKGROUND_START: "自動開始",
    SHUT_DOWN: "シャットダウン",
    REBOOT: "再起動",
    HIBERNATE: "休止状態",
    SLEEP: "スリープ",
    FORCE_SHUT_DOWN: "強制終了",
    LOGIN: "ログオン",
    UPLOAD_VM: "VM をアップロード",
    BACKUP_NOW: "すぐにバックアップする",
    CHECK_NOW: "すぐにチェックする",
    ADD_DEVICE: "デバイスを追加",
    DELETE: "削除",
    DETAILS: "詳細",
    PAUSE: "一時停止",
    RESUME: "再開",
    RETRY: "再試行",
    CANCEL: "キャンセル",
    GENERAL: "全般の設定",
    DEVICES: "デバイス",
    DEVICE: "デバイス",
    NO_DEVICES: "接続されたデバイスはありません",
    OPTIONS: "オプション",
    ACTIONS: "操作",
    ALWAYS_USE: "この VM で常に使用する",
    DISCONNECT: "切断",
    SYNCHRONIZATION: "同期",
    HARDWARE: "ハードウェア",
    ICON: "アイコン",
    ADVANCED: "上級設定",
    NAME: "名前:",
    VCPUS: "vCPU:",
    MEMORY: "メモリ (MB):",
    AUTOBOOT: "自動起動:",
    AUTOBOOT_TOOLTIP: "ホスト起動時にこの VM を起動します。",
    POWER_BEHAVIOUR: "電源制御:",
    POWER_BEHAVIOUR_TOOLTIP: "VM をシャットダウン、休止状態、またはスリープすると、その操作がホスト デバイスにも実行されます。",
    POWER_BEHAVIOUR_ENABLED: "電源操作を VM およびホストに適用する",
    POWER_BEHAVIOUR_DISABLED: "電源操作を VM にのみ適用する",
    SWITCHER_KEY: "スイッチャー キー:",
    TOOLS_CD: "ツール CD:",
    INSTALLED_TOOLS_MASK: "インストール済み: {0}",
    THREED_GFX: "3D グラフィック:",
    TYPE: "種類:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 32 ビット",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 32 ビット",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 32 ビット",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 64 ビット",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 32 ビット (試験的)",
    TYPE_UNKNOWN: "不明",
    DESCRIPTION: "説明:",
    REGISTERED_USER: "登録ユーザー:",
    BACKUP_MODE: "バックアップ モード:",
    BACKUP_NONE: "なし",
    BACKUP_USER: "ユーザー データ",
    BACKUP_ALL: "すべてのデータ",
    BACKUP_SCHEDULE: "バックアップ スケジュール:",
    UPDATE_SCHEDULE: "更新スケジュール:",
    LEASE_EXPIRATION: "リース有効期限:",
    SAVE_ACROSS_REBOOTS: "再起動用に変更を保存:",
    DESKTOP_NAME: "デスクトップ名:",
    CURRENT_VERSION: "現在のバージョン:",
    BASE_VERSION: "上位バージョン:",
    WIRELESS_NETWORK: "ワイヤレス ネットワーク:",
    WIRED_NETWORK: "ワイヤード ネットワーク:",
    WIRED_NIC: "ワイヤード MAC アドレス:",
    DISK_SPACE: "ディスク領域:",
    ALLOW_OEM: "OEM Windows インストールの許可:",
    EXPOSE_HARDWARE_INFO: "物理ハードウェア情報の表示:",
    DISPLAY_VM: "スイッチャー バーでの VM の表示:",
    AMT_PASSTHROUGH: "Intel AMT パススルー:",
    OEM_ACPI_PASSTHROUGH: "物理 OEM ハードウェアの表示:",
    BOOT_ORDER: "起動順序:",
    EDIT: "編集",
    SAVE: "保存",
    CLOSE: "閉じる",
    MANAGED_ENABLED: "管理 VM",
    THREED_GRAPHICS_ENABLED: "3D グラフィック有効",
    PUBLISH_APP_ENABLED: "アプリケーションを公開",
    ENABLED: "有効",
    DISABLED: "無効",
    NONE: "なし",
    INSTALLED_NONE: "インストールされたツールなし",
    NEVER: "なし",
    ATTACHED: "付属",
    SHARED_WIRELESS: "共有ワイヤレス",
    SHARED_3G: "共有 3G (試験的)",
    BRIDGED: "ブリッジ",
    SHARED: "共有",
    INTERNAL: "内部",
    BRIDGED_MASK: "{0} でブリッジ",
    SHARED_MASK: "{0} で共有",
    INTERNAL_MASK: "{0} 上の内部",
    POLICY_DISABLED: "ポリシーにより無効",
    CHANGE_VERSION: "バーションを変更",
    NAME_VALERROR: "名前を入力してください。60 文字以内の文字、数字、スペース、句読点 (アンダースコア、ダッシュ、括弧、ピリオド、アポストロフィ、およびカンマを含む) を使用できます。",
    DESCRIPTION_VALERROR: "説明として、200 文字以内の数字、スペース、句読点 (アンダースコア、ダッシュ、括弧、ピリオド、アポストロフィ、およびカンマを含む) を使用できます。",
    MEMORY_MASK: "{0:n}",
    SYSTEM_MEMORY_MASK: "合計: {0:n}、空き: {1:n}",
    DISK_SPACE_MASK: "プライベート: {0}、共有: {1}",
    BACKUP_FREQUENCY_MASK: "{0:n} 時間",
    UPDATE_FREQUENCY_MASK: "{0:n} 分",
    LEASE_EXPIRATION_MASK: "{0:n} 日",
    BACKUP_LAST_MASK: "最終バックアップ {0:y年 MMMM d日 H:mm} (UTC)",
    UPDATE_LAST_MASK: "最終更新 {0:y年 MMMM d日 H:mm} (UTC)",
    BACKUP_SCHEDULE_MASK: "次のバックアップ {0:y年 MMMM d日 H:mm} (UTC)",
    UPDATE_SCHEDULE_MASK: "次回更新チェック {0:y年 MMMM d日 H:mm} (UTC)",
    LEASE_SCHEDULE_MASK: "次回 {0:y年 MMMM d日 H:mm} (UTC)",
    BACKUP_LAST_MASK_1: "最終バックアップは {0:n} 時間 {1:n} 分前",
    UPDATE_LAST_MASK_1: "最終更新は {0:n} 時間 {1:n} 分前",
    BACKUP_NEXT_MASK: "次のバックアップは {0:n} 時間 {1:n} 分後",
    UPDATE_NEXT_MASK: "次の更新チェックは {0:n} 時間 {1:n} 分後",
    LEASE_NEXT_MASK: "次回は {0:n} 日 {1:n} 時間後",
    NETWORK_INFORMATION: "<strong>ブリッジ</strong> ネットワークは VM を直接外部ネットワークに接続します。<br/><strong>共有</strong>ネットワークはすべての VM の単一のネットワーク IP アドレスを再使用します。<br/><strong>内部</strong>ネットワークは外部ネットワークには接続されません。",
    TRANSFER: "転送",
    TRANSFER_STATE: "状態:",
    TRANSFER_PROGRESS: "進行状況:",
    TRANSFER_SPEED_MASK: "{0:f} MB/秒",
    SWITCHER_KEY_MASK: "Ctrl + {0}",
    SWITCHER_DROPDWON_MASK: " ({0})",
    THIS_VM: "この VM",
    CD_DRIVE: "CD ドライブ",
    HARD_DRIVE: "ハード ドライブ",
    NETWORK: "ネットワーク",
    BOOT_TITLE: "起動オプションを追加...",
    HDX_TOOLTIP: "システム上の複数の仮想マシンで同時にこの機能を有効にすることはできません。この機能を有効にするには、仮想マシンがオフになっており、OpenXT ツールおよび Intel ビデオ ドライバーがインストール済みである必要があります。",
    MEMORY_TOOLTIP: "この機能は、休止状態の仮想マシンでは変更できません。",
    VCPU_TOOLTIP: "この機能は、休止状態の仮想マシンでは変更できません。",
    DISK_SPACE_TOOLTIP: "プライベート: この仮想マシンによってのみ使用されるディスク領域です。<br/>共有: システム上の他の仮想マシンと共有されるディスク領域です。",
    AMT_PT_TOOLTIP: "Intel Active Management Technology (AMT) Management Engine (ME) が有効になり、ハードウェア ベースのネットワーク管理が提供されます。これにより、OpenXT デバイスにアウトオブバンド (IP ネットワークを使わない) でアクセスして管理できます。この機能を有効にできるのは、1 つの VM だけです。",
    ACPI_PT_TOOLTIP: "ホスト ACPI SLIC テーブルを VM に公開して、Windows の OEM 版をアンロックします。",
    SMBIOS_PT_TOOLTIP: "OpenXT によるものではなく、ホスト ハードウェアを説明する SMBIOS レコードの種類を VM に公開します。",
    OEM_ACPI_PT_TOOLTIP: "OEM ハードウェアを直接 VM に公開します。この機能を有効にできるのは、1 つの VM だけです。",
    POWER: "電源",
    COMMUNICATION: "シームレス アプリケーション サポート:",
    COMMUNICATION_TOOLTIP: "シームレス アプリケーションが動作するように、仮想マシン ファイアウォール設定を制御します。",
    ADVANCED_WARNING: "このセクションの内容は上級機能を対象としています。この設定を変更するのは、それによるシステムに対しての影響を理解している場合に限ります。",
    INTEL_AMT: "Intel AMT パススルーの設定は、OpenXT を再起動するまでは適用されません。",
    MEMORY_CHANGE: "メモリの変更は仮想マシンを次に起動した際に適用されます。",
    BACKUP_VM: "VM をバックアップ",
    VM_UPDATE_CHECK: "VM 更新をチェック",
    DELETE_VM_HEADER: "仮想マシンを削除",
    DELETE_VM: "'{0}' という名前の仮想マシンを削除してもよろしいですか?",
    ACCEPT_DELETE: "はい、削除します",
    XEN_MGR_DELETE: "VM を削除",
    USB_UNASSIGN: "この USB デバイスは、現在この VM で使用中です。これを選択解除すると、この VM から強制的に削除されるためデータが損失することがあります。VM のオペレーティング システム内でこのデバイスを正しく削除してください。",
    UPLOAD_VM_STATUS: "アップロードするには、仮想マシンがオフになっている必要があります",
    ADD_DEVICE_STATUS: "デバイスを接続するには、仮想マシンがオンで OpenXT ツールがインストール済みである必要があります",
    DELETE_VM_STATUS: "仮想マシンを削除するには、仮想マシンがオフまたは休止状態である必要があります",
    FORCE_UPDATE: "VM の強制更新エラー",
    USB_DISABLED: "この VM ではデバイス管理が無効になっているため、デバイスを追加できません"
})
