({
    // Layout
    CREATE_FROM_MEDIA: "Crear con disco de instalación",
    CREATE_VM_WIZARD_NAME_HEADER: "Nombre y tipo",
    TYPE_LABEL: "Tipo:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 de 32 bits",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 de 32 bits",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 de 32 bits",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 de 64 bits",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 de 32 bits (experimental)",
    TYPE_UNKNOWN: "Desconocido",
    VM_NAME_LABEL: "Nombre de la VM:",
    DESCRIPTION_LABEL: "Descripción:",
    CREATE_VM_WIZARD_ICON_HEADER: "Icono",
    CREATE_VM_WIZARD_MEMORY_HEADER: "Memoria y CPU",
    CREATE_VM_WIZARD_MEMORY_ALT_HEADER: "Memoria",
    MEMORY_LABEL: "Memoria:",
    MB_INDICATOR_TEXT: "(MB)",
    GB_INDICATOR_TEXT: "(GB)",
    TOTAL_MEM_MASK: "Memoria total: {0:n}",
    FREE_MEM_MASK: "Memoria libre: {0:n}",
    VCPUS_LABEL: "CPU virtuales:",
    CREATE_VM_WIZARD_STORAGE_HEADER: "Almacenamiento y redes",
    STORAGE_LABEL: "Tamaño del disco virtual:",
    WIRELESS_LABEL: "Red inalámbrica:",
    NETWORK_WIRELESS_OPTION: "Inalámbrica compartida",
    NETWORK_3G_OPTION: "3G compartida (experimental)",
    WIRED_LABEL: "Red de cable:",
    NETWORK_BRIDGED_OPTION: "Con puente",
    NETWORK_SHARED_OPTION: "Compartida",
    NETWORK_INTERNAL_OPTION: "Interna",
    NETWORK_BRIDGED_MASK: "Con puente en {0}",
    NETWORK_SHARED_MASK: "Compartida en {0}",
    NETWORK_INTERNAL_MASK: "Interna en {0}",
    WIRED_NETWORK_INFORMATION: "Una red <strong>con puente</strong> conecta una VM directamente a la red externa.<br/>Una red <strong>compartida</strong> reutiliza una única dirección IP de red para todas las VM.<br/>La red <strong>interna</strong> no está conectada a ninguna red externa.",
    CREATE_VM_WIZARD_FINISH_HEADER: "Finalizar",
    CREATE_VM_WIZARD_FINISH_PARA1: "Ya está listo para crear una VM a partir del disco de instalación del sistema operativo.",
    AUTOSTART_LABEL: "Iniciar VM e instalar sistema operativo",
    AUTOSTART_OFF_LABEL: "Crear VM e instalar sistema operativo más tarde",
    CREATE_VM_WIZARD_FINISH_PARA2: "Después de instalar el sistema operativo, haga doble clic en el <strong>CD virtual de Herramientas de OpenXT</strong> para instalar las Herramientas de OpenXT.",
    // Errors
    NAME_VALERROR: "Hay que introducir un nombre. El nombre no puede tener más de 60 caracteres y puede contener letras, números, espacios y ciertos signos de puntuación (guiones bajos, guiones, corchetes, puntos, apóstrofes y comas).",
    DESCRIPTION_VALERROR: "La descripción no puede tener más de 200 caracteres y puede contener letras, números, espacios y ciertos signos de puntuación (guiones bajos, guiones, corchetes, puntos, apóstrofes y comas).",
    VM_ERRORS: "Se ha creado la máquina virtual, pero hubo errores. Verifique los parámetros de la nueva máquina virtual."
})
