({
    // Layout
    SYS_INFO_HEADER: "Parámetros del sistema",
    SYS_INFO_WALLPAPER_TITLE: "Tapiz",
    SYS_INFO_POWER_TITLE: "Energía",
    SYS_INFO_TOUCHPAD_TITLE: "Interfaz",
    SYS_INFO_TRANSMITTER_TITLE: "Synchronizer",
    SYS_INFO_AUTH_TITLE: "Inicio de sesión",
    SYS_INFO_SOFTWARE_TITLE: "Software",
    SYS_INFO_HARDWARE_TITLE: "Hardware",
    SYS_INFO_NETWORK_TITLE: "Funciones de red",
    STATUS_REPORT_HEADER: "Informe de estado",
    WALLPAPER_HEADER: "Haga clic en la imagen de tapiz que quiera",
    VENDOR_LABEL: "Proveedor:",
    MODEL_LABEL: "Modelo:",
    BIOS_REV_LABEL: "Revisión de BIOS:",
    TOTAL_MEM_LABEL: "Memoria física total:",
    MEMORY_MASK: "{0:n} MB",
    FREE_MEM_LABEL: "Memoria física libre:",
    FREE_STORAGE_LABEL: "Espacio libre en disco:",
    TOTAL_STORAGE_LABEL: "Espacio total en disco:",
    DISK_SPACE_MASK: "{0:n} MB",
    CPU_MODEL_LABEL: "Modelo de CPU física:",
    GPU_MODEL_LABEL: "Modelo de GPU física:",
    ETH0_MAC_ADDRESS_LABEL: "Dirección MAC con cable:",
    ETH0_MODEL_LABEL: "Modelo con cable:",
    HOST_AMT_PT_LABEL: "Paso de credenciales mediante dirección MAC:",
    ON_TEXT: "Habilitado",
    OFF_TEXT: "Inhabilitado",
    WIRELESS_MAC_ADDRESS_LABEL: "Dirección MAC inalámbrica:",
    WIRELESS_MODEL_LABEL: "Modelo inalámbrico:",
    XENCLIENT_VERSION_LABEL: "Versión de OpenXT:",
    XENCLIENT_VERSION_MASK: "{0} (rama {1})",
    XENCLIENT_BUILD_LABEL: "Compilación de OpenXT:",
    XENCLIENT_BUILD_MASK: "{0} ({1:d MMMM y})",
    TOOLS_VERSION_LABEL: "Versión del CD de herramientas:",
    UPDATE_TITLE: "Actualización de software",
    UPDATE_TOOLTIP: "El administrador debe suministrar la dirección URL para actualizar OpenXT",
    UPDATE_ACTION: "Comprobar actualizaciones",
    CANCEL_DOWNLOAD_ACTION: "Cancelar descarga",
    DISCARD_UPDATE_ACTION: "Descartar actualización",
    UPDATE_SHUTDOWN: "La descarga fue correcta, reinicie su dispositivo para aplicar la actualización",
    LID_CLOSE_LABEL: "Acción al cerrar la tapa",
    LID_CLOSE_AC_POWER_LABEL: "Corriente alterna:",
    SLEEP_ALL_OPTION: "Suspender el sistema entero",
    DO_NOTHING_OPTION: "No hacer nada",
    LID_CLOSE_BATTERY_LABEL: "Batería:",
    BRIGHTNESS_LABEL: "Brillo de pantalla",
    TOUCHPAD_OPTIONS: "Opciones del panel táctil",
    TAP_TO_CLICK_LABEL: "Clic con toque para el panel táctil:",
    SCROLLING_LABEL: "Desplazamiento con panel táctil:",
    SPEED_LABEL: "Velocidad del panel táctil",
    SLOW: "Lento",
    FAST: "Rápido",
    LEFT: "Izquierda",
    RIGHT: "Derecha",
    POINTER_TRAIL: "Rastro del puntero",
    NONE_TEXT: "Ninguno",
    SHORT_TEXT: "Corto",
    LONG_TEXT: "Largo",
    KEYBOARD_LAYOUT: "Distribución del teclado",
    LANGUAGE_HEADER: "Idioma",
    TRANSMITTER_STATE_LABEL: "Estado:",
    TRANSMITTER_STATE_UNREGISTERED: "Sin registrar",
    TRANSMITTER_STATE_PREREGISTERED: "Preregistrado",
    TRANSMITTER_STATE_CONNECTED: "Conectado",
    TRANSMITTER_STATE_DISCONNECTED: "Desconectado",
    TRANSMITTER_URL_LABEL: "Nombre de host de Synchronizer:",
    TRANSMITTER_VERSION_LABEL: "Versión:",
    TRANSMITTER_BUILD_LABEL: "Compilación:",
    TRANSMITTER_LOGGEDIN_LABEL: "Usuario registrado:",
    TRANSMITTER_HEADER: "Regístrese con un Synchronizer para descargar nuevas VM y mantener copias de seguridad.",
    REGISTER_ACTION: "Registrar",
    CONNECT_ACTION: "Conectar con Synchronizer",
    AUTH_SET_PASSWORD_TEXT: "Establezca una contraseña para habilitar la autenticación local",
    SET_PASSWORD_ACTION: "Establecer contraseña",
    CHANGE_PASSWORD_ACTION: "Cambiar contraseña",
    AUTH_REQUIRED_TEXT: "Contraseña al iniciar:",
    AUTH_SET_TIMEOUT_TEXT: "Tiempo de espera de bloqueo de pantalla:",
    STATUS_REPORT: "La creación de un informe de estado recopila información de diagnóstico de este dispositivo y la empaqueta en un archivo único.<br/><br/>Esto puede hacerse en cualquier momento, presionando CTRL+ALT+R",
    CREATE_STATUS_REPORT: "Crear informe de estado",
    STATUS_SERVER_HEADER: "Descarga de informes",
    STATUS_SERVER: "Consulte el capítulo sobre solución de problemas (Troubleshooting) en la guía del usuario de OpenXT para ver información sobre cómo descargar los informes de estado.",
    BEGIN_STATUS_SERVER: "Permitir informes descargables",
    STATUS_SERVER_INFO: "Sólo debe permitirse la descarga de informes si la red donde se encuentra el equipo es segura y el administrador le permite hacerlo.",
    CLOSE_ACTION: "Cerrar",
    SAVE_ACTION: "Guardar",
    SYS_INFO_DISPLAY_TITLE: "Pantalla",
    SEAMLESS_HEADER: "Cambio de puntero",
    SWITCHER_LABEL: "Cambio de puntero:",
    RESISTANCE_LABEL: "Resistencia de cambio:",
    KEYBOARD_LABEL: "Teclado sigue al puntero:",
    ADAPTER_LABEL: "Configure el orden de los adaptadores de pantalla para los movimientos integrados del puntero.",
    LANGUAGE_WARNING: "El parámetro de idioma se ha cambiado y es necesario reiniciar la interfaz de usuario.",
    // Other
    AUTH_MANAGED_TEXT: "Use sus credenciales de Synchronizer para iniciar la sesión.",
    MINUTE: "minuto",
    MINUTES: "minutos",
    NEVER: "nunca",
    ALREADY_CONNECTED: "Ya está conectado con Synchronizer.",
    UPDATE_HEADER: "Actualización de software",
    CANNOT_UPGRADE: "Versión de OpenXT instalada: {0}\nVersión de OpenXT más reciente: {1}\n\nNo es posible actualizar a esta versión de OpenXT.",
    CAN_UPGRADE: "Versión de OpenXT instalada: {0}\nVersión de OpenXT más reciente: {1}\n\nSe ha detectado una versión más reciente de OpenXT. ¿Quiere descargar esta actualización?\n\nConsulte la documentación para obtener más información sobre cómo puede afectar esto al sistema.",
    UP_TO_DATE: "Versión de OpenXT instalada: {0}\nVersión de OpenXT más reciente: {1}\n\nEstá ejecutando ya la versión más reciente de OpenXT, pero puede descargarla y aplicar de nuevo la actualización.\n\nConsulte la documentación para obtener más información sobre cómo puede afectar esto al sistema.",
    START_DOWNLOAD_ACTION: "Descargar",
    SERVE_REPORT: "Los informes están disponibles para su descarga en otro equipo en:\n\n{0}\n\nEstán disponibles para descargarse en las VM de este equipo en:\n\n{1}",
    STOP_STATUS_SERVER: "Detener disponibilidad de informes",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "Suiza",
    KEYBOARD_LAYOUT_CN: "China",
    KEYBOARD_LAYOUT_FR: "Francia",
    KEYBOARD_LAYOUT_DE: "Alemania",
    KEYBOARD_LAYOUT_IT: "Italia",
    KEYBOARD_LAYOUT_JP: "Japón",
    KEYBOARD_LAYOUT_ES: "España",
    KEYBOARD_LAYOUT_GB: "Reino Unido",
    KEYBOARD_LAYOUT_US: "Estados Unidos",
    KEYBOARD_LAYOUT_RU: "Rusia",
    KEYBOARD_LAYOUT_CA: "Canadá",
    KEYBOARD_LAYOUT_BR: "Brasil",
    KEYBOARD_LAYOUT_NL: "Holanda",
    KEYBOARD_LAYOUT_NO: "Noruega",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Corea",
    KEYBOARD_LAYOUT_BE: "Bélgica",
    KEYBOARD_LAYOUT_DK: "Dinamarca",
    KEYBOARD_LAYOUT_IN: "India",
    KEYBOARD_LAYOUT_SE: "Suecia",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English"
})
