({
    // Layout
    DEFERRED_INSTALL_TITLE: "Bienvenido a OpenXT",
    EULA_HEADER: "Contrato de licencia de usuario final",
    KEYBOARD_HEADER: "Distribución del teclado",
    KEYBOARD_INSTR: "Seleccione una distribución de teclado.",
    LANGUAGE_HEADER: "Idioma",
    LANGUAGE_INSTR: "Seleccione un idioma.",
    ROOT_PASSWORD_HEADER: "Contraseña del sistema",
    // Keyboards
    KEYBOARD_LAYOUT_CH: "Suiza",
    KEYBOARD_LAYOUT_CN: "China",
    KEYBOARD_LAYOUT_FR: "Francia",
    KEYBOARD_LAYOUT_DE: "Alemania",
    KEYBOARD_LAYOUT_IT: "Italia",
    KEYBOARD_LAYOUT_JP: "Japón",
    KEYBOARD_LAYOUT_ES: "España",
    KEYBOARD_LAYOUT_GB: "Reino Unido",
    KEYBOARD_LAYOUT_US: "Estados Unidos",
    KEYBOARD_LAYOUT_RU: "Rusia",
    KEYBOARD_LAYOUT_CA: "Canadá",
    KEYBOARD_LAYOUT_BR: "Brasil",
    KEYBOARD_LAYOUT_NL: "Holanda",
    KEYBOARD_LAYOUT_NO: "Noruega",
    KEYBOARD_LAYOUT_LATAM: "Latin America",
    KEYBOARD_LAYOUT_KR: "Corea",
    KEYBOARD_LAYOUT_BE: "Bélgica",
    KEYBOARD_LAYOUT_DK: "Dinamarca",
    KEYBOARD_LAYOUT_IN: "India",
    KEYBOARD_LAYOUT_SE: "Suecia",
    // Languages
    LANGUAGE_DE: "Deutsch",
    LANGUAGE_ES: "Español",
    LANGUAGE_FR: "Français",
    LANGUAGE_IT: "Italian",
    LANGUAGE_JP: "日本語",
    LANGUAGE_KR: "Korean",
    LANGUAGE_RU: "Russian",
    LANGUAGE_CN: "简体中文",
    LANGUAGE_TW: "Chinese (Traditional)",
    LANGUAGE_US: "English",
    // Errors
    EULA_ERROR: "Acepte este Contrato de licencia de usuario final para usar OpenXT. Si lo cancela, OpenXT se cerrará.",
    KEYBOARD_ERROR: "Seleccione una distribución de teclado.",
    SET_SYSTEM_PASSWORD: "OpenXT necesita una contraseña del sistema."
})
