({
    // Controls
    START: "Iniciar",
    BACKGROUND_START: "Inicio silencioso",
    SHUT_DOWN: "Apagar",
    FORCE_SHUT_DOWN: "Forzar desactivado",
    LOGIN: "Inicio de sesión",
    DETAILS: "Detalles",
    DELETE: "Eliminar",
    // Tooltips
    XC_TOOLS_NOT_INSTALLED: "<strong>Las herramientas de OpenXT no están instaladas</strong><br/><br/>Para instalarlas haga doble clic en el CD virtual de Herramientas de OpenXT en el sistema operativo de su VM.",
    XC_TOOLS_OLD_VERSION: "<strong>Las herramientas de OpenXT necesitan actualizarse</strong><br/><br/>Para actualizarlas haga doble clic en el CD virtual de Herramientas de OpenXT en el sistema operativo de su VM.",
    // Layout
    NAME_MASK: "Nombre: {0}",
    STATUS_MASK: "Estado: {0}",
    SLOT_MASK: "Tecla del selector: CTRL + {0}",
    // VM States
    VM_CREATED : "iniciando",
    VM_STOPPED : "desactivado",
    VM_STOPPING : "deteniéndose",
    VM_REBOOTING : "reiniciando",
    VM_REBOOTED : "reiniciada",
    VM_PAUSED : "activado",
    VM_SUSPENDING : "hibernando",
    VM_SUSPENDED : "en hibernación",
    VM_RUNNING : "activado",
    VM_LOCKED : "bloqueado",
    VM_ASLEEP : "suspendida",
    // XenConstants.DesktopStates
    PUBLISHING: "cargando",
    BACKING_UP: "haciendo copia de seguridad",
    DOWNLOADING: "descargando",
    UPDATING: "actualizando",
    FORCE_UPDATING: "en actualización forzosa",
    READY: "lista",
    LOCKED: "bloqueado",
    REMOTE_LOCKED: "bloqueado",
    UNMANAGED: "sin administrar",
    // XenConstants.SyncOpStates
    PREPARING: "En preparación",
    PREPARATION_FAILED: "Fallo de preparación",
    TRANSFER_PENDING: "Transferencia pendiente",
    COMPUTING_DIGEST: "Calculando suma de comprobación",
    TRANSFER_ACTIVE: "Transfiriendo",
    TRANSFER_PAUSED: "En pausa",
    TRANSFER_FAILED: "Error",
    TRANSFER_NETINT_STALLED: "Esperando... Servidor no accesible",
    TRANSFER_ADMCTL_STALLED: "Esperando... Servidor ocupado",
    INSTALLING_IMAGE: "Instalando imagen",
    TRANSFER_FINISHED: "Transferencia finalizada",
    SHUTDOWN_REQUIRED: "Apagado requerido",
    CLEAN_SHUTDOWN_REQUIRED: "Apagado correcto requerido",
    BACKGROUND_FAILED: "Fallo de operación en segundo plano"
})
