({
    // Layout
    START: "Iniciar",
    BACKGROUND_START: "Inicio silencioso",
    SHUT_DOWN: "Apagar",
    REBOOT: "Reiniciar",
    HIBERNATE: "Hibernar",
    SLEEP: "Suspender",
    FORCE_SHUT_DOWN: "Forzar desactivado",
    LOGIN: "Inicio de sesión",
    UPLOAD_VM: "Cargar VM",
    BACKUP_NOW: "Hacer copia de seguridad ahora",
    CHECK_NOW: "Comprobar ahora",
    ADD_DEVICE: "Agregar dispositivo",
    DELETE: "Eliminar",
    DETAILS: "Detalles",
    PAUSE: "Pausa",
    RESUME: "Reanudar",
    RETRY: "Reintentar",
    CANCEL: "Cancelar",
    GENERAL: "General",
    DEVICES: "Dispositivos",
    DEVICE: "Dispositivo",
    NO_DEVICES: "No hay dispositivos conectados",
    OPTIONS: "Opciones",
    ACTIONS: "Acciones",
    ALWAYS_USE: "Usar siempre con esta VM",
    DISCONNECT: "Desconectar",
    SYNCHRONIZATION: "Sincronización",
    HARDWARE: "Hardware",
    ICON: "Icono",
    ADVANCED: "Avanzadas",
    NAME: "Nombre:",
    VCPUS: "CPU virtuales:",
    MEMORY: "Memoria (MB):",
    AUTOBOOT: "Arranque automático:",
    AUTOBOOT_TOOLTIP: "Iniciar esta VM cuando se inicie el host.",
    POWER_BEHAVIOUR: "Control de encendido:",
    POWER_BEHAVIOUR_TOOLTIP: "Cuando la VM se apague, se suspenda o hiberne, el dispositivo host hará lo mismo.",
    POWER_BEHAVIOUR_ENABLED: "El control de encendido afecta a la VM y al host",
    POWER_BEHAVIOUR_DISABLED: "El control de encendido afecta solamente a la VM",
    SWITCHER_KEY: "Tecla del selector:",
    TOOLS_CD: "CD de herramientas:",
    INSTALLED_TOOLS_MASK: "Instalado: {0}",
    THREED_GFX: "Gráficos 3D:",
    TYPE: "Tipo:",
    TYPE_XP_OPTION: "Microsoft Windows XP SP3 de 32 bits",
    TYPE_VISTA_OPTION: "Microsoft Windows Vista SP2 de 32 bits",
    TYPE_WIN7_OPTION: "Microsoft Windows 7 SP1 de 32 bits",
    TYPE_WIN7_64_OPTION: "Microsoft Windows 7 SP1 de 64 bits",
    TYPE_UBUNTU_OPTION: "Ubuntu 11.04 de 32 bits (experimental)",
    TYPE_UNKNOWN: "Desconocido",
    DESCRIPTION: "Descripción:",
    REGISTERED_USER: "Usuario registrado:",
    BACKUP_MODE: "Modo de copia de seguridad:",
    BACKUP_NONE: "Ninguno",
    BACKUP_USER: "Datos de usuario",
    BACKUP_ALL: "Todos los datos",
    BACKUP_SCHEDULE: "Programación de copia de seguridad:",
    UPDATE_SCHEDULE: "Programación de actualizaciones:",
    LEASE_EXPIRATION: "Caducidad de cesión:",
    SAVE_ACROSS_REBOOTS: "Guardar cambios para reinicios:",
    DESKTOP_NAME: "Nombre del escritorio:",
    CURRENT_VERSION: "Versión actual:",
    BASE_VERSION: "Versión superior:",
    WIRELESS_NETWORK: "Red inalámbrica:",
    WIRED_NETWORK: "Red de cable:",
    WIRED_NIC: "Dirección MAC con cable:",
    DISK_SPACE: "Espacio en disco:",
    ALLOW_OEM: "Permitir instalaciones OEM de Windows:",
    EXPOSE_HARDWARE_INFO: "Exponer información del hardware físico:",
    DISPLAY_VM: "Mostrar VM en la barra del selector:",
    AMT_PASSTHROUGH: "Paso de credenciales Intel AMT:",
    OEM_ACPI_PASSTHROUGH: "Exponer hardware OEM físico:",
    BOOT_ORDER: "Orden de arranque:",
    EDIT: "Modificar",
    SAVE: "Guardar",
    CLOSE: "Cerrar",
    MANAGED_ENABLED: "VM administrada",
    THREED_GRAPHICS_ENABLED: "Gráficos 3D habilitados",
    PUBLISH_APP_ENABLED: "Publicación de aplicaciones",
    ENABLED: "Habilitado",
    DISABLED: "Inhabilitado",
    NONE: "Ninguno",
    INSTALLED_NONE: "No hay herramientas instaladas",
    NEVER: "Nunca",
    ATTACHED: "Conectado",
    SHARED_WIRELESS: "Inalámbrica compartida",
    SHARED_3G: "3G compartida (experimental)",
    BRIDGED: "Con puente",
    SHARED: "Compartida",
    INTERNAL: "Interna",
    BRIDGED_MASK: "Con puente en {0}",
    SHARED_MASK: "Compartida en {0}",
    INTERNAL_MASK: "Interna en {0}",
    POLICY_DISABLED: "Inhabilitado por directiva",
    CHANGE_VERSION: "Cambiar versión",
    NAME_VALERROR: "Hay que introducir un nombre. El nombre no puede tener más de 60 caracteres y puede contener letras, números, espacios y ciertos signos de puntuación (guiones bajos, guiones, corchetes, puntos, apóstrofes y comas).",
    DESCRIPTION_VALERROR: "La descripción no puede tener más de 200 caracteres y puede contener letras, números, espacios y ciertos signos de puntuación (guiones bajos, guiones, corchetes, puntos, apóstrofes y comas).",
    MEMORY_MASK: "{0:n}",
    SYSTEM_MEMORY_MASK: "Total: {0:n}, Libre: {1:n}",
    DISK_SPACE_MASK: "Privado: {0}, Compartido: {1}",
    BACKUP_FREQUENCY_MASK: "{0:n} hora(s)",
    UPDATE_FREQUENCY_MASK: "{0:n} minuto(s)",
    LEASE_EXPIRATION_MASK: "{0:n} día(s)",
    BACKUP_LAST_MASK: "Última copia de seguridad: {0:d MMMM y H:mm} (UTC)",
    UPDATE_LAST_MASK: "Última actualización: {0:d MMMM y H:mm} (UTC)",
    BACKUP_SCHEDULE_MASK: "Próxima copia de seguridad: {0:d MMMM y H:mm} (UTC)",
    UPDATE_SCHEDULE_MASK: "Próxima comprobación de actualizaciones: {0:d MMMM y H:mm} (UTC)",
    LEASE_SCHEDULE_MASK: "Próximo: {0:d MMMM y H:mm} (UTC)",
    BACKUP_LAST_MASK_1: "Última copia de seguridad realizada hace {0:n} hora(s), {1:n} minuto(s)",
    UPDATE_LAST_MASK_1: "Última actualización realizada hace {0:n} hora(s), {1:n} minuto(s)",
    BACKUP_NEXT_MASK: "Próxima copia de seguridad en {0:n} hora(s), {1:n} minuto(s)",
    UPDATE_NEXT_MASK: "Próxima comprobación de actualización en {0:n} hora(s), {1:n} minuto(s)",
    LEASE_NEXT_MASK: "Próximo en {0:n} día(s), {1:n} hora(s)",
    NETWORK_INFORMATION: "Una red <strong>con puente</strong> conecta una VM directamente a la red externa.<br/>Una red <strong>compartida</strong> reutiliza una única dirección IP de red para todas las VM.<br/>La red <strong>interna</strong> no está conectada a ninguna red externa.",
    TRANSFER: "Transferencia",
    TRANSFER_STATE: "Estado:",
    TRANSFER_PROGRESS: "Progreso:",
    TRANSFER_SPEED_MASK: "{0:f} MB/s",
    SWITCHER_KEY_MASK: "CTRL + {0}",
    SWITCHER_DROPDWON_MASK: " ({0})",
    THIS_VM: "esta VM",
    CD_DRIVE: "Unidad de CD",
    HARD_DRIVE: "Disco duro",
    NETWORK: "Red",
    BOOT_TITLE: "Agregar opción de arranque...",
    HDX_TOOLTIP: "Solamente se puede ejecutar una máquina virtual en el sistema con estas capacidades cada vez. Para habilitar esta función, la máquina virtual debe estar apagada y tener instalados los controladores de vídeo de Intel y las Herramientas de OpenXT.",
    MEMORY_TOOLTIP: "Esta característica no puede modificarse cuando la máquina virtual está en hibernación.",
    VCPU_TOOLTIP: "Esta característica no puede modificarse cuando la máquina virtual está en hibernación.",
    DISK_SPACE_TOOLTIP: "Privado: Espacio en disco utilizado solamente por esta máquina virtual.<br/>Compartido: Espacio en disco compartido con otras máquinas virtuales en el sistema.",
    AMT_PT_TOOLTIP: "La habilitación de Intel Active Management Technology (AMT) Management Engine (ME) ofrece una administración de redes basada en hardware, que permite el acceso fuera de banda a dispositivos OpenXT con fines administrativos. Sólo puede haber una VM con esta función habilitada.",
    ACPI_PT_TOOLTIP: "Exponer la tabla ACPI SLIC del host a la VM para desbloquear ediciones OEM de Windows.",
    SMBIOS_PT_TOOLTIP: "Exponer los tipos de registros de SMBIOS que describen el hardware del host a la VM en lugar de los suministrados por OpenXT.",
    OEM_ACPI_PT_TOOLTIP: "Exponer el hardware de OEM directamente a la VM. Sólo puede haber una VM con esta función habilitada.",
    POWER: "Energía",
    COMMUNICATION: "Respaldo de aplicaciones integradas:",
    COMMUNICATION_TOOLTIP: "Controla los parámetros de servidor de seguridad de la máquina virtual para que funcionen las aplicaciones integradas.",
    ADVANCED_WARNING: "Esta sección contiene funciones avanzadas y solamente deben modificarse si se conoce el impacto que tienen en el sistema.",
    INTEL_AMT: "El paso de credenciales mediante Intel AMT ME no tendrá efecto hasta que se reinicie OpenXT.",
    MEMORY_CHANGE: "El cambio de memoria tendrá lugar cuando vuelva a iniciarse la máquina virtual",
    BACKUP_VM: "Copia de seguridad de la VM",
    VM_UPDATE_CHECK: "Comprobar actualizaciones de la VM",
    DELETE_VM_HEADER: "Eliminar máquina virtual",
    DELETE_VM: "¿Seguro que quiere eliminar la máquina virtual '{0}'?",
    ACCEPT_DELETE: "Sí, eliminarla",
    XEN_MGR_DELETE: "Eliminar VM",
    USB_UNASSIGN: "Este dispositivo USB está siendo utilizado actualmente por esta VM. Si lo quita de la selección se forzará su desconexión, lo que podría ocasionar una pérdida de datos. Puede quitar de forma segura este dispositivo, expulsándolo desde dentro del sistema operativo de la VM.",
    UPLOAD_VM_STATUS: "Sólo se puede cargar una máquina virtual cuando se encuentra desconectada.",
    ADD_DEVICE_STATUS: "Sólo se puede conectar un dispositivo cuando la máquina virtual está encendida y tiene instaladas las Herramientas de OpenXT",
    DELETE_VM_STATUS: "Sólo se puede eliminar una máquina virtual cuando se encuentra desconectada o en hibernación.",
    FORCE_UPDATE: "Error al forzar la actualización de la VM",
    USB_DISABLED: "No se puede agregar un dispositivo porque la administración de dispositivos está inhabilitada para esta VM"
})
